### PR TITLE
fix: Make resolution of UTC_NOW the same across transaction

### LINKED ISSUE #4231: Multiple instances of UTC_NOW in a transaction should resolve to the same value
Consider running the following:

```
defradb client schema add '
  type User {
    name: String 
    created: DateTime @default(dateTime: UTC_NOW) 
  }
'

defradb client query '
mutation {
    bob: create_User(input: { name: "Bob" }) {
        _docID
        name
        created
    }

    alice: create_User(input: { name: "Alice" }) {
        _docID
        name
        created
    }
}
'
```

Currently, we expect the `created` timestamp on both documents to be slightly different from one another, as instances of `UTC_NOW` are resolved separately for each mutation. This is not the desired behavior. All instances of it should resolved to exactly the same value.

### PR DESCRIPTION
**Pull request by ChrisBQu**
## Relevant issue(s)

Resolves #4231 

## Description

This PR makes it so that across a transaction, all instances of `UTC_NOW` will resolve to the same value. 

The core work is done by adding a new field to `datastore.BasicTxn`, called `ts` for timestamp. We also add function to the `datastore.Txn` interface, `StartTS()` which returns the timestamp. This value is then propogated down inside a context. The new `clock` package defines the context key that is used for this purpose, and contains the functions that add a timestamp to, and get a timestamp from, a given context.

You can see that many function signatures have been touched to facilitate this passing down-and-through of the context: `client.NewDocFromMap`, `client.NewDocWithID`, `doc.SetWithJSON`, etc. In most of these places, the change will be straightforward, and the reason for the change will hopefully be self-evident.

Additionally, this PR includes several integration tests which illustrate the new functionality. Further, the client wrappers have all been adjusted accordingly, such that the Txn wrappers fit the new interface.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Specify the platform(s) on which this was tested:
- WSL

### CODE REVIEW

File: internal/datastore/txn.go [hunk 1]
```diff
@@ -45,6 +46,9 @@ type Txn interface {
 	// ID returns the unique immutable identifier for this transaction.
 	ID() uint64
 
+	// StartTS returns the start timestamp of the transaction
+	StartTS() time.Time
```
Comment (AndrewSisley) [inline internal/datastore/txn.go:50]: question: This very much looks like a different timestamp to the GQL `UTC_NOW`, and suggests that other future timestamps are possible, such as `CommitTS`.

Do you have plans for other timestamps? If not, are you sure you want this held on the transaction?

Comment (ChrisBQu) [reply internal/datastore/txn.go:50]: That code was actually written by John. He took a swing at the problem that was very different than my original approach. But let's discuss it in the standup.

**Review by fredcarle — APPROVED** [review]
LGTM
