### PR TITLE
fix: Ensure list p2p replicator nac gate works

### LINKED ISSUE #4109: Test ListReplicators/GetAllReplicators Operation with NAC
Test ListReplicators/GetAllReplicators Operation with NAC

While doing NAC gates for p2p operations I noticed that there was an un unused action for this, that isn't tested.

So add the test for normal and NAC case.

### PR DESCRIPTION
**Pull request by shahzadlone**
## Relevant issue(s)
Resolves #4109 

## Description
- Test list p2p replicator with NAC

### CODE REVIEW

File: tests/integration/p2p_replicator.go [hunk 1]
```diff
@@ -74,29 +74,6 @@ type DeleteReplicator struct {
 	ExpectedError string
 }
 
-// ListReplicators gets the configured replicators for the given node and compares them against the
-// expected results.
-// TODO: Test ListReplicators with and without NAC.
-// https://github.com/sourcenetwork/defradb/issues/4109
-type ListReplicators struct {
```
Comment (AndrewSisley) [inline tests/integration/p2p_replicator.go:81]: todo: It looks like you have removed the old action, but not the old code that handled it.  Please remove that code too, as significant parts of it should now be dead.

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
It looks like the CLI client is failing the new tests.

File: tests/integration/p2p_replicator.go (hunk 1 above)
Comment (shahzadlone) [reply tests/integration/p2p_replicator.go:81]: What old code that handled it (I thought this was dead code)?

The only other place I see references of `ListReplicators` (other than stuff introduced in this PR) is in the clients:
- `tests/clients/js/wrapper.go`
- `tests/clients/http/wrapper.go`
- `tests/clients/cli/wrapper.go`

**Comment by shahzadlone** [comment]
> It looks like the CLI client is failing the new tests.

There was a bug found for cli client as they identity wasn't being passed to it. Should now have been fixed :)

File: tests/integration/p2p_replicator.go (hunk 1 above)
Comment (AndrewSisley) [reply tests/integration/p2p_replicator.go:81]: Oh my bad, sorry - I thought you migrated an existing action to the `action` package :)

**Review by AndrewSisley — APPROVED** [review]
LGTM, thanks Shahzad.

suggestion: Consider changing the PR title to `fix:...` as this now fixes a bug

**Comment by shahzadlone** [comment]
> suggestion: Consider changing the PR title to `fix:...` as this now fixes a bug

Good suggestion, will do!
