### PR TITLE
fix: Use index with _or conditions on same field

### LINKED ISSUE #4399: _or filter with index returns empty
Queries using `_or` filter with indexed fields return empty results

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4399

## Description

Implement index handling of _or filter operator if all conditions are on the same field.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Integration tests

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/db/fetcher/indexer_iterators.go [hunk 1]
```diff
@@ -439,12 +476,12 @@ func (f *indexFetcher) newPrefixBasedMatchIteratorFromConditions(
 	return iter, nil
 }
 
-// newInIndexIterator creates a new inIndexIterator for fetching indexed data.
+// newInIndexIterator creates a new multiIndexIterator for fetching indexed data using _in filter.
 // It can modify the input matchers slice.
 func (f *indexFetcher) newInIndexIterator(
```
Comment (fredcarle) [inline internal/db/fetcher/indexer_iterators.go]: suggestion: The name of this method should probably be changed to `newMultiIndexIterator`.

**Review by fredcarle — APPROVED** [review]
LGTM

File: internal/db/fetcher/indexer_iterators.go (hunk 1 above)
Comment (islamaliev) [reply internal/db/fetcher/indexer_iterators.go]: done
