### PR TITLE
fix: Sync DAG

### LINKED ISSUE #4272: Improve syncDAG performance

### PR DESCRIPTION
**Pull request by iverc**
## Relevant issue(s)

Resolves #4272

## Description

This PR fixes syncDAG performance/concurrency issues.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

(*replace*) Describe the tests performed to verify the changes. Provide instructions to reproduce them.

Specify the platform(s) on which this was tested:
- Debian Linux
- MacOS

### CODE REVIEW

**Review by fredcarle — APPROVED** [review]
LGTM. Please create an issue and link it to the PR before merge.

It's a nice coincidence that you did this now as I wanted to rework this function after my current P2P work.

File: internal/db/p2p/sync_dag.go [hunk 1]
```diff
@@ -38,32 +36,27 @@ func makeLinkSystem(blockService blockstore.IPLDStore) linking.LinkSystem {
...
-	return p.loadBlockLinks(ctx, &linkSystem, block)
+	return p.loadBlockLinks(sessionCtx, &linkSystem, block)
 }
 
 // loadBlockLinks loads the links of a block recursively.
 //
-// If it encounters errors in the concurrent loading of links, it will return
-// the first error it encountered.
+// The function returns immediately on the first error encountered.
 func (p *P2P) loadBlockLinks(ctx context.Context, linkSys *linking.LinkSystem, block *coreblock.Block) error {
```
Comment (fredcarle) [inline internal/db/p2p/sync_dag.go:61]: suggestion: If you want to take care of the early exit from DAG walk, just add the following block of code either at the beginning of `loadBlockLinks` or before the recursion using `continue` instead of returning.

```go
link, err := block.GenerateLink()
if err != nil {
	return err
}
bstore := datastore.BlockstoreFrom(p.db.Rootstore(), immutable.None[int]())
merged, err := bstore.IsMerged(ctx, link.Cid)
if err != nil {
	return err
}
if merged {
	return nil
}
```
