### PR TITLE
fix(i): Retain embedded schema within gql types on reload

### LINKED ISSUE #2184: Schema used in Views disappear when later updating the GQL types
As inner `interface` types are collection-less, they are not reloaded when further modifying the types.

For example the below will error as `BookView` is 'forgotten' when adding the `User` collection to the GQL types:
```
			testUtils.SchemaUpdate{
				Schema: `
					type Author {
						name: String
						books: [Book]
					}
					type Book {
						name: String
						author: Author
					}
				`,
			},
			testUtils.CreateView{
				Query: `
					Author {
						name
						books {
							name
						}
					}
				`,
				SDL: `
					type AuthorView {
						name: String
						books: [BookView]
					}
					interface BookView {
						name: String
					}
				`,
			},
			testUtils.SchemaUpdate{
				Schema: `
					type User {
						name: String
					}
				`,
			},
```

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #2184 #2182

## Description

Retain embedded schema within gql types on reload and further GQL modification.

Also refactors the code a little to make it harder to re-introduce (calling `loadSchema` instead of sometimes relying on function vars).

Appears to accidentally solve #2182
Todo: 
- [x] Add proper tests for #2182

### CODE REVIEW

File: tests/integration/schema/simple_test.go [hunk 1]
```diff
@@ -78,7 +78,7 @@ func TestSchemaSimpleErrorsGivenDuplicateSchema(t *testing.T) {
 				Schema: `
 					type Users {}
 				`,
-				ExpectedError: "schema type already exists",
+				ExpectedError: "collection already exists",
```
Comment (AndrewSisley) [inline tests/integration/schema/simple_test.go:81]: note: These changed as the order in which `loadSchema` was called changed slightly.  I think the new error is more correct anyway.

**Review by fredcarle — APPROVED** [review]
LGTM
