### PR TITLE
fix: Prevent blocking on server close

### LINKED ISSUE #3976: HTTP server close blocks when graphql subscription is active.

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #3976 

## Description

This PR fixes an issue where the Defra would block on close when a graphql subscription was active. This was only problematic for graphql subscriptions over HTTP.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Changed the test util and clients using HTTP to not automatically exit when all actions are done.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: http/handler_store.go [hunk 1]
```diff
@@ -294,10 +294,29 @@ func (s *storeHandler) ExecRequest(rw http.ResponseWriter, req *http.Request) {
...
 			return
+		case <-serverDone:
+			// We need to check for closure of the server context
+			// otherwise the server won't gracefully shutdown until all
+			// connections are closed.
+			_, err := fmt.Fprintf(rw, "event: complete\n")
+			if err != nil {
+				return
+			}
+			_, err = fmt.Fprintf(rw, "data: {}\n\n")
```
Comment (shahzadlone) [inline http/handler_store.go:314]: question: why are there two newlines (`\n\n`)?

File: tests/integration/subscription/subscription_test.go [hunk 2]
```diff
@@ -344,3 +344,22 @@ func TestSubscriptionWithUpdateAllMutations(t *testing.T) {
 
 	execute(t, test)
 }
+
+func TestSubscription_WithClose_WontBlock(t *testing.T) {
```
Comment (shahzadlone) [inline tests/integration/subscription/subscription_test.go:348]: Question: This test would fail before this PR, correct?

**Review by shahzadlone — APPROVED** [review]
Just some non-blocking questions.

LGTM

File: http/handler_store.go (hunk 1 above)
Comment (fredcarle) [reply http/handler_store.go:314]: Thats how SSE determines that the message is complete.

File: tests/integration/subscription/subscription_test.go (hunk 2 above)
Comment (fredcarle) [reply tests/integration/subscription/subscription_test.go:348]: With the changes to the test clients and util but without the fix, yes. The test clients were forcing client connections to close which hid this issue.

**Comment by getify** [comment]
awesome work!
