### PR TITLE
fix: Test matcher subscription bug

### LINKED ISSUE #4428: Test matcher subscription bug
I discovered a problem when debugging this test: `TestCommitSubscription_WithDocFilterAndMultipleMutations_FilteredDoc`

Test matchers are reset before subscriptions are finished, which means any matchers used within the subscription will give incorrect results.

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #4428

## Description

This PR fixes a bug with test matchers in subscriptions.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Integration tests.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: tests/integration/subscription/with_commit_test.go [hunk 1]
```diff
@@ -194,6 +194,14 @@ func TestCommitSubscription_WithDocFilterAndMultipleMutations_FilteredDoc(t *tes
...
 				}`,
 				Results: []map[string]any{
+					{
+						"_commits": []map[string]any{
+							{
+								"cid":   "bafyreib5dvg3wkm722kietpvx5gmfueilyvywyiz2tl44q6xnhv4bedcpq",
+								"docID": docID,
+							},
+						},
+					},
```
Comment (fredcarle) [inline tests/integration/subscription/with_commit_test.go:206]: question: I'm struggling to understand how we get 2 separate commits results. Why do we now have a second commit in the result set?

Comment (nasdf) [reply tests/integration/subscription/with_commit_test.go:206]: One for the create and one for the update

Comment (fredcarle) [reply tests/integration/subscription/with_commit_test.go:206]: We shouldn't be getting the one for the create since the subscription was initiated after the create call. That's why I'm puzzled by this.

Comment (nasdf) [reply tests/integration/subscription/with_commit_test.go:206]: My guess would be that the create action just after the subscription triggers it to refresh.

Comment (nasdf) [reply tests/integration/subscription/with_commit_test.go:206]: I just verified that is what's happening. We don't filter the select based on the DocID.

https://github.com/sourcenetwork/defradb/blob/38d0766692633817e0658f8548bd8fd13f4b71e2/client/request/commit.go#L61-L76

Comment (fredcarle) [reply tests/integration/subscription/with_commit_test.go:206]: Thanks for testing. I was about to do that myself. 

I think we are filtering based on the DocID but not doing the `&` operation with the CID that would filter out the result.

Comment (fredcarle) [reply tests/integration/subscription/with_commit_test.go:206]: Either way it's a bug. Thanks for finding it :)

**Review by fredcarle — APPROVED** [review]
Approving but before merge please open an issue explaining the bug and link the issue to a `TODO` above the test result item.
