### PR TITLE
fix(i): Aggregate json filter

### LINKED ISSUE #3149: Aggregate with JSON object filter does not work
This schema:

```
type Users {
  custom: JSON
}
```

with this query:

```gql
query {
  _count(Users: {filter: {custom: {tree: {_eq: "oak"}}}})
}
```

returns an error:

```
type not found. Type: custom
```

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #3149

## Description

This PR fixes an issue with aggregate JSON filtering.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Added integration test.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/planner/mapper/mapper.go [hunk 1]
```diff
@@ -569,6 +570,32 @@ func resolveAggregates(
 	return fields, nil
 }
 
+// fixAggregateNestedTargets ensures that selections of
+// JSON objects are not interpreted as joins.
+//
+// This can happen when an aggregate contains a filter
+// on a JSON object, but we can't tell if it is a relation
+// until the child mapping is created.
+func fixAggregateNestedTargets(
```
Comment (fredcarle) [inline internal/planner/mapper/mapper.go:579]: suggestion: I got stuck on this function name a little too long for my liking lol. I think the `fix` prefix threw me off. This fonction does something that is very specific to JSON objects so my suggestion is to make that clearer in the name. What we are really doing here is filtering out/removing JSON sub-fields from the selection set.

Also, this is used at the moment specifically for aggregates but there is nothing in the function itself that handles aggregate specific objects.

As a result of the above, I would suggest renaming to `removeJSONSubFields`.

**Review by fredcarle — APPROVED** [review]
Thanks for fixing. I just have a suggestion regarding the function name.

File: tests/integration/query/json/with_aggregate_test.go [hunk 2]
```diff
@@ -0,0 +1,55 @@
+package json
```
Comment (AndrewSisley) [inline tests/integration/query/json/with_aggregate_test.go:1]: todo: Please add some more tests.  At least one to cover the `default` case in the switch, and another where `isMapped` is false.  Also consider tests for invalid user filters, although that could arguably be done in the other JSON filter PR.

Comment (shahzadlone) [reply tests/integration/query/json/with_aggregate_test.go:1]: +1

Comment (nasdf) [reply tests/integration/query/json/with_aggregate_test.go:11]: I've added an additional test to cover the `isMapped` case. The `default` case is technically dead code but removing it could cause a hard to find bug in the future.

File: internal/planner/mapper/mapper.go (hunk 1 above)
Comment (nasdf) [reply internal/planner/mapper/mapper.go]: Renamed to `removeJSONSubFields` as suggested

File: tests/integration/query/json/with_aggregate_test.go (hunk 2 above)
Comment (AndrewSisley) [reply tests/integration/query/json/with_aggregate_test.go:11]: Okay no worries, I have a very minor preference for an error to be returned from `default` then, but happy as is, so only change it if you like the suggestion.

Thanks for the `isMapped` test :)

**Review by AndrewSisley — APPROVED** [review]
LGTM, thanks Keenan!
