### PR TITLE
fix: Improve NonNull error message

### LINKED ISSUE #1191: Error when adding non-null developer-defined type
Schema:
```
type A {
  s: String
}

type B {
  as: [A!]
}
```

Error on adding schema:
```
  {
    "message": "no type found for given name. Type: A",
    "extensions": {
      "status": 500,
      "httpError": "Internal Server Error"
    }
  }
```

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1191

## Description

Improves the NonNull error message when attempting to declare an inline array for an unsupported type.

### CODE REVIEW

File: tests/integration/schema/simple_test.go [hunk 1]
```diff
@@ -227,5 +227,26 @@ func TestSchemaSimpleErrorsGivenNonNullField(t *testing.T) {
 		},
 	}
 
-	testUtils.ExecuteTestCase(t, []string{"users"}, test)
+	testUtils.ExecuteTestCase(t, []string{"Users"}, test)
```
Comment (shahzadlone) [inline tests/integration/schema/simple_test.go:230]: thought: Would be nice to have an error raised upon incorrect / unknown Collection name.

**Review by shahzadlone — APPROVED** [review]
LGTM! Thanks

File: tests/integration/schema/simple_test.go (hunk 1 above)
Comment (AndrewSisley) [reply tests/integration/schema/simple_test.go:230]: I think a better fix would to not require this param at all :)
