### PR TITLE
fix(i): Tests with primary doc patch update events

### LINKED ISSUE #2849: Integration tests don't account for primary document patches
The integration test event logic does not account for updates from primary document patching.

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #2849

## Description

This PR fixes an issue with primary document patch updates. We also now assert that the document updates match the expected updates. We can most likely remove the `events` test package now that every test asserts the expected events.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

`make test`

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: tests/integration/events.go [hunk 1]
```diff
@@ -148,52 +150,76 @@ func waitForUnsubscribeToCollectionEvent(s *state, action UnsubscribeToCollectio
...
+			require.True(s.t, ok, "unexpected document update")
+			delete(expect, evt.DocID)
 
-		// update the expected document heads of replicator targets
-		for id := range s.nodeP2P[i].replicators {
-			// replicator target nodes push updates to source nodes
-			s.nodeP2P[id].expectedDocHeads[evt.DocID] = evt.Cid
-		}
+			if i >= len(s.nodeConfigs) {
+				continue // not testing network state
```
Comment (AndrewSisley) [inline tests/integration/events.go:187]: todo: This comment caused me a fair bit of confusion, and I initially thought it was skipping P2P tests (via some strange mechanic that I didn't yet understand).  Can you please rework the comment a bit?

File: tests/integration/events.go [hunk 2]
```diff
@@ -148,52 +150,76 @@ func waitForUnsubscribeToCollectionEvent(s *state, action UnsubscribeToCollectio
...
-		select {
-		case msg, ok := <-s.nodeEvents[i].update.Message():
-			if !ok {
-				require.Fail(s.t, "subscription closed waiting for update event")
-			}
-			evt = msg.Data.(event.Update)
-
-		case <-time.After(eventTimeout):
-			require.Fail(s.t, "timeout waiting for update event")
+		expect := make(map[string]struct{})
```
Comment (AndrewSisley) [inline tests/integration/events.go:163]: todo: Please set the length in the `make` call instead of resizing the map for each item.

File: tests/integration/events.go [hunk 3]
```diff
@@ -240,3 +266,84 @@ func waitForMergeEvents(s *state) {
...
+		}
+	}
+
+	return expect
+}
+
+// getEventsForDelete returns a map of expected update events for a document delete action.
+func getEventsForDelete(docID client.DocID) map[string]struct{} {
+	expect := make(map[string]struct{})
+	expect[docID.String()] = struct{}{}
```
Comment (AndrewSisley) [inline tests/integration/events.go:347]: todo: Please dont grow the map like this, please either set the length on `make`, or (IMO) better replace this with:
```
return map[string]struct{}{
   docID.String(): {},
}
```
I would probably delete the `getEventsForDelete` entirely and just do this inline where `getEventsForDelete`, it saves readers from having to bounce around the file when reading (I won't push for that as a todo though :)).

**Review by AndrewSisley — APPROVED** [review]
Thank you very much for removing that test package Keenan, just a couple of small todo's for you before merge :)

File: tests/integration/events.go [hunk 4]
```diff
@@ -148,52 +150,76 @@ func waitForUnsubscribeToCollectionEvent(s *state, action UnsubscribeToCollectio
 // update event to the local event bus.
 //
 // Expected document heads will be updated for any connected nodes.
-func waitForUpdateEvents(s *state, nodeID immutable.Option[int], collectionID int) {
+func waitForUpdateEvents(
+	s *state,
+	nodeID immutable.Option[int],
+	updates map[string]struct{},
```
[the remark this answers is not in the document]
Comment (nasdf) [reply tests/integration/events.go]: renamed to `docIDs`

File: tests/integration/events.go (hunk 1 above)
Comment (nasdf) [reply tests/integration/events.go]: I updated the docs and broke out the rest into a more dedicated function. Hopefully its more clear now.

File: tests/integration/events.go (hunk 3 above)
Comment (nasdf) [reply tests/integration/events.go]: I dropped the function and created the map like you suggested.
