### PR TITLE
fix: Add reconnection to known peers

### LINKED ISSUE #1481: Reconnect to known peers on restart

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #1481 

## Description

Currently, we de not reconnect to known peers on restart unless the peer is defined in the config file or on the CLI command. This PR makes sure that we try to reconnect to known peers.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test shows now degradation and tested manually that peers reconnect on restart.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by AndrewSisley — APPROVED** [review]
Approving so long as you test this manually first, as I don't have the bandwidth to finish of the restart tests atm, and `make test` (as stated in the PR description) will not test that this works atm.

File: net/peer.go [hunk 1]
```diff
@@ -137,6 +137,21 @@ func (p *Peer) Start() error {
...
 
+	// reconnect to known peers
+	for _, id := range p.host.Peerstore().PeersWithAddrs() {
+		go func(id peer.ID) {
+			addr := p.host.Peerstore().PeerInfo(id)
+			err := p.host.Connect(p.ctx, addr)
+			if err != nil {
+				log.Info(
+					p.ctx,
+					"Failed to reconnect to peer`",
```
Comment (shahzadlone) [inline net/peer.go:148]: todo: Why is there a backtick after peer?

suggestion: Change to this perhaps:
```suggestion
					"Failure while reconnecting to a known peer",
```

**Review by shahzadlone — APPROVED** [review]
A todo, and suggestion. Similar to Andy haven't manually tested. Giving an LGTM

File: net/peer.go (hunk 1 above)
Comment (fredcarle) [reply net/peer.go]: ✅
