### PR TITLE
fix: Make change detector skip transactional isolation tests

### LINKED ISSUE #4648: Make Change Detector skip tests exhibiting transactional isolation
Transactions are not and cannot be kept alive between two different DefraDB instances. This means tests that display transactional isolation, such as `TestTxn_DeleteIndex_ExhibitsTransactionalIsolation_Succeeds` cannot work with the change detector. Therefore, the detector should be adjusted to detect and skip these tests.

### PR DESCRIPTION
**Pull request by ChrisBQu**
## Relevant issue(s)

Resolves #4648 

## Description

Some tests do not work with the change detector. Specifically, tests that do things inside transactions without committing them, displaying transactional isolation, cannot work with the change detector. This adjusts the change detector logic to skip these tests. It does so by creating a set of transaction IDs that are created prior to the first action of a test. Upon seeing a CommitTransaction action, it removes the appropriate item from the set. Then, when this initial scan is done, we know that if any IDs are left in the set, it means the test uses uncommitted transactional behavior and must be skipped.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Specify the platform(s) on which this was tested:
-WSL

### CODE REVIEW

File: tests/integration/utils.go [hunk 1]
```diff
@@ -772,7 +775,34 @@ ActionLoop:
 			// We don't care about anything else if this has been explicitly provided
 			break ActionLoop
 
-		case *action.AddCollection, *action.AddDoc, UpdateDoc, Restart, CommitTransaction:
+		case *action.AddCollection:
+			concreteAction := testCase.Actions[i].(*action.AddCollection)
```
Comment (AndrewSisley) [inline tests/integration/utils.go]: todo: It looks like you can remove the casts here by declaring a variable on line 772:
```
switch concreteAction := testCase.Actions[i].(type) {
```

**Review by AndrewSisley — APPROVED** [review]
I feel like there should be a cleaner way (not thought much on it though), but this unblocks the build :)

Please have a quick look at the rabbit comment before merge.
