### PR TITLE
fix: Allow configuring node identity with embedded Defra

### LINKED ISSUE #4022: Can't set node identity when using embedded DefraDB
This came up when a team member tried to use embedded Defra and they noticed that the document block didn't contain any signature. The reason for this is that, even though signing is set to `true` by default, the node identity has to be configured to be able to produce the signature. 

When looking into configuring the node identity, they noticed that the only way to do so programatically is to call `db.WithNodeIdentity` which is an internal function that can't be used by `defradb` consumers.

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #4022

## Description

This PR simply exposes a node config to set the internal db node identity config.

Our test framework couldn't catch this since it has access to the internal package.

We had discussed making DB public again. I'll be looking into doing this in order to prevent these kinds of problems in the future.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

manual embedded defra test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: node/config.go [hunk 1]
```diff
@@ -70,6 +72,12 @@ func WithEnableDevelopment(enable bool) NodeOpt {
 	}
 }
 
+// WithNodeIdentity sets the identity for the node. This is the identity that
+// will be used for things like block signatures and P2P sync operations.
+func WithNodeIdentity(ident identity.Identity) db.Option {
```
Comment (AndrewSisley) [inline node/config.go:77]: suggestion: If it is simple to do, can you please use this in the test framework instead of the internal call you mentioned in the PR description?

**Review by AndrewSisley — APPROVED** [review]
LGTM

File: node/config.go (hunk 1 above)
Comment (fredcarle) [reply node/config.go:77]: Since we plan on making `db` public, I'd rather not change it now only to change it again later.
