### PR TITLE
fix: Serialize DB errors to json in http package

### LINKED ISSUE #1383: Errors dont Marshal nicely to json
Our errors, 3rd party errors, and std lib errors do not marshal nicely to json (typically marshal to an empty object).  This means that on request error, and empty object is sent back to GQL clients, which is not very useful to them.

e.g.:
```
{
  "errors": [
    {}
  ],
  "data": null
}
```
Issue also visible in #1382 

EDIT: Discussed over discord, agreed to handle error serialisation within the http package.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1383 

## Description

Serializes DB errors to json in http package. They were previously resolving to `"{}"`.

image

### CODE REVIEW

File: api/http/request_result.go [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+	Errors []string `json:"errors,omitempty"`
+
+	Data any `json:"data"`
+}
+
+func newGQLResult(r client.GQLResult) *GQLResult {
+	errors := make([]string, len(r.Errors))
+	for i := range r.Errors {
+		errors[i] = r.Errors[i].Error()
+	}
```
Comment (shahzadlone) [inline api/http/request_result.go:25]: nitpick:
```suggestion
	for i, e := range r.Errors {
		errors[i] = e.Error()
	}
```

File: api/http/handlerfuncs_test.go [hunk 2]
```diff
@@ -347,6 +347,46 @@ func TestExecGQLHandlerContentTypeJSON(t *testing.T) {
...
+	"query": "mutation {
+		create_user(
+			data: \"{
+				\\\"age\\\": 31,
+				\\\"notAField\\\": true
+			}\"
+		) {_key}
+	}"
+}`
+	// remote line returns and tabulation from formatted statement
```
Comment (shahzadlone) [inline api/http/handlerfuncs_test.go:370]: typo: Do you mean replace instead of remote?

Comment (AndrewSisley) [reply api/http/handlerfuncs_test.go:370]: My bad, this comment is here to indicate that the PR author's brain auto-filtered out the comments and failed to remove it having copy-pasted from the test above.

- [ ] remove?

File: api/http/request_result.go (hunk 1 above)
Comment (AndrewSisley) [reply api/http/request_result.go:25]: Ah, I'm happy with either.  Leaving as is

**Review by shahzadlone — APPROVED** [review]
LGTM

**Review by fredcarle — APPROVED** [review]
LGTM!
