### PR TITLE
fix: Add check to filter result for logical ops

### LINKED ISSUE #2571: Foreign object filter part of an `_or` set of filters doesn't seem to do anything
With a query of the form:
```graphql
query {
  Book (filter: {_or: [
    {title: {_ilike: "%Test3%"}},
    {author: {name: {_ilike: "%Test3%"}}},
    {subTitle: {_ilike: "%Test3%"}}
  ]}) {
    title
  }
}
```
The `{author: {name: {_ilike: "%Test3%"}}}` part of the filter doesn't seem to have any impact on the result. It seems like having this object filter inside an `_or` set doesn't work. The following does work however.
```graphql
query {
  Book (filter: {author: {name: {_ilike: "%Test3%"}}}) {
    title
  }
}
```

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2571

## Description

This PR adds a check post doc filtering in the fetcher to see if we need to rely on the external conditions instead to ensure a valid filtering operation. This is specially important when filtering with logical operators `_and` and `_or`.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by AndrewSisley — APPROVED** [review]
LGTM, thanks Fred!

File: planner/filter/complex.go [hunk 1]
```diff
@@ -32,6 +32,7 @@ func isComplex(conditions any, seekRelation bool) bool {
 		for k, v := range typedCond {
 			if op, ok := k.(*mapper.Operator); ok {
 				if (op.Operation == request.FilterOpOr && len(v.([]any)) > 1) ||
```
Comment (nasdf) [inline planner/filter/complex.go:34]: suggestion: I think this can be simplified a bit and avoid the potential panic from type casting.

```go
isOpComplex := false
switch op.Operation {
  case request.FilterOpOr:
    isOpComplex = isComplex(v, true)
  case request.FilterOpAnd:
    isOpComplex = isComplex(v, true)
  case request.FilterOpNot:
    isOpComplex = isComplex(v, true)
}
if isOpComplex {
  return true
}
continue
```

**Review by nasdf — APPROVED** [review]
LGTM. One minor suggestion.

**Review by shahzadlone — APPROVED** [review]
LGTM

File: planner/filter/complex.go (hunk 1 above)
Comment (fredcarle) [reply planner/filter/complex.go:34]: `v` can't be anything other than an `[]any` if it's an `_or` or `_and` operator and we don't want to classify them as complex if there is only one element in the array.

Comment (nasdf) [reply planner/filter/complex.go]: I don't think this changes the logic though. It just adds another recursive step.

Comment (fredcarle) [reply planner/filter/complex.go]: made a change in line with what you suggested. Let me know what you think.
