### PR TITLE
fix(i): Delete entire block dag on truncate

### LINKED ISSUE #4377: Truncate only deletes the head blocks
I forgot to walk them back.  We are currently orphaning a lot of blocks.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #4377

## Description

Deletes the entire block dag on truncate, instead of just the head blocks.

## How has this been tested?

As was in the PR that introduced this bug and deleted the head blocks, this is a performance change with no other user-visible behaviour and is untested besides a couple of sanity-checking in-development printlns, and the absence of errors being thrown whilst this code is being executed.

### CODE REVIEW

File: internal/db/collection_truncate.go [hunk 1]
```diff
@@ -391,3 +391,55 @@ func (c *collection) hardDeleteCollectionBlocks(
 
 	return nil
 }
+
+// deleteBlocks deletes the block of the given cid and all the blocks it links to, if
+// a block with this cid is found.
+//
+// If the block is not found, it will not error.
+func deleteBlocks(ctx context.Context, head cid.Cid) error {
```
Comment (fredcarle) [inline internal/db/collection_truncate.go:399]: todo: There is a way to make this more efficient. You should only fetch the heads and directly delete the links. This way you're only walking the composites and saving a lot of work. For branchable you would have to walk both heads (other collection blocks) and links (document composites) though. But still overall much less work.

**Review by fredcarle — CHANGES_REQUESTED** [review]
I'd like to reduce the amount of work done here before approval.

File: internal/db/collection_truncate.go [hunk 2]
```diff
@@ -391,3 +391,55 @@ func (c *collection) hardDeleteCollectionBlocks(
...
+
+		currentBlock, err := blockstore.Get(ctx, currentBlockCid)
+		if errors.Is(err, ipld.ErrNotFound{}) {
+			// We are looping through the links in a simple way that may result in us
+			// attempting to delete blocks we have already deleted, this can include
+			// blocks deleted by walking the dag pointed-to from another headstore key
+			// (another call to `deleteBlocks`).
+			//
+			// If we encounter such a block, we can skip over the error and continue.
+			continue
```
Comment (shahzadlone) [inline internal/db/collection_truncate.go:423]: question/thought: Is that the only case we have to worry about? Just think out loud if there is an edge case for skipping on a ErrNotFound

File: internal/db/collection_truncate.go (hunk 1 above)
Comment (AndrewSisley) [reply internal/db/collection_truncate.go:399]: That would only delete the top level blocks no?

If a doc is updated the previous head is removed from the headstore.  We need to walk the DAG in order to delete all the blocks.

File: internal/db/collection_truncate.go (hunk 2 above)
Comment (AndrewSisley) [reply internal/db/collection_truncate.go:423]: I don't think so, and if there is, I don't think we really lose anything by not knowing about it - we try to delete a block that wasn't there and continue.

File: internal/db/collection_truncate.go (hunk 1 above)
Comment (fredcarle) [reply internal/db/collection_truncate.go:399]: The blocks have mainly 2 link fields
```go
type Block struct {
  Heads []cidlink.Link
  Links []DAGLink
  ...
}
```
Walking the DAG (from a document composite) through the `Heads` is enough to delete all the document blocks. However, I realize we still need to load the link blocks to make sure we delete the `Encryption` and `Signature` blocks if they are different than that of the composite. But we don't need to load the `Encryption` and `Signature` blocks and neither de we need to walk from the link blocks of the fields. 

image

image

Comment (AndrewSisley) [reply internal/db/collection_truncate.go:399]: Clarified on discord, resuming conversation here.

I am a bit uncomfortable about adding too much logic here as it risks us missing blocks in the future if the linking ever changes.  This is particularly risky with our current lack of tests here (we don't test that specific blocks have been removed).

I'm also slightly hesitant because we don't have any performance tests for this, so whilst skipping over some links will almost certainly be faster, we haven't actually measured the relative impact of that on the `Truncate` call.

I think I'm going to avoid whitelisting block kinds and their links, and instead blacklist field level blocks, this should hopefully reduce the risk of not deleting stuff in the future (there will still remain some risk to field links though, I'll document).

- [x] Don't delete field head links

Comment (fredcarle) [reply internal/db/collection_truncate.go:399]: > and instead blacklist field level blocks

I'm ok with that 👍

Comment (fredcarle) [reply internal/db/collection_truncate.go:399]: Just because you didn't mention it in you last comment and I want to make sure we don't forget them, I'm gonna add a todo.

todo: Make sure you delete the Encryption and Signature blocks for both composites and fields.

Comment (AndrewSisley) [reply internal/db/collection_truncate.go:399]: Cheers, I thought they were in `Links`

- [x] Delete enc and sig blocks

File: internal/db/collection_truncate.go [hunk 3]
```diff
@@ -379,7 +379,7 @@ func (c *collection) hardDeleteCollectionBlocks(
 			return err
 		}
 
-		err = blockstore.DeleteBlock(ctx, key.Cid)
+		err = deleteBlocks(ctx, key.Cid)
```
Comment (shahzadlone) [inline internal/db/collection_truncate.go:382]: question: This line is never hit by tests?

File: internal/db/collection_truncate.go [hunk 4]
```diff
@@ -391,3 +391,75 @@ func (c *collection) hardDeleteCollectionBlocks(
...
+		}
+
+		switch {
+		case decodedBlock.Delta.IsField():
+			// At the time of writing, field blocks do not have any heads that will not already be linked
+			// to by other DAGs being deleted, so we have decided that the compute that we will save by not
+			// trying to `Get` them is worth the risk of potentially missing blocks in the future should
+			// this change.
+			for _, link := range decodedBlock.Links {
+				toDelete[link.Cid] = struct{}{}
```
Comment (shahzadlone) [inline internal/db/collection_truncate.go]: nitpick: Is this dead/dormant code right now?

File: internal/db/collection_truncate.go (hunk 3 above)
Comment (AndrewSisley) [reply internal/db/collection_truncate.go:382]: No, I think there is a test gap for branchable collections.  They don't really do anything special that would break, but we should have a sanity check at least.

- [x] Close branchable test gap

File: internal/db/collection_truncate.go (hunk 4 above)
Comment (AndrewSisley) [reply internal/db/collection_truncate.go]: No, why do you ask?

**Comment by AndrewSisley** [comment]
@coderabbitai configuration

File: internal/db/collection_truncate.go (hunk 4 above)
Comment (fredcarle) [reply internal/db/collection_truncate.go]: This is indeed dead code as `Field` blocks never have links to other blocks within the `Links` field

File: internal/db/collection_truncate.go [hunk 5]
```diff
@@ -391,3 +391,75 @@ func (c *collection) hardDeleteCollectionBlocks(
...
+			}
+
+		default:
+			for _, link := range decodedBlock.AllLinks() {
+				toDelete[link.Cid] = struct{}{}
+			}
+		}
+
+		if decodedBlock.Encryption != nil {
+			toDelete[decodedBlock.Encryption.Cid] = struct{}{}
```
Comment (fredcarle) [inline internal/db/collection_truncate.go:453]: todo: Please add code test coverage for truncating encrypted block.

File: internal/db/collection_truncate.go [hunk 6]
```diff
@@ -391,3 +391,75 @@ func (c *collection) hardDeleteCollectionBlocks(
...
+		}
+
+		if decodedBlock.Signature != nil {
+			toDelete[decodedBlock.Signature.Cid] = struct{}{}
```
Comment (fredcarle) [inline internal/db/collection_truncate.go:457]: todo: Please add test coverage for truncating signed blocks.

**Review by fredcarle — APPROVED** [review]
Approving with 2 todos to resolve before merge. It would be good to take care of the dead code as well.

File: internal/db/collection_truncate.go (hunk 4 above)
Comment (AndrewSisley) [reply internal/db/collection_truncate.go]: Ugh, I fell back into my prior/outdated thinking here.  I'll remove this, it should be a no-op.

- [x] Rm deadcode

File: internal/db/collection_truncate.go (hunk 5 above)
Comment (AndrewSisley) [reply internal/db/collection_truncate.go:453]: I think this should be covered automatically.  I've opened https://github.com/sourcenetwork/defradb/issues/4452

File: internal/db/collection_truncate.go (hunk 6 above)
Comment (AndrewSisley) [reply internal/db/collection_truncate.go:457]: I think this should be covered automatically. I've opened https://github.com/sourcenetwork/defradb/issues/4453
