### PR TITLE
fix(i): Make peer connections deterministic

### LINKED ISSUE #1902: Depricate: go-libp2p is removing database-backed peerstore (pstoreds)
Note:
```
// Deprecated: The database-backed peerstore will be removed from go-libp2p in the future.
// Use the memory peerstore (pstoremem) instead.
// For more details see https://github.com/libp2p/go-libp2p/issues/2329
// and https://github.com/libp2p/go-libp2p/issues/2355.
```

In net/node.go we use `"github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoreds"` that creates our peerstore from the underlying defra rootstore with the appropriate prefix. However now if we are forced to use pstoremem

### LINKED ISSUE #2847: Node p2p connections in tests are not deterministic
Node p2p connections in tests are done through a bootstrapping process that does not guarantee all nodes are properly connected.

Failed test due to node connection failure:

```
=== Failed
=== FAIL: tests/integration/net/simple/replicator TestP2POneToOneReplicatorWithRestart (30.83s)
Jul 18 16:31:35.868 INF tests.integration  database=badger-file-system client=http mutationType=collection-named databaseDir="" badgerEncryption=false skipNetworkTests=false changeDetector.Enabled=false changeDetector.SetupOnly=false changeDetector.SourceBranch=develop changeDetector.TargetBranch="" changeDetector.Repository=https://github.com/sourcenetwork/defradb.git
Jul 18 16:31:35.945 INF net Created LibP2P host PeerId=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z Address=[/ip4/127.0.0.1/tcp/0]
Jul 18 16:31:35.950 INF tests.integration Starting P2P node "P2P address"="{12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z: [/ip4/127.0.0.1/tcp/35891]}"
Jul 18 16:31:35.957 INF net Starting internal broadcaster for pubsub network
Jul 18 16:31:35.957 INF net Starting P2P node "P2P addresses"=[/ip4/127.0.0.1/tcp/35891]
Jul 18 16:31:36.034 INF net Created LibP2P host PeerId=12D3KooWDkH3etqDkmq45DUrfB6cX4rw793sxJKR5pcs3r6Hiomn Address=[/ip4/127.0.0.1/tcp/0]
Jul 18 16:31:36.036 INF tests.integration Starting P2P node "P2P address"="{12D3KooWDkH3etqDkmq45DUrfB6cX4rw793sxJKR5pcs3r6Hiomn: [/ip4/127.0.0.1/tcp/41399]}"
Jul 18 16:31:36.042 INF net Starting internal broadcaster for pubsub network
Jul 18 16:31:36.042 INF net Starting P2P node "P2P addresses"=[/ip4/127.0.0.1/tcp/41399]
Jul 18 16:31:36.110 INF net Removing all pubsub topics PeerID=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z
Jul 18 16:31:36.119 INF db Closing DefraDB process...
2024-07-18T16:31:36.161Z	ERROR	peerstore/ds	pstoreds/keybook.go:81	error while updating pubkey in datastore for peer 12D3KooWDkH3etqDkmq45DUrfB6cX4rw793sxJKR5pcs3r6Hiomn: datastore closed

Jul 18 16:31:36.161 INF db Successfully closed running process
Jul 18 16:31:36.161 INF net Removing all pubsub topics PeerID=12D3KooWDkH3etqDkmq45DUrfB6cX4rw793sxJKR5pcs3r6Hiomn
Jul 18 16:31:36.167 INF db Closing DefraDB process...
Jul 18 16:31:36.209 INF db Successfully closed running process
Jul 18 16:31:36.303 INF net Created LibP2P host PeerId=12D3KooWDkH3etqDkmq45DUrfB6cX4rw793sxJKR5pcs3r6Hiomn Address=[/ip4/127.0.0.1/tcp/41399]
Jul 18 16:31:36.314 INF net Failure while reconnecting to a known peer peer=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z
Jul 18 16:31:36.314 INF net Starting internal broadcaster for pubsub network
Jul 18 16:31:36.316 INF net Starting P2P node "P2P addresses"=[/ip4/127.0.0.1/tcp/41399]
Jul 18 16:31:36.413 INF net Created LibP2P host PeerId=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z Address=[/ip4/127.0.0.1/tcp/35891]
Jul 18 16:31:36.458 INF net Starting internal broadcaster for pubsub network
Jul 18 16:31:36.458 INF net Starting P2P node "P2P addresses"=[/ip4/127.0.0.1/tcp/35891]
Jul 18 16:31:36.492 INF net Adding pubsub topic PeerID=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z Topic=bae-a77c5e93-5a74-5722-bbfc-9baf549a922f
Jul 18 16:31:36.492 INF net Publish log PeerID=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z Topic=bafkreial5obfyogjwuvy6zhrooi5klmam7p5jy6e2g5fwmdfiwuetxfxga
Jul 18 16:31:36.492 INF net Adding pubsub topic PeerID=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z Topic=bafkreial5obfyogjwuvy6zhrooi5klmam7p5jy6e2g5fwmdfiwuetxfxga
Jul 18 16:31:36.493 INF net Publish log PeerID=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z Topic=bafkreial5obfyogjwuvy6zhrooi5klmam7p5jy6e2g5fwmdfiwuetxfxga
Jul 18 16:31:36.498 INF net Adding pubsub topic PeerID=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z Topic=bae-a77c5e93-5a74-5722-bbfc-9baf549a922f
    events.go:233: 
        	Error Trace:	/home/runner/work/defradb/defradb/tests/integration/events.go:233
        	            				/home/runner/work/defradb/defradb/tests/integration/utils2.go:345
        	            				/home/runner/work/defradb/defradb/tests/integration/utils2.go:226
        	            				/home/runner/work/defradb/defradb/tests/integration/utils2.go:180
        	            				/home/runner/work/defradb/defradb/tests/integration/net/simple/replicator/with_create_restart_test.go:63
        	Error:      	timeout waiting for merge complete event
        	Test:       	TestP2POneToOneReplicatorWithRestart
Jul 18 16:32:06.597 INF net Removing all pubsub topics PeerID=12D3KooWLbpVvaeL9vYiqgm47dETtmJthuSXKJX6QhR8yoFL5Z5Z
Jul 18 16:32:06.605 INF db Closing DefraDB process...
Jul 18 16:32:06.667 INF db Successfully closed running process
Jul 18 16:32:06.667 INF net Removing all pubsub topics PeerID=12D3KooWDkH3etqDkmq45DUrfB6cX4rw793sxJKR5pcs3r6Hiomn
Jul 18 16:32:06.673 INF db Closing DefraDB process...
Jul 18 16:32:06.700 INF db Successfully closed running process
```

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #2847
Resolves #1902

## Description

This PR fixes an issue where peer connections were not deterministic within the test framework.

There's also a few other areas that were cleaned up:
- Bootstrap has been replaced with https://github.com/ipfs/boxo/blob/main/bootstrap/bootstrap.go
- Host setup logic was moved to `net/host.go`
- Persistent peer store was replaced with in memory only version
- Context reuse within the `net` package has been refactored
- Removed unused peer event

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

`make test`

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: net/server.go [hunk 1]
```diff
@@ -196,7 +195,7 @@ func (s *server) addPubSubTopic(topic string, subscribe bool) error {
 		}
 	}
 
-	t, err := rpc.NewTopic(s.peer.ctx, s.peer.ps, s.peer.host.ID(), topic, subscribe)
+	t, err := rpc.NewTopic(context.Background(), s.peer.ps, s.peer.host.ID(), topic, subscribe)
```
Comment (AndrewSisley) [inline net/server.go:198]: question: Are you sure this is an improvement?  It does look like a suspicious change to me, I would have expected us to want to use the same context for all topics+peer

Comment (nasdf) [reply net/server.go:198]: I've always followed this rule from the Go docs:

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.

Since there is no context to pass around in these functions they should be run with a background context..

File: net/config.go [hunk 2]
```diff
@@ -24,6 +24,7 @@ type Options struct {
 	EnableRelay       bool
 	GRPCServerOptions []grpc.ServerOption
 	GRPCDialOptions   []grpc.DialOption
+	BootstrapPeers    []string
```
Comment (AndrewSisley) [inline net/config.go:27]: question: Sorry if I've misread, but I can't spot where this is actually read - is it dead code?

File: net/server.go (hunk 1 above)
Comment (AndrewSisley) [reply net/server.go:198]: In that case I really think we should ignore that suggestion here and use the context provided to the system.    Please consider reverting this change a todo.

Comment (nasdf) [reply net/server.go:198]: I don't think the context provided to the constructor makes sense either since it would outlive the function call. Would you be okay with creating a new background context that is then used for all publish / topic calls?

Comment (AndrewSisley) [reply net/server.go:198]: > I don't think the context provided to the constructor makes sense either since it would outlive the function call.

Why does that not make sense?  Any context provided to a function outlives the function call

File: net/config.go (hunk 2 above)
Comment (nasdf) [reply net/config.go:27]: It's used here: https://github.com/sourcenetwork/defradb/blob/f8032b3d912597833f747665774c927e38343408/net/peer.go#L84

Comment (AndrewSisley) [reply net/config.go:27]: cheers!

File: net/server.go (hunk 1 above)
Comment (nasdf) [reply net/server.go:198]: This example shows how the shared context is confusing for callers:

```go
func setupNetworkWithTimeout(ctx context.Context) (*net.Peer, error) {
  // cancel setup if it takes too long
  ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
  defer cancel()

  // context is shared in peer struct with all sub functions
  n, err := net.NewPeer(ctx, ...)
  if err != nil {
    return nil, err
  }

  return n, nil
}

func main() {
  ctx := context.Background()

  n, err := setupNetworkWithTimeout(ctx)
  if err != nil {
    panic(err)
  }
  
  // the shared context was cancelled so the peer cannot run
  n.Start()
}
```

Comment (AndrewSisley) [reply net/server.go:198]: I mean if I cancelled a context that I used to construct something, I'd want it to close all the things owned by that.  I like that about the current setup.

It also provides all the other stuff that context holds to the children of `Peer`, if nothing else it is handy for logging.

Comment (AndrewSisley) [reply net/server.go:198]: suggestion: If you are not happy about this, I suggest we discuss it in the standup.

Comment (nasdf) [reply net/server.go:198]: > I mean if I cancelled a context that I used to construct something, I'd want it to close all the things owned by that. I like that about the current setup.

If we didn't have explicit `Start` and `Stop` functions I would agree with this.

Comment (AndrewSisley) [reply net/server.go:198]: > If we didn't have explicit Start and Stop functions I would agree with this.

I could rant for quite a while about how much I hate `Start` functions on objects with constructors...  I don't see a `Stop` function though, although I could rant about that/those paired with `Close` functions too :sweat_smile:.

Comment (shahzadlone) [reply net/server.go:198]: Interesting discussion, I feel like we have discussed something similar before. While I do personally have a slight preference for Andy's approach. Since I read the Go guidelines regarding not storing contexts in structs I do tend to stick to those guidelines and am happy with this change. However I do wonder if it's possible to just pass the ctx to `addPubSubTopic` through a function parameter (most of the callers do have a `ctx`).

File: net/peer.go [hunk 3]
```diff
@@ -97,75 +81,20 @@ func NewPeer(
...
-		key, err := crypto.GenerateEd25519()
+	peers := make([]peer.AddrInfo, len(options.BootstrapPeers))
+	for i, p := range options.BootstrapPeers {
+		addr, err := peer.AddrInfoFromString(p)
 		if err != nil {
 			return nil, err
 		}
-		options.PrivateKey = key
+		peers[i] = *addr
 	}
```
Comment (shahzadlone) [inline net/peer.go:91]: question: This for-loop is never entered in any test, is it possible to test this easily?

File: net/config.go [hunk 4]
```diff
@@ -64,3 +65,10 @@ func WithListenAddresses(addresses ...string) NodeOpt {
 		opt.ListenAddresses = addresses
 	}
 }
+
+// WithBootstrapPeers sets the bootstrap peer addresses to attempt to connect to.
+func WithBootstrapPeers(peers ...string) NodeOpt {
+	return func(opt *Options) {
+		opt.BootstrapPeers = peers
+	}
+}
```
Comment (shahzadlone) [inline net/config.go:74]: suggestion: All other config functions are tested in this file except this one. Please add a test if not too much hassle.

File: net/peer.go (hunk 3 above)
Comment (nasdf) [reply net/peer.go:91]: added a test for the non error case

File: net/config.go (hunk 4 above)
Comment (nasdf) [reply net/config.go:74]: added a test here

File: net/server.go (hunk 1 above)
Comment (nasdf) [reply net/server.go:198]: > However I do wonder if it's possible to just pass the ctx to addPubSubTopic through a function parameter (most of the callers do have a ctx).

I'm open to this as long as that context is not the same as the constructor context.

**Review by shahzadlone — APPROVED** [review]
Thanks for adding the requested tests, before merge please don't forget to handle the `tidy` check (just need to do `make tidy`) it's not required yet but will be nice to maintain a tidy state. Also do resolve the `ctx` discussion before merging.
