### PR TITLE
fix: Encrypted index patch tests and validation

### LINKED ISSUE #4508: EncryptedIndexes patch collection tests do not test what they try to
They all seem to forget to specify which collection they are trying to patch, for example:
```
func TestPatchCollection_RemoveEncryptedIndex_ShouldError(t *testing.T) {
	test := testUtils.TestCase{
		Actions: []any{
			&action.AddSchema{
				Schema: `
					type Users {
						name: String
						email: String @encryptedIndex
					}
				`,
			},
			&action.PatchCollection{
				Patch: `
					[
						{
							"op": "remove",
							"path": "/EncryptedIndexes"
						}
					]
				`,
				ExpectedError: "unable to remove nonexistent key",
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
}
```

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4508

## Description

The patch collection tests for encrypted indexes had wrong JSON patch paths, they used "/EncryptedIndexes" instead of "/Users/EncryptedIndexes", so they never actually targeted the collection. They passed but only because malformed paths produce generic JSON errors, not because the validation was working.                                                                                                                                             

Fixed the paths, corrected the `Type` field from a number to the proper string value, and updated expected errors to match the real validation message. This also uncovered a panic in `validateEncryptedIndexesNotModified` where the element-wise comparison loop ran even when slice lengths differed, causing an index-out-of-range crash on remove operations. Added the missing else branch to match the pattern used by the adjacent index validator.              
                                                                                                                                                                                                                                     
## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Integration tests

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: tests/action/utils_events.go [hunk 1]
```diff
@@ -133,7 +133,9 @@ func updateNetworkState(s *state.State, nodeID int, evt event.Update, ident immu
 	// update the expected document heads of replicator targets
 	for id := range node.P2P.Replicators {
 		// replicator target nodes push updates to source nodes
-		s.Nodes[id].P2P.ExpectedDAGHeads[getUpdateEventKey(evt)] = evt.Cid
+		s.Nodes[id].P2P.ExpectedDAGHeads[getUpdateEventKey(evt)] = append(
```
Comment (AndrewSisley) [inline tests/action/utils_events.go:138]: question: This change is not explained by the PR description - why are you doing this? Why is it necessary now?

Comment (AndrewSisley) [reply tests/action/utils_events.go:138]: Also, there appear to be a larger than normal amount of CI jobs timing out - please be certain that you have not made the tests more flaky with these changes.

**Review by AndrewSisley — APPROVED** [review]
LGTM!
