### PR TITLE
fix: Handle _version property in time travel queries

### LINKED ISSUE #4021: Server 500 from cid+_version query
When I issue this query:

```graphql
query {
  User(cid:"-whatever-") {
    _version {
      cid height signature { __typename }
    }
  }
}
```

I got back a server 500 error (with no error text).

But when I removed the `_version` stuff (and selected other fields), it worked fine.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #4021

## Description

Handle the `_version` property in time travel queries.

### CODE REVIEW

File: internal/planner/select.go [hunk 1]
```diff
@@ -446,18 +446,11 @@ func (n *selectNode) initFields(selectReq *mapper.Select) ([]aggregateNode, []*s
...
-				// or a TimeTravel query.
+
 				if selectReq.Cid.HasValue() {
-					// for a TimeTravel query, we don't need the Latest
-					// commit. Instead, _version references the CID
-					// of that Target version we are querying.
-					// So instead of a LatestCommit subquery, we need
-					// a commits query with max depth starting from the
-					// target CID version
-					commitSlct.DocID = immutable.Some(selectReq.DocIDs.Value()[0]) // @todo check length
```
Comment (AndrewSisley) [inline internal/planner/select.go:459]: note: The docID filtering of the parent is handled by the parent select/filter node(s).

**Comment by getify** [comment]
I'm confused as to how this bug fix only was removal of code comments?

**Comment by shahzadlone** [comment]
> I'm confused as to how this bug fix only was removal of code comments?

Line 459 is not a comment haha

**Review by shahzadlone — APPROVED** [review]
LGTM

**Comment by getify** [comment]
ahhh I did miss that. sorry. 

might be helpful to document here why that removal of code fixes the bug, as that's not as common as needing to add code to fix bugs.

if I missed it, perhaps others might also miss it without more clear roadsigns.
