### PR TITLE
fix: Compound filter operators with relations

### LINKED ISSUE #1808: Compound filter condition that includes a relation panics
**Describe the problem**
When running a query with a compound filter like `_and` that includes a relation (i.e. filtering on a related type) it panics with this call stack:
```
--- FAIL: TestQueryFromSingleSideWithEqFilterOnRelatedType (0.01s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 9 [running]:
testing.tRunner.func1.2({0x105e033a0, 0x14000f422e8})
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1529 +0x384
panic({0x105e033a0, 0x14000f422e8})
	/Users/islam/sdk/go1.20.7/src/runtime/panic.go:884 +0x204
github.com/sourcenetwork/defradb/core.(*DocumentMapping).FirstIndexOfName(...)
	/Users/islam/dev/sourcenetwork/defradb/core/doc.go:194
github.com/sourcenetwork/defradb/planner/mapper.toFilterMap({0x140001984d0?, 0x140001502a0?}, {0x105c8a660?, 0x140001500f0?}, 0x14000055200)
	/Users/islam/dev/sourcenetwork/defradb/planner/mapper/mapper.go:1156 +0x390
github.com/sourcenetwork/defradb/planner/mapper.toFilterMap({0x10565cf82, 0x3}, {0x105bdc920?, 0x1400014c1f8?}, 0x14000055200)
	/Users/islam/dev/sourcenetwork/defradb/planner/mapper/mapper.go:1131 +0x5ec
github.com/sourcenetwork/defradb/planner/mapper.ToFilter({0x140008af3d6?}, 0x6?)
	/Users/islam/dev/sourcenetwork/defradb/planner/mapper/mapper.go:1098 +0xcc
github.com/sourcenetwork/defradb/planner/mapper.toTargetable(0x0, 0x1400014b500, 0x14000055200)
	/Users/islam/dev/sourcenetwork/defradb/planner/mapper/mapper.go:1073 +0x64
github.com/sourcenetwork/defradb/planner/mapper.toSelect(0x3?, 0x3?, 0x1400014b500, {0x0?, 0x0?})
	/Users/islam/dev/sourcenetwork/defradb/planner/mapper/mapper.go:128 +0x310
github.com/sourcenetwork/defradb/planner/mapper.ToSelect({0x105efc6b0?, 0x14000198018?}, {0x105f0d5c0?, 0x14000b071f0?}, 0x14000150000?)
	/Users/islam/dev/sourcenetwork/defradb/planner/mapper/mapper.go:39 +0x68
github.com/sourcenetwork/defradb/planner.(*Planner).newPlan(0x140001501b0, {0x105cd48e0?, 0x1400014b500?})
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:115 +0x264
github.com/sourcenetwork/defradb/planner.(*Planner).newPlan(0x140001501b0, {0x105bb2380?, 0x14000150000?})
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:112 +0x19c
github.com/sourcenetwork/defradb/planner.(*Planner).newPlan(0x140001501b0, {0x105bb2480?, 0x1400012bcc0?})
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:101 +0x134
github.com/sourcenetwork/defradb/planner.(*Planner).makePlan(0x18?, {0x105bb2480?, 0x1400012bcc0?})
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:167 +0x28
github.com/sourcenetwork/defradb/planner.(*Planner).RunRequest(0x140005341f8?, {0x105efc6b0, 0x14000198018}, 0x1400012bcc0)
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:473 +0x50
github.com/sourcenetwork/defradb/db.(*db).execRequest(0x14000b1d130, {0x105efc6b0?, 0x14000198018}, {0x1058373c9, 0xb7}, {0x105f0d5c0?, 0x14000b071f0})
	/Users/islam/dev/sourcenetwork/defradb/db/request.go:53 +0x3c8
github.com/sourcenetwork/defradb/db.(*implicitTxnDB).ExecRequest(0x14000538038, {0x105efc6b0, 0x14000198018}, {0x1058373c9, 0xb7})
	/Users/islam/dev/sourcenetwork/defradb/db/txn_db.go:45 +0x150
github.com/sourcenetwork/defradb/tests/integration.executeRequest(0x140004ae160, {{0x0, 0x0}, {0x0, 0x0}, {0x1058373c9, 0xb7}, {0x140001a1018, 0x1, 0x1}, ...})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:1293 +0xe8
github.com/sourcenetwork/defradb/tests/integration.executeTestCase({0x105efc6b0?, 0x14000198018}, 0x140007829c0, {0x140004b6440, 0x2, 0x2}, {{0x10582a409, 0x49}, {0x140000ae300, 0xb, ...}}, ...)
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:383 +0xab8
github.com/sourcenetwork/defradb/tests/integration.ExecuteTestCase(0x105e14460?, {{0x10582a409, 0x49}, {0x140000ae300, 0xb, 0x10}})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:288 +0x340
github.com/sourcenetwork/defradb/tests/integration.ExecuteRequestTestCase(0x104869fdc?, {0x105835b65?, 0x104869eac?}, {0x14000266380?, 0x104749ae4?, 0x105c634e0?}, {{0x10582a409, 0x49}, {0x1058373c9, 0xb7}, ...})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils.go:85 +0x328
github.com/sourcenetwork/defradb/tests/integration/query/one_to_many.executeTestCase(...)
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/query/one_to_many/utils.go:37
github.com/sourcenetwork/defradb/tests/integration/query/one_to_many.TestQueryFromSingleSideWithEqFilterOnRelatedType(0x14000509f98?)
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/query/one_to_many/with_filter_related_id_test.go:334 +0x324
testing.tRunner(0x140007829c0, 0x105ee20c0)
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1576 +0x10c
created by testing.(*T).Run
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1629 +0x368
FAIL	github.com/sourcenetwork/defradb/tests/integration/query/one_to_many	0.665s
FAIL
```

**To Reproduce**
* find `TestQueryFromSingleSideWithEqFilterOnRelatedType` test
* replace this query
```graphql
query {
	Author(filter: {published: {_key: {_eq: "bae-b9b83269-1f28-5c3b-ae75-3fb4c00d559d"}}}) {
		name
	}
}
```
* with this logically equivalent one:
```graphql
query {
	Author(filter: {
		_and: [ 
			{ name: { _ne: "Voltaire" }},
			{ published: {_key: {_eq: "bae-b9b83269-1f28-5c3b-ae75-3fb4c00d559d"}}}
		]
	}) {
		name
	}
}
```
* run the test and observe the crash

**Expected behavior**
It should not panic and return the same result as the test with the original query.

**Platform**
mac

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #1808 

## Description

Any time a filter with `_and` or `_or` operator that includes relations is applied it will fail.
There were 2 problems:
- filter is not recursively analysed during mapping phase which would result in some relational fields not being mapped and later panic upon attempt to access them.
- the filter is not properly split between the scan and select nodes. It would just analyse and split top-level fields.
These problems are fixed.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Integration tests

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: planner/type_join.go [hunk 1]
```diff
@@ -479,24 +424,47 @@ type typeJoinMany struct {
...
+	subType.ShowDeleted = parent.selectReq.ShowDeleted
+
+	scan, ok := source.(*scanNode)
+	if !ok || scan.filter == nil {
+		return
+	}
+
+	if filter.IsComplex(scan.filter) {
+		if parent.filter == nil {
+			parent.filter = new(mapper.Filter)
```
Comment (AndrewSisley) [inline planner/type_join.go:441]: nitpick: I do have a preference here for `parent.filter = mapper.NewFilter()` - the constructor makes it much easier to find places that instantiate new instances, and with the current code parent.filter can easily panic as `filter.Conditions` is nil.

File: planner/mapper/mapper.go [hunk 2]
```diff
@@ -797,50 +803,66 @@ func resolveInnerFilterDependencies(
...
 	mapping *core.DocumentMapping,
 	existingFields []Requestable,
+	resolvedFields []Requestable,
 ) ([]Requestable, error) {
 	newFields := []Requestable{}
 
-sourceLoop:
 	for key := range source {
-		if strings.HasPrefix(key, "_") && key != request.KeyFieldName {
+		if key == opAnd || key == opOr { // handle _not
```
Comment (AndrewSisley) [inline planner/mapper/mapper.go:811]: todo: I don't think the `// handle _not` comment belongs in develop branch, this is basically a todo, and if presered it should be linked to a ticket.

File: planner/mapper/mapper.go [hunk 3]
```diff
@@ -797,50 +803,66 @@ func resolveInnerFilterDependencies(
...
+			andFilter := source[key].([]any)
```
Comment (AndrewSisley) [inline planner/mapper/mapper.go:812]: nitpick: `andFilter` should be `andOrFilter` (or something else) no?  It is not just an and-filter?

File: tests/integration/query/one_to_many/with_filter_test.go [hunk 4]
```diff
@@ -17,274 +17,468 @@ import (
 )
 
 func TestQueryOneToManyWithNumericGreaterThanFilterOnParent(t *testing.T) {
-	test := testUtils.RequestTestCase{
+	test := testUtils.TestCase{
```
Comment (AndrewSisley) [inline tests/integration/query/one_to_many/with_filter_test.go:20]: praise: Thank you for taking the time to convert these to the newer framework :)

File: tests/integration/query/one_to_many/with_filter_test.go [hunk 5]
```diff
@@ -17,274 +17,468 @@ import (
...
+			testUtils.CreateDoc{
+				CollectionID: 1,
+				// bae-b769708d-f552-5c3d-a402-ccfd7ac7fb04
+				Doc: `{
+					"name": "Cornelia Funke",
+					"age": 62,
+					"verified": false
+				}`,
+			},
+			testUtils.Request{
```
Comment (AndrewSisley) [inline tests/integration/query/one_to_many/with_filter_test.go:401]: suggestion: I think these tests can be improved slightly:

At the moment you have an or of three, but you are only returning a single record each time - this means that I could 'simplify' the test, by removing two of those 3 inner conditions, leaving an or of one, and then further simplify the test to remove the or.  Neither the setup, or the results would change - this offers little protection against changing the filter, the only real reason stopping developers from simplifying the test is their ability to read and understand what the title/description says the test is trying to test.

If you change it so that changing any one of the setup, act (filter), or assert (results) steps will cause the test to fail, it should be even more robust.

The same goes for the other new integration tests, they seem to all follow this pattern.

similar suggestion: I'd also drop the `verified` field from these tests too, other than the dockeys in the setup, it has no impact on the test result and is just noise.

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
I've gone over everything outside the filter package, which I'll try and do later/tomorrow depending on how much time/energy I have left.

I like how you have done it from what I have seen so far, my requests are all fairly localised I think.  If I haven't finished my review by Friday afternoon and someone else has approved (and you have responded to all my comments so far) please feel very free to dismiss my request for changes and merge without my approval.

File: planner/mapper/mapper.go (hunk 2 above)
Comment (islamaliev) [reply planner/mapper/mapper.go:811]: it's something I'm working on now. Will push a bit later to this PR

File: planner/filter/copy_field.go [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+package filter
+
+import (
+	"github.com/sourcenetwork/defradb/connor"
+	"github.com/sourcenetwork/defradb/planner/mapper"
+)
+
+// CopyField copies the given field from the provided filter.
+// The result filter preserves the structure of the original filter.
+func CopyField(filter *mapper.Filter, field mapper.Field) *mapper.Filter {
```
Comment (AndrewSisley) [inline planner/filter/copy_field.go:19]: suggestion: This looks like it could be made private?

File: planner/filter/external_conditions.go [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+package filter
+
+import (
+	"github.com/sourcenetwork/defradb/connor"
+	"github.com/sourcenetwork/defradb/core"
+	"github.com/sourcenetwork/defradb/planner/mapper"
+)
+
+// BuildExternalConditions builds a map of external conditions from the provided conditions.
+func BuildExternalConditions(conditions map[connor.FilterKey]any, mapping *core.DocumentMapping) map[string]any {
```
Comment (AndrewSisley) [inline planner/filter/external_conditions.go:19]: suggestion: This looks like it is dead and could be removed?

File: planner/filter/merge.go [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+		dest = make(map[connor.FilterKey]any)
+	}
+
+	result := map[connor.FilterKey]any{
+		&mapper.Operator{Operation: request.FilterOpAnd}: []any{
+			dest, src,
+		},
+	}
+
+	return Normalize(result)
```
Comment (AndrewSisley) [inline planner/filter/merge.go:31]: suggestion: It is not obvious to me as to why we want normalise here, I'd suggest adding a comment above this line explaining why, otherwise it could be seen as an optimisation (I'm assuming it is not just that).

File: planner/filter/normalize.go [hunk 9]
```diff
@@ -0,0 +1,149 @@
...
+
+// Normalize normalizes the provided filter conditions.
+// The following cases are subject of normalization:
+// - _and or _or with one element is removed flattened
+// - double _not is removed
+// - any number of consecutive _ands with any number of elements is flattened
+// As the result object is a map with unique keys (a.k.a. properties),
+// while performing flattening of compound operators if the same property
+// is present in the result map, both conditions will be moved into an _and
+func Normalize(conditions map[connor.FilterKey]any) map[connor.FilterKey]any {
```
Comment (AndrewSisley) [inline planner/filter/normalize.go:26]: suggestion: This looks like it could be private?

**Review by AndrewSisley — APPROVED** [review]
Looks good to me, have gone through everything and am happy, assuming the (small/localised) comments I've left are responded to sensibly :)

File: planner/filter/external_conditions.go (hunk 7 above)
Comment (islamaliev) [reply planner/filter/external_conditions.go:19]: I've actually added this, because I need this for secondary indexes. But I can add it in secondary indexes branch. No problem

File: planner/filter/copy_field.go (hunk 6 above)
Comment (islamaliev) [reply planner/filter/copy_field.go:19]: This is actually a question: what makes a function a good candidate for being public? Is it just usage from another package? Some function are just nice utilities that can be used later.
