### PR TITLE
fix: Passive sync with node chain

### LINKED ISSUE #2744: Network document updates do not send subscription events
Document updates from the p2p network do not send subscription events. Should be easy to fix by changing merge event types.

### LINKED ISSUE #4010: Document not syncing with chain of nodes on pubsub
This fails as the document never reaches node 2
```golang
func TestP2PCreateWithP2PCollection2(t *testing.T) {
    test := testUtils.TestCase{
        Actions: []any{
            testUtils.RandomNetworkingConfig(),
            testUtils.RandomNetworkingConfig(),
            testUtils.RandomNetworkingConfig(),
            &action.AddSchema{
                Schema: `
                    type Users {
                        Name: String
                        Age: Int
                    }
                `,
            },
            testUtils.ConnectPeers{
                SourceNodeID: 1,
                TargetNodeID: 0,
            },
            testUtils.ConnectPeers{
                SourceNodeID: 2,
                TargetNodeID: 1,
            },
            testUtils.SubscribeToCollection{
                NodeID:        1,
                CollectionIDs: []int{0},
            },
            testUtils.SubscribeToCollection{
                NodeID:        2,
                CollectionIDs: []int{0},
            },
            testUtils.CreateDoc{
                NodeID: immutable.Some(0),
                Doc: `{
                    "Name": "John",
                    "Age": 21
                }`,
            },
            testUtils.WaitForSync{},
            testUtils.Request{
                Request: `query {
                    Users {
                        Age
                    }
                }`,
                Results: map[string]any{
                    "Users": []map[string]any{
                        {
                            "Age": int64(21),
                        },
                    },
                },
            },
        },
    }

    testUtils.ExecuteTestCase(t, test)
}
```

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #4010 
Resolves #2744  

## Description

This PR ensures that every node in a chain of connected nodes receives a document update if they subscribe to the appropriate topic. 

The issue was caused by the nodes receiving the update message trying to fetch the new blocks, but the nodes that they were connected to didn't yet have it themselves. We solve this by sending the update message again once a node completes a sync.

By fixing this, we also fixed the gql subscription missing new doc updates when those updates came from the p2p system.

Additionally, the blockstore now as the capability to track if a block has been merged or not. This helps to prevent unnecessarily walking the dag upon receiving an update and trying to sync.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

New integration tests

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/db/p2p/p2p.go [hunk 1]
```diff
@@ -368,12 +378,33 @@ func (p *P2P) processPushlogRequest(
...
+	}
+	if merged {
+		return nil
+	}
+
+	// Calls to syncDAG should not overlap for a given CID. If they do, they will use the same
+	// underlying pubsub topic and this brings along potential pitfalls. One of them being that
+	// if this initial sync call had a negative response for a given link, the subsequent calls will
+	// assume a negative response for that same link without retrying.
+	p.processQueue.add(headCID.String())
```
Comment (AndrewSisley) [inline internal/db/p2p/p2p.go]: suggestion: Does this need to call `String()`?  Can we not use the raw cid (either bytes or `KeyString()`)?

File: internal/db/p2p/p2p.go [hunk 2]
```diff
@@ -431,3 +476,44 @@ func (p *P2P) SendUpdate(evt event.Update) error {
 
 	return nil
 }
+
+// processQueue is synchronization source to ensure that concurrent
+// document merges do not cause transaction conflicts.
+type processQueue struct {
```
Comment (AndrewSisley) [inline internal/db/p2p/p2p.go:487]: praise: This is quite (b)locky, but a neat and code-efficient way of handling the problem - thanks :)

File: tests/integration/net/simple/peer/with_create_test.go [hunk 3]
```diff
@@ -195,3 +195,131 @@ func TestP2PCreateWithP2PCollection(t *testing.T) {
...
+			},
+			testUtils.ConnectPeers{
+				SourceNodeID: 2,
+				TargetNodeID: 1,
+			},
+			testUtils.ConnectPeers{
+				SourceNodeID: 3,
+				TargetNodeID: 2,
+			},
+			testUtils.ConnectPeers{
```
Comment (AndrewSisley) [inline tests/integration/net/simple/peer/with_create_test.go:230]: suggestion: It might be worth noting the importance of having 4 somewhere in this test. I almost always assume that 3 and 4 would have the same problems, and we might lose a node from this test (and any future derivatives) over time after forgetting the bug you found at 4.

**Review by AndrewSisley — APPROVED** [review]
LGTM, approving now but might want to review any blockstore/index rework that may or may not happen before merge.  Thanks for this Fred :)

File: internal/core/block/store.go [hunk 4]
```diff
@@ -226,13 +226,23 @@ func updateHeads(
 		}
 	}
 
+	err := txn.Blockstore().MarkAsMerged(ctx, blockLink.Cid)
+	if err != nil {
```
Comment (shahzadlone) [inline internal/core/block/store.go:232]: Nitpick: one liner comment here saying why its important to mark this as merged right here is important would be nice.

File: internal/db/config.go [hunk 5]
```diff
@@ -45,6 +47,7 @@ func defaultDBOptions() *dbOptions {
 			time.Minute * 16,
 			time.Minute * 32,
 		},
+		p2pBlockSyncTimeout: time.Second * 5,
```
Comment (shahzadlone) [inline internal/db/config.go:50]: Nitpick: would be nice to see all these time defaults defined at the top perhaps

**Review by shahzadlone — APPROVED** [review]
LGTM, just some nitpicks

**Comment by nasdf** [comment]
@fredcarle does this fix #2744 as well?

**Comment by fredcarle** [comment]
> @fredcarle does this fix #2744 as well?

It does :)

File: internal/db/config.go (hunk 5 above)
Comment (fredcarle) [reply internal/db/config.go:50]: I prefer not separating the default declaration from the defined values. Specially if they are not used anywhere else.

File: internal/db/p2p/p2p.go (hunk 1 above)
Comment (fredcarle) [reply internal/db/p2p/p2p.go]: Done

File: tests/integration/net/simple/peer/with_create_test.go (hunk 3 above)
Comment (fredcarle) [reply tests/integration/net/simple/peer/with_create_test.go:230]: Done

File: internal/core/block/store.go (hunk 4 above)
Comment (fredcarle) [reply internal/core/block/store.go:232]: Done

**Review by AndrewSisley — APPROVED** [review]
LGTM, thanks Fred!
