### PR TITLE
fix: Add validation to JSON fields

### LINKED ISSUE #2370: The content of doc field of type JSON is not validated
created a collection with a json field:
```shell
$ defradb client schema add 'type Product { title: String custom: JSON }'
```
Ran these 2 commands without any errors:
```shell
$ defradb client collection create --name Product '{"title": "XBox", "custom": "{ \"cpu\": \"Intel }" }'
$ defradb client collection create --name Product '{"title": "XBox", "custom": "blah" }'
```
Get document:
```shell
$ defradb client collection --name Product get bae-0f9266b2-eaac-5a6b-8c36-96882abb9637
{
  "_docID": "bae-0f9266b2-eaac-5a6b-8c36-96882abb9637",
  "custom": "blah",
  "title": "XBox"
}
```

Maybe it's intended this way, but I don't see a point of having JSON field that is not being validated. I could just use `String`.

Additional info:
```shell
$ defradb client schema describe Product
[
  {
    "Root": "bafkreiduhjgytitsc7fckm45wryms7gvywunl3x3gqoeesiuzxmjark3em",
    "VersionID": "bafkreiduhjgytitsc7fckm45wryms7gvywunl3x3gqoeesiuzxmjark3em",
    "Name": "User",
    "Fields": [
      {
        "Name": "_docID",
        "Kind": 1,
        "Schema": "",
        "RelationName": "",
        "Typ": 0,
        "IsPrimaryRelation": false
      },
      {
        "Name": "age",
        "Kind": 4,
        "Schema": "",
        "RelationName": "",
        "Typ": 1,
        "IsPrimaryRelation": false
      },
      {
        "Name": "name",
        "Kind": 11,
        "Schema": "",
        "RelationName": "",
        "Typ": 1,
        "IsPrimaryRelation": false
      }
    ]
  },
  {
    "Root": "bafkreif3bitgrnxwb5zybnbv5mixyd4wrhbvf7s6ku2ntknxfun436j6f4",
    "VersionID": "bafkreif3bitgrnxwb5zybnbv5mixyd4wrhbvf7s6ku2ntknxfun436j6f4",
    "Name": "Product",
    "Fields": [
      {
        "Name": "_docID",
        "Kind": 1,
        "Schema": "",
        "RelationName": "",
        "Typ": 0,
        "IsPrimaryRelation": false
      },
      {
        "Name": "custom",
        "Kind": 14,
        "Schema": "",
        "RelationName": "",
        "Typ": 1,
        "IsPrimaryRelation": false
      },
      {
        "Name": "title",
        "Kind": 11,
        "Schema": "",
        "RelationName": "",
        "Typ": 1,
        "IsPrimaryRelation": false
      }
    ]
  }
]
```

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2370 

## Description

This PR adds validation to JSON fields.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by nasdf — APPROVED** [review]
Thanks for fixing! The additional test coverage is nice.

File: tests/integration/mutation/create/field_kinds/field_kind_json_test.go [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+			},
+			testUtils.Request{
+				Request: `mutation {
+					create_Users(input: {name: "John", custom: "{\"tree\": \"maple, \"age\": 250}"}) {
+						_docID
+						name
+						custom
+					}
+				}`,
+				ExpectedError: `Argument "input" has invalid value {name: "John", custom: "{\"tree\": \"maple, \"age\": 250}"}.
```
Comment (shahzadlone) [inline tests/integration/mutation/create/field_kinds/field_kind_json_test.go:73]: though: LOL that's a long error 😱

**Review by shahzadlone — APPROVED** [review]
NICE!

Praise:
```
Coverage    74.98%   74.99%   +0.01%
```

**Review by islamaliev — APPROVED** [review]
Awesome. Thanks for tests
