### PR TITLE
fix: Guarantee event processing order

### LINKED ISSUE #1351: simpleChannel does not guarantee order of execution
For example if:

1) Create Doc
2) Subscribe to events

(2) may be processed before (1), resulting in the subscription erroneously receiving the event for (1).

Likely responsible for a significant portion of recent test flakiness.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1351 #1349
May also resolve much of the current test flakiness, but there may be other underlying issues so I'll leave those open for a bit. It does not resolve all of the flakiness and I have seen one P2P local failure on this branch (logged in https://github.com/sourcenetwork/defradb/issues/1338 )

## Description

Modifies the simpleChannel to guarantee the processing order of stuff. 

The previous solution did not do this, and allowed new subscriptions to pick up database events that had previously occurred but had not yet been processed by `handleChannel`.

A common scenario for how this can result in a test failure is documented in #1351

Also includes a fix for https://github.com/sourcenetwork/defradb/issues/1349 as I believe it occurs in the same part of the codebase, for similar reasons, and there is no point putting up a second, dependant review for it.

### CODE REVIEW

File: events/simple.go [hunk 1]
```diff
@@ -11,26 +11,39 @@
...
+	// WARNING: This does mean that non-event commands can block the database if the buffer
+	// size is breached (e.g. if many subscribe commands occupy the buffer).
+	commandChannel  chan any
+	eventBufferSize int
+	hasClosedChan   chan struct{}
+	isClosed        bool
 }
 
-// NewSimpleChannel creates a new simpleChannel with the given subscriberBufferSize and
+type subscribeCommand[T any] Subscription[T]
```
Comment (AndrewSisley) [inline events/simple.go:28]: Note: Fred suggested dropping the `command` suffix for these, or shortening it to `cmd`.  I have a minor preference for the current names (I like it being clear that they are commands, and not an e.g. `subscribe` type, I also prefer the more verbose name).

Happy to change this though if others want, or if Fred's preference is/becomes stronger than I think it is :)

Comment (islamaliev) [reply events/simple.go:28]: I would be against dropping the suffix because at the moment it clearly shows that these types belong to a single concept. Shortening would be fine though especially because `cmd` is well-known. But my personal preference is to keep `command`

**Review by islamaliev — APPROVED** [review]
LGTM

File: events/simple.go (hunk 1 above)
Comment (shahzadlone) [reply events/simple.go:28]: Prefer to keep it the way it is.

**Review by shahzadlone — APPROVED** [review]
LGTM! Tested this quite a few times again, and can confirm it is significantly less flakey! Even had a pass on my machine that would never pass before.

File: events/simple.go (hunk 1 above)
Comment (AndrewSisley) [reply events/simple.go:28]: Will keep as-is then :)

**Comment by AndrewSisley** [comment]
> LGTM! Tested this quite a few times again, and can confirm it is significantly less flakey! Even had a pass on my machine that would never pass before.

Really glad to hear - thanks again for your help with this one :)
