### PR TITLE
fix: Fix identity-related bugs in c bindings

### LINKED ISSUE #4091: Fix all c-binding identity bugs.
There are 2 or 3 types of c-binding bugs I found related to access control and identity passing between the c wrapper step.

Bugs:

1) Memory leaks: There are a lot of instances where the c type pointers are not freeing the identity pointer properly like it is for other properties.
For example in `cbindings/wrapper.go` consider:
```go
func (w *CWrapper) AddDACPolicy(
	ctx context.Context,
	policy string,
) (client.AddPolicyResult, error) {
	cIdentity := identityFromContext(ctx)
	cPolicy := C.CString(policy)
	defer C.free(unsafe.Pointer(cPolicy))
...
```
Note: the `cIdentity` does not have a defer `C.free` call (I am assuming that is a memory bug, and not purposeful @ChrisBQu correct me if I am wrong please). There are many other instances like this.

2) No identity being passed: The second bug is that the identity is not being passed at all. This means for all NAC instances where this happens, we would see `"not authorized to perform operation"` error even when access is given. Kind of the same bug as the one highlighted in this PR comment: https://github.com/sourcenetwork/defradb/pull/4088#discussion_r2449972401

Solution should be similar to this: https://www.loom.com/share/25979d65369a41d4b85f3a0f50e11b33?sid=8b566e4a-e944-4e98-b0c1-1a2f73987c36
Some NAC tests would have a `todo` marked this ticket where we need to add `state.CClientType` in the `SupportedClientTypes` list(`[]state.ClientType`) 

As of writing, this bug is at least in 3 places (likely way more places). `VerifySignature` and `GetIdentityNode` commands + the newly added commands all have this issue.

- Also fix for: https://github.com/sourcenetwork/defradb/pull/4088#discussion_r2451838155

- Also fix for p2p nac cbinding tests introduced in: https://github.com/sourcenetwork/defradb/pull/4111

### PR DESCRIPTION
**Pull request by ChrisBQu**
## Relevant issue(s)

Resolves #4091 

## Description

This pull request does a few different things, which are all related to bugs in the way the c bindings, and the c binding integration test wrapper, used and passed identity.

Firstly:

A new function is available, `IdentityFree`, which takes an identity pointer, checks whether or not it is valid, and if it is valid, calls `Delete` on the associate CGO handle. This function is exported and made available to users, however we also now use it throughout the C client wrapper. Previously, we were creating a CGO handle every time we extracted an identity from a context, and made a pointer out of it, but we were never actually deleting the handle. This is probably harmless on the scale our tests exist, but it is a memory leak, and it is wrong. This has been fixed.

Secondly:

Several functions never took in identity, when in reality, they were supposed to. These are `BlockVerifySignature` ,`IndexList` , and `IndexDrop` , and all of the P2P-related functions. Because identity was never being passed into these functions, errors creeped in with regards to permissions of actions. To address this, these functions now take either a `CollectionOptions` object, or an identity pointer. 

*There has been a bit of questioning around whether or not the use of CollectionOptions is ideal in all of these locations. I think we should have a team-wide discussion on this topic, however, I think it should be a separate PR.*

Thirdly:

These changes have resulted in integration tests that were not behaving correctly before, to work.

 The C client type has been enabled for the following tests, and they will pass:

`TestNAC_AdminRelation_CanIndexCreate`
`TestNAC_AdminRelation_CanIndexDrop`
`TestNAC_AdminRelation_CanIndexList`

Tests prefixed with `TestNAC_GatesP2P*`
Tests prefixed with `TestNAC_AdminRelation*`

The to-do has been removed from the following tests, as it will not (and should not) ever pass:

`TestNAC_AdminRelation_CanVerifySignature`
`TestNAC_GatesVerifySignature_AuthorizedIdentity_AllowAccess`

And instead, the C client has been added as a supported client for the following tests, where it will pass:

`TestNAC_AdminRelation_GoClient_CanVerifySignature`
`TestNAC_GatesVerifySignature_GoClient_AllowAccess` (renamed: `TestNAC_GatesVerifySignature_GoClient_AuthorizedIdentity_AllowAccess`)

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Specify the platform(s) on which this was tested:
- WSL

### CODE REVIEW

File: cbindings/wrapper.go [hunk 1]
```diff
@@ -706,11 +720,25 @@ func (w *CWrapper) GetCollections(
...
-	defer C.free(unsafe.Pointer(colName))
+	cVersion := C.CString("")
+	cCollectionID := C.CString("")
+	cName := C.CString("")
+	cIdentity := identityFromContext(ctx)
+	defer C.free(unsafe.Pointer(cVersion))
+	defer C.free(unsafe.Pointer(cCollectionID))
+	defer C.free(unsafe.Pointer(cName))
+	defer C.IdentityFree(cIdentity)
+	defer C.IdentityFree(cIdentity)
```
Comment (shahzadlone) [inline cbindings/wrapper.go]: todo: There is a duplicate free.

```suggestion
	defer C.IdentityFree(cIdentity)
	defer C.IdentityFree(cIdentity)
```

File: tests/integration/acp/nac/signature_verify_test.go
Comment (shahzadlone) [inline tests/integration/acp/nac/signature_verify_test.go:1]: praise: Cheers for sorting this out

**Review by shahzadlone — APPROVED** [review]
Thanks for sorting this out bud, we discussed most of this in the call today so giving an LGTM and summarizing the todo(s) that need to be resolved pre-merge:

1) Rebase with develop, then resolve the missing todo(s) introduced in: https://github.com/sourcenetwork/defradb/pull/4111

2) Rename `TestNAC_GatesVerifySignature_GoClient_AllowAccess` to `TestNAC_GatesVerifySignature_GoClient_AuthorizedIdentity_AllowAccess`

3) Fix the double/extra free-ing

File: cbindings/index.go [hunk 2]
```diff
@@ -112,15 +124,21 @@ func IndexList(nodePtr C.uintptr_t, collectionName *C.char) C.Result {
...
+
+	collectionName := C.GoString(options.name)
 
 	store, err := getStoreFromPointer(nodePtr)
 	if err != nil {
 		return returnC(returnGoC(1, err.Error(), ""))
 	}
 
-	col, err := store.GetCollectionByName(ctx, C.GoString(collectionName))
+	col, err := store.GetCollectionByName(ctx, collectionName)
```
Comment (AndrewSisley) [inline cbindings/index.go:141]: question: Why are you doing this manually, instead of the `parseCollectionOptions` => `getCollection` flow I've seen elsewhere? e.g. in `CollectionUpdate`.

File: cbindings/p2p.go [hunk 3]
```diff
@@ -176,8 +211,16 @@ func P2PdocumentGetAll(nodePtr C.uintptr_t) C.Result {
...
-func P2PdocumentSync(nodePtr C.uintptr_t, collection *C.char, docIDs *C.char, timeoutStr *C.char) C.Result {
+func P2PdocumentSync(nodePtr C.uintptr_t,
+	collection *C.char,
+	docIDs *C.char,
+	timeoutStr *C.char,
+	identityPtr C.uintptr_t) C.Result {
 	ctx := context.Background()
+	ctx, err := contextWithIdentity(ctx, identityPtr)
+	if err != nil {
+		return returnC(returnGoC(1, err.Error(), ""))
```
Comment (AndrewSisley) [inline cbindings/p2p.go:222]: suggestion: The code seems to do this a lot - perhaps it would be better to write a function for this - this will reduce the noise from the usually unimportant error returns.

e.g.
```
func returnCErr(error) C.Result

func P2PdocumentSync() {
  ...
  if err != nil {
    return returnCErr(err)
  }
}
```

**Review by AndrewSisley — APPROVED** [review]
LGTM, but IMO this really should have been 2 different PRs, and two different items in the change log.

File: cbindings/index.go (hunk 2 above)
Comment (ChrisBQu) [reply cbindings/index.go:141]: That's a good catch. The honest answer is the same reasoning behind the order of parameters in the function name: because this was the first one I fixed, while working through it in real time, on a call with Shahzad. :) Can definitely do better. Let me just re-tackle this function and make a fresh commit.

Comment (ChrisBQu) [reply cbindings/index.go:141]: Actually taking a closer look at it, I have some thoughts. It was a quick-change from taking in a collectionName to taking in a CollectionOptions, and this line is a result of that change. But I think the reason it called GetCollectionByName, taking in that parameter, is because that is how the CLI does it (see: `cli/index_list.go` line 34.)

I'm not against refactoring this for consistency if you feel strongly that the other approach is cleaner. However, your other comment already suggests maybe this PR should have been broken into two. I think that would further dilute it. Perhaps if its deemed important, we make a separate issue?

Comment (AndrewSisley) [reply cbindings/index.go:141]: > because that is how the CLI does it

I think a lot of the c-bindings functions have this inconsistency - here we are trading inconsistencies against each other :)  I also think the c-bindings way is superiour and should probably be ported to our other clients.

If you feel like this needs more thought, you are probably right to not do it in this PR though.  Happy either way as this is just a couple of lines here and can be merged immediately after.
