### PR TITLE
fix: Connect peers with retries in tests

### LINKED ISSUE #4287: Flaky network tests: all dials failed
Some tests that many nodes sometimes fails with error `all dials failed`. Here is an example:
```
--- FAIL: TestBranchableCollectionSync_WithDocumentsFromPeersAndNewHeadAfterSync_ShouldHaveIdenticalDAG (2.11s)
    utils.go:2160: 
                Error Trace:    /Users/islam/dev/sourcenetwork/defradb/tests/integration/utils.go:2160
                                                        /Users/islam/dev/sourcenetwork/defradb/tests/integration/p2p.go:94
                                                        /Users/islam/dev/sourcenetwork/defradb/tests/integration/utils.go:360
                                                        /Users/islam/dev/sourcenetwork/defradb/tests/integration/utils.go:309
                                                        /Users/islam/dev/sourcenetwork/defradb/tests/integration/utils.go:237
                                                        /Users/islam/dev/sourcenetwork/defradb/tests/integration/net/sync/branchable_collection/complex_network_test.go:547
                Error:          Received unexpected error:
                                failed to dial: failed to dial 12D3KooWAqK4oeVxkvM4QX7pSHFcEHurvDS3SwXHjeotyjLygRBg: all dials failed
                                  * [/ip4/192.168.178.75/tcp/53236] dial backoff
                Test:           TestBranchableCollectionSync_WithDocumentsFromPeersAndNewHeadAfterSync_ShouldHaveIdenticalDAG
```

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4287

## Description

Implement peer connection retries in testing framework.

### CODE REVIEW

File: tests/integration/p2p.go [hunk 1]
```diff
@@ -125,12 +129,35 @@ func reconnectPeers(s *state.State) {
...
+			err = connectWithRetry(ctx, sourceNode, targetAddresses)
 			require.NoError(s.T, err)
 		}
 	}
 }
 
+// connectWithRetry attempts to connect to target addresses with retry logic
+// to handle transient "dial backoff" errors that can occur when libp2p's host
+// is not fully ready to accept connections.
+func connectWithRetry(ctx context.Context, node *state.NodeState, targetAddresses []string) error {
```
Comment (fredcarle) [inline tests/integration/p2p.go:139]: thought: An alternative to this would be to pass an option to `go-p2p` when testing where it would retry immediately on dial-backoff with a backoff clearing.
```go
// in go-p2p host.go
p.host.Network().(*swarm.Swarm).Backoff().Clear(addrInfo.ID)
```

**Review by fredcarle — APPROVED** [review]
LGTM. There is an alternative solution but if this works for what you are trying to do I'm ok with it.
