### PR TITLE
fix: Add missing delta payload

### LINKED ISSUE #2299: delta field on commit/version queries returns incorrect result
**Describe the problem**
When requesting the `delta` field on either ` _version` object or a `commit` query will return incorrect values.

**To Reproduce**
- Create any schema
- Create any document with that schema
- Query the `_version` field or `commit` query specifying the `delta` in the selection set

**Expected behavior**
Return the base64 encode delta payload, instead it just seems to return the string "Data"

**Platform**
Linux WSL

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2299

## Description

This PR fixes a regression bug and adds integration tests to ensure that future changes don't break the expected query results

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test and manual queries

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: tests/integration/query/commits/simple_test.go [hunk 1]
```diff
@@ -315,3 +313,118 @@ func TestQueryCommitsWithFieldIDFieldWithUpdate(t *testing.T) {
...
+								name
+							}
+						}
+					}
+				`,
+				Results: []map[string]any{
+					{
+						"cid":          "bafybeiddpjl27ulw2yo4ohup6gr2wob3pwagqw2rbeaxxodv4ljelnu7ve",
+						"collectionID": int64(1),
+						"delta":        []uint8([]byte{0x16}),
```
Comment (nasdf) [inline tests/integration/query/commits/simple_test.go:354]: question: should this be a base64 encoding instead?

File: request/graphql/schema/types/commits.go [hunk 2]
```diff
@@ -47,47 +47,47 @@ var (
 		Name:        request.CommitTypeName,
 		Description: commitDescription,
 		Fields: gql.Fields{
-			"height": &gql.Field{
+			request.HeightFieldName: &gql.Field{
```
Comment (nasdf) [inline request/graphql/schema/types/commits.go:50]: praise: this is much cleaner

**Review by nasdf — APPROVED** [review]
Fix looks good! Just one question about encoding.

File: request/graphql/schema/types/commits.go (hunk 2 above)
Comment (AndrewSisley) [reply request/graphql/schema/types/commits.go:50]: It looks nicer, but now we have lost protection against these changing.  I have mixed feelings about this change.

**Review by AndrewSisley — APPROVED** [review]
Looks good to me, and thank you for the tests :)

I am a bit uncomfortable about the use of production constants in the expected test results, but not uncomfortable enough to block it :)

File: tests/integration/query/commits/simple_test.go (hunk 1 above)
Comment (fredcarle) [reply tests/integration/query/commits/simple_test.go:354]: yes. Trying to figure something out for this. It si base64 when using CLI and HTTP clients but not when using the go client.

Comment (fredcarle) [reply tests/integration/query/commits/simple_test.go]: So it's base64 with CLI and HTTP clients because that's how `json.Marshal` will convert `[]uint8` to `string` representation. I've added support for `[]uint8` result assertion when using the CLI and HTTP clients.

**Review by shahzadlone — APPROVED** [review]
Thanks for this fix! LGTM
