### PR TITLE
fix: Introspection OrderArg returns null inputFields

### LINKED ISSUE #1463: Erroneous introspection schema resulting from one-to-many schema
We obtain a erroneous introspection schema when using a one-to-relation relationship.

Using the `booksmany.gql` example:
```graphql
type Book {
    name: String
    rating: Float
    author: Author
}

type Author {
    name: String
    age: Int
    verified: Boolean
    published: [Book]
}

```

We obtain in GraphiQL:

```
Error: Introspection result missing inputFields: 
{"description":"","enumValues":null,"fields":null,"inputFields":null,"interfaces":null,"kind":"INPUT_OBJECT","name":"AuthorOrderArg","possibleTypes":null}
```

### LINKED ISSUE #1502: GraphQL error `Unknown kind of type: ` with one-to-many schema
On develop as of this issue, i.e. https://github.com/sourcenetwork/defradb/commit/a49dbed63feab151487c1a165d647c3311bbe8a4

GraphQL error `Unknown kind of type: ` is obtained

With schema

```gql
type Book {
	name: String
	author: Author
}
type Author {
	name: String
	published: [Book]
}
```

And introspection query (default from clients GraphiQL, Altair, ...):
```
query IntrospectionQuery {
  __schema {
    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type { ...TypeRef }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
```

### LINKED ISSUE #1632: Introspection returns `OrderArg` with null `inputFields`
**Describe the problem**
When introspecting a schema with a many-to-one relationship it returns an `OrderArg` with null `inputFields`.  This causes an error in the latest GraphiQL.

**To Reproduce**
Create a schema with a many-to-one relationship and run introspection.

```
type user {
    age: Int
    name: String
    points: Float
    verified: Boolean
}

type group {
    members: [user]
}
```

**Expected behavior**
I believe the expected behavior is to return the `OrderArg` object with at least 1 `inputField`.

**Platform**
MacOS develop branch

**Additional context**

Introspection result excerpt:

```
...
{
    "description": "",
    "enumValues": null,
    "fields": null,
    "inputFields": null,
    "interfaces": null,
    "kind": "INPUT_OBJECT",
    "name": "groupOrderArg",
    "possibleTypes": null
}
...
```

Error from GraphiQL:

```
{
  "errors": [
    {
      "message": "Introspection result missing inputFields: { description: \"\", enumValues: null, fields: null, inputFields: null, interfaces: null, kind: \"INPUT_OBJECT\", name: \"groupOrderArg\", possibleTypes: null }.",
      "stack": "Error: Introspection result missing inputFields: { description: \"\", enumValues: null, fields: null, inputFields: null, interfaces: null, kind: \"INPUT_OBJECT\", name: \"groupOrderArg\", possibleTypes: null }.\n    at buildInputObjectDef (http://localhost:5173/node_modules/.vite/deps/chunk-JJM3ZUCC.js?v=1e9f098c:8874:13)\n    at buildType (http://localhost:5173/node_modules/.vite/deps/chunk-JJM3ZUCC.js?v=1e9f098c:8795:18)\n    at http://localhost:5173/node_modules/.vite/deps/chunk-JJM3ZUCC.js?v=1e9f098c:8724:28\n    at keyValMap (http://localhost:5173/node_modules/.vite/deps/chunk-JJM3ZUCC.js?v=1e9f098c:3137:27)\n    at buildClientSchema (http://localhost:5173/node_modules/.vite/deps/chunk-JJM3ZUCC.js?v=1e9f098c:8721:19)\n    at http://localhost:5173/node_modules/.vite/deps/chunk-5EYXVEAX.js?v=1e9f098c:23864:27"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #1632 
Resolves #1502 
Resolves #1463

## Description

This PR adds an introspection test that identifies an issue with `orderArg`.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

`make test`

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: tests/integration/schema/input_type_test.go [hunk 1]
```diff
@@ -16,6 +16,115 @@ import (
...
+													"name": "_key",
+													"type": map[string]any{
+														"name":   "Ordering",
+														"ofType": nil,
+													},
+												},
+												map[string]any{
+													"name": "members",
+													"type": map[string]any{
+														"name":   "",
```
Comment (nasdf) [inline tests/integration/schema/input_type_test.go:109]: I think this may be the root of the issue. The name should not be empty.

**Review by fredcarle — APPROVED** [review]
Great investigative work on this one Keenan.

I'm pretty sure this PR also resolves #1502 and #1463 so you could add them to the set of resolved issues in the PR description.
