### PR TITLE
fix: Fix invalid (badger) datastore state

### LINKED ISSUE #1672: AssertFail in badger file on db close
Has started happening in the change detector recently, happens in `TestQueryOneToOneWithGroupRelatedIDFromSecondary` most (but not all) of the time.  Removing the last query removes the assert fail.

*Might* be a badger bug, as they seem to have had issues in the past: https://github.com/dgraph-io/badger/issues/1350

If the request in the test is modified:

This fails:
```
Request: `query {
	Book {
		name
	}
}`,
``` 
This works:
```
Request: `query {
	Author {
		name
	}
}`,
``` 
- Removing either one of the Author create actions removes/hides the problem. 
- Removing lines 874-891 (where secondary id creation is handled) from collection.go has no impact.
- Removing the Lens fetcher has no impact.
- Updating to badger v4.1.0 has no impact
- Exiting before calling `fetcher.FetchNextDoc` in scan node removes the error, suggesting that `fetcher.Init` and `fetcher.Start` are not relevant in this issue.
- Exiting immediately after the `FetchNext` call in `FetchNextDoc` has no impact, suggesting `FetchNext` is responsible
- Removing the filter stuff from `FetchNext` has no impact, suggesting it's irrelevance
- Returning an error anywhere within the last 4 lines of `fetcher.nextKey` removes the assert failure
- Calling `nextKV` 8 times results in the failure, calling it 7 times does not.  The key on the 8th value is `/1/v/bae-d6627fea-8bf7-511c-bcf9-bac4212bddd6/v`
- Calling `df.kvResultsIter.NextSync()` in `nextKVRaw` a 9th time results in the problem, regardless of whether the value is ignored or not

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1672

## Description

Fixes invalid datastore state where somehow the iterator is not closed properly, even though Close is called.  I am guessing that something is getting GC'd before it can be closed, as closing it immediately after use appears to remove the issue.

Bug discovered testing with badger-file, but I cannot be sure where the GC'd object is, and so it could be within the ipfs code, which could mean other datastore implementations were exposed to this.

Fix is commit `Close iterator on spanDone` *only*, the others are small improvements to the codebase I found along the way.

### CODE REVIEW

File: db/fetcher/fetcher.go [hunk 1]
```diff
@@ -332,6 +332,10 @@ func (df *DocumentFetcher) nextKey(ctx context.Context, seekNext bool) (spanDone
 
 	df.kvEnd = spanDone
 	if df.kvEnd {
+		err = df.kvResultsIter.Close()
```
Comment (shahzadlone) [inline db/fetcher/fetcher.go:335]: Question: where was this close happening before? Do we have to worry about double closing now?

**Review by shahzadlone — APPROVED** [review]

File: db/fetcher/fetcher.go (hunk 1 above)
Comment (AndrewSisley) [reply db/fetcher/fetcher.go:335]: Double closing is a non-issue, the docs say you can close as often as you like.  Before it was happening in fetcher.Close, and fetcher.startNextSpan.  It is still done in those places. In some situations (like the uncommented out test) Close will now be called multiple times.
