### PR TITLE
fix: Make all array kinds nillable

### LINKED ISSUE #2533: Array field kinds return incorrect value for `IsNillable`

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #2533

## Description

This PR fixes a bug where `ScalarArrayKind.IsNillable()` returned an incorrect value for arrays of non-nillable values.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

`make test`

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
Thanks for finding this :) Got a couple of todos for you though

File: client/schema_field_description.go [hunk 1]
```diff
@@ -154,7 +154,11 @@ func (k ScalarArrayKind) Underlying() string {
 }
 
 func (k ScalarArrayKind) IsNillable() bool {
```
[the remark this answers is not in the document]
Comment (nasdf) [reply client/schema_field_description.go:156]: I'm actually not sure how the tests did not fail before. I'm still investigating, but I believe its because of encoding / decoding of `[]int{}` vs `nil`.

[the remark this answers is not in the document]
Comment (nasdf) [reply client/schema_field_description.go:156]: I've added a unit test, but I don't think an integration test can actually catch this problem due to the encoding I mentioned above.

**Review by AndrewSisley — APPROVED** [review]
LGTM, thanks Keenan :)

File: client/schema_field_description.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (AndrewSisley) [reply client/schema_field_description.go:156]: https://github.com/sourcenetwork/defradb/issues/2539

File: client/normal_value_test.go [hunk 2]
```diff
@@ -1622,3 +1622,28 @@ func TestNormalValue_ToArrayOfNormalValues(t *testing.T) {
 		})
 	}
 }
+
+// This test documents a bug where array values
+// were not returning the correct value for IsNillable
+// and were also not convertible to a normal nil kind.
+func TestArrayValue_IsNillable(t *testing.T) {
```
Comment (fredcarle) [inline client/normal_value_test.go:1629]: thought: I'm not sure that this is correct. Please wait before merging.

File: client/normal_nil.go [hunk 3]
```diff
@@ -34,13 +34,13 @@ func NewNormalNil(kind FieldKind) (NormalValue, error) {
 		return NewNormalNillableString(immutable.None[string]()), nil
 	case FieldKind_NILLABLE_BLOB:
 		return NewNormalNillableBytes(immutable.None[[]byte]()), nil
-	case FieldKind_NILLABLE_BOOL_ARRAY:
+	case FieldKind_BOOL_ARRAY, FieldKind_NILLABLE_BOOL_ARRAY:
```
Comment (fredcarle) [inline client/normal_nil.go:37]: todo: This should be changed to 
```go
case FieldKind_BOOL_ARRAY:
    return NewNormalIntNillableArray(immutable.None[[]bool]()), nil
case FieldKind_NILLABLE_BOOL_ARRAY:
	return NewNormalNillableBoolNillableArray(immutable.None[[]immutable.Option[bool]]()), nil
```
and similarly for the other array types.

Comment (AndrewSisley) [reply client/normal_nil.go:37]: Nice spot :)

File: client/normal_value_test.go (hunk 2 above)
Comment (fredcarle) [reply client/normal_value_test.go:1629]: All good here. I got mixed up because of us not updating the field kinds.

File: client/normal_value_test.go [hunk 4]
```diff
@@ -1622,3 +1622,28 @@ func TestNormalValue_ToArrayOfNormalValues(t *testing.T) {
...
+	fieldKinds := []FieldKind{
+		FieldKind_BOOL_ARRAY,
+		FieldKind_INT_ARRAY,
+		FieldKind_FLOAT_ARRAY,
+		FieldKind_STRING_ARRAY,
+		FieldKind_NILLABLE_BOOL_ARRAY,
+		FieldKind_NILLABLE_INT_ARRAY,
+		FieldKind_NILLABLE_FLOAT_ARRAY,
+		FieldKind_NILLABLE_STRING_ARRAY,
```
Comment (islamaliev) [inline client/normal_value_test.go:1638]: todo: sorry, but I'm trying to figure out what this PR actually tries to achieve.
Looking at this test I'm a bit confused.
We have the following array types:
1. FieldKind_<type>_ARRAY - NOT nillable array with NOT nillable elements
2. FieldKind_NILLABLE_<type>_ARRAY - NOT nillable array with nillable elements
3. FieldKind_<type>_NILLABLE_ARRAY - nillable array with NOT nillable elements
4. FieldKind_NILLABLE_<type>_NILLABLE_ARRAY - nillable array with nillable elements
At least this is how these different array kinds are supposed to be distinguished.

At the moment `IsNillable` on `ScalarArrayKind` return true IIRC only elements are nillable, but it's no ideal. I also planned to put some effort on this.

So please clarify which of those 4 types you are changing and how.

Comment (AndrewSisley) [reply client/normal_value_test.go:1638]: There was a discord conversation around this, all the scalar arrays are nillable atm, the enum values are just stuck with the old names.  e.g. `FieldKind__ARRAY` is nillable, with non-nillable elements.

Comment (fredcarle) [reply client/normal_value_test.go:1638]: At the moment, `FieldKind__ARRAY` is a Nillable array with nillable elements. That is where we all get confused. This needs to be fix. This PR ensures that things work as they should given the current naming.

Comment (fredcarle) [reply client/normal_value_test.go:1638]: `FieldKind__NILLABLE_ARRAY` and `FieldKind_NILLABLE__NILLABLE_ARRAY` don't exist at the moment.

Comment (islamaliev) [reply client/normal_value_test.go:1638]: looks like I missed this discord conversation. All right then
