### PR TITLE
fix: Handle compound filters on related indexed fields

### LINKED ISSUE #2572: Compound filter targeting related indexed field errors
Querying with a compound (and/or) filter targeting related indexed field errors.

- This happens with or without data in the database.
- the compound operator can be either `_and` or `_or`, omitting the compound operator does not result in an error.
- The error occurs whether the index is unique or not.
- The kind of simple operator in the filter (e.g. `_ilike`, `_eq`, etc) does not appear to matter.

For example:
```
func TestFoo(t *testing.T) {
	test := testUtils.TestCase{
		Actions: []any{
			testUtils.SchemaUpdate{
				Schema: `
				  type Program {
					name: String
					certificationBodyOrg: Organization
				  }

				  type Organization {
					name: String @index
					programs: [Program]
				  }`,
			},
			testUtils.Request{
				Request: `query {
					Program(
					  filter: {
						_and: [
							{ certificationBodyOrg: { name: { _ilike: "%Test3%" } } }
						]
					  }
					) {
					  name
					}
				  }`,
				ExpectedError: "invalid filter operator is provided. Operator: _any",
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
}
``` 

Bug is hitting ln 661 and then 689 in `indexer_iterators.go`, func `IndexFetcher.determineFieldFilterConditions()`.  That function does not appear to have been written with compound operators in mind.  In the above test case ln 659 is hit, but ln 663 is not.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #2572

## Description

Handles compound filters targeting related indexed fields, and one-many joins from the many side.

The invertableJoin issue may be affecting non indexed joins.

First commit documents the existing behaviour, second commit fixes it.

There is another issue in this space not solved by this PR: https://github.com/sourcenetwork/defradb/issues/2574

### CODE REVIEW

File: planner/filter/complex.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ func isComplex(conditions any, seekRelation bool) bool {
 			if op, ok := k.(*mapper.Operator); ok {
 				switch op.Operation {
 				case request.FilterOpOr, request.FilterOpAnd, request.FilterOpNot:
-					if v, ok := v.([]any); ok && len(v) == 1 {
+					if v, ok := v.([]any); ok && len(v) == 0 {
```
Comment (AndrewSisley) [inline planner/filter/complex.go:36]: It is not ideal to keep this as-is long-term, as it will prevent a possible performance-shortcut once John's fetcher rework gets merged, but for now it is a simple way of excluding the index fetcher filter's lack of support for compound filters..

File: planner/type_join.go [hunk 2]
```diff
@@ -487,6 +486,9 @@ type invertibleTypeJoin struct {
 	secondaryFieldIndex immutable.Option[int]
 	secondaryFetchLimit uint
 
+	// docsToYield contains cocuments read and ready to be yielded by this node.
```
Comment (fredcarle) [inline planner/type_join.go:489]: typo: documents

**Review by nasdf — APPROVED** [review]
LGTM. The additional test coverage is really nice.

File: planner/type_join.go [hunk 3]
```diff
@@ -556,6 +558,17 @@ func (join *invertibleTypeJoin) processSecondResult(secondDocs []core.Doc) (any,
 }
 
 func (join *invertibleTypeJoin) Next() (bool, error) {
```
Comment (nasdf) [inline planner/type_join.go:560]: thought: This function is really difficult to understand.

Comment (AndrewSisley) [reply planner/type_join.go:560]: Yes, and IMO the variable names don't really pair up well either, and they actually represent different things in different situations.

File: planner/type_join.go (hunk 2 above)
Comment (AndrewSisley) [reply planner/type_join.go:489]: :) will fix

- [ ] typo

File: planner/filter/complex.go (hunk 1 above)
Comment (AndrewSisley) [reply planner/filter/complex.go:36]: Will do.  I think it is valid to submit an empty and/or clause, but probably not really worth the extra code for that :)

- [ ] Remove len 0 check

File: planner/type_join.go (hunk 3 above)
Comment (AndrewSisley) [reply planner/type_join.go:560]: https://github.com/sourcenetwork/defradb/issues/2577

File: tests/integration/index/query_with_compound_filter_relation_test.go [hunk 4]
```diff
@@ -0,0 +1,362 @@
...
+				  type Organization {
+					name: String @index
+					programs: [Program]
+				  }`,
+			},
+			testUtils.Request{
+				Request: `query {
+					Program(
+						filter: {
+							_and: [
```
Comment (islamaliev) [inline tests/integration/index/query_with_compound_filter_relation_test.go:73]: todo: this is not `_or`

File: tests/integration/index/query_with_compound_filter_relation_test.go [hunk 5]
```diff
@@ -0,0 +1,362 @@
...
```
Comment (islamaliev) [inline tests/integration/index/query_with_compound_filter_relation_test.go:108]: todo: this is not `_not`

File: tests/integration/index/query_with_compound_filter_relation_test.go (hunk 4 above)
Comment (AndrewSisley) [reply tests/integration/index/query_with_compound_filter_relation_test.go:73]: https://github.com/sourcenetwork/defradb/pull/2581
