### PR TITLE
fix: Make GraphQL errors spec compliant

### LINKED ISSUE #3039: GraphQL response errors are not spec compliant
See https://spec.graphql.org/October2021/#sec-Errors

### LINKED ISSUE #3041: client GQLResult is not spec compliant
The `client.GQLResult` type does not define errors in a spec compliant way.

See https://spec.graphql.org/October2021/#sec-Errors

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #3039
Resolves #3041

## Description

This PR fixes an issue with response errors not being spec compliant.

It also adds a `GQLError` type to the client package.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Added tests here https://github.com/sourcenetwork/defradb-third-party-test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by fredcarle — APPROVED** [review]
LGTM

File: client/db.go [hunk 1]
```diff
@@ -290,14 +296,33 @@ type GQLResult struct {
...
 	// If there are values in this slice the request will likely not have run to completion
 	// and [Data] will be nil.
-	Errors []error `json:"errors,omitempty"`
+	Errors []GQLError `json:"errors,omitempty"`
 
 	// Data contains the resultant data produced by the GQL request.
 	//
 	// It will be nil if any errors were raised during execution.
 	Data any `json:"data"`
 }
```
Comment (AndrewSisley) [inline client/db.go:305]: suggestion:  If you add a Marshal/Unmarshal func for `GQLResult` you could probably drop the new types and functions.  It might also be nicer for users of the Go client.

Comment (fredcarle) [reply client/db.go:305]: I would just add a custom Marshal/Unmarshal func for `GQLError` instead .

Comment (nasdf) [reply client/db.go:300]: > I would just add a custom Marshal/Unmarshal func for GQLError instead .

I think the custom marshalling only works if its on the GQLResult and we want to keep errors as the generic `error` type.

I've refactored it to use a custom marshaller and added some tests to make sure our http server returns proper responses.

**Review by fredcarle — APPROVED** [review]
LGTM. The Marshal/Unmarshal change is nice.
