### PR TITLE
fix: Handle the querying of secondary relation id fields

### LINKED ISSUE #1654: Secondary relation id is unavailable when querying one-one relations
See documenting tests:
- `TestQueryOneToOneWithGroupRelatedIDFromSecondary`
- `TestQueryOneToOneWithGroupRelatedIDAliasFromSecondary`

Likely affects all stuff (order, filter) not just group by.
- https://github.com/sourcenetwork/defradb/issues/1670
- https://github.com/sourcenetwork/defradb/issues/1671

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1654

## Description

Handles the querying of secondary relation id fields.

It does this by joining the related object and copying the dockey value into the secondary related id field.

- ~~Is currently blocked by https://github.com/sourcenetwork/defradb/issues/1769 but can still be reviewed now~~ ~~PR is now based off the fix for that issue (do not review the first commit here).  Will rebase off develop branch before merge.~~ Fix merged to develop, this branch has been rebased onto it.

### CODE REVIEW

File: tests/integration/query/one_to_one/simple_test.go
Comment (fredcarle) [inline tests/integration/query/one_to_one/simple_test.go:1]: suggestion: Can you please add a test in `one_to_one_to_one` with a query on `Book` joining both `Author` and `Publisher`?

Comment (AndrewSisley) [reply tests/integration/query/one_to_one/simple_test.go:1]: I'm curious, not argumentative - how do you see that breaking/being-relevant?

Comment (fredcarle) [reply tests/integration/query/one_to_one/simple_test.go:1]: I want a test confirming that two or more joins on the one object works as expected. Pretty much to ensure `makeTypeJoinOne` works in these kinds of situations.

Comment (AndrewSisley) [reply tests/integration/query/one_to_one/simple_test.go:1]: As-in work in general? I hope we already have tests that properly cover one-one-one joins

Comment (AndrewSisley) [reply tests/integration/query/one_to_one/simple_test.go:1]: Confirmed, we already cover all possible direction combinations for one-one-one joins.

Comment (fredcarle) [reply tests/integration/query/one_to_one/simple_test.go:1]: Work in general yes and with this change. There aren't that many in the package `one_to_one_to_one` and none with the pattern I'd like to see. Maybe there are some elsewhere.

Comment (AndrewSisley) [reply tests/integration/query/one_to_one/simple_test.go:1]: > none with the pattern I'd like to see

Which pattern are you after?

Comment (fredcarle) [reply tests/integration/query/one_to_one/simple_test.go:1]:
```graphql
Book {
  name
  publisher {
    name
  }
  author {
    name
  }
}
```

Comment (AndrewSisley) [reply tests/integration/query/one_to_one/simple_test.go:1]: Ah okay spreading out from the middle obj? I'll add that in another PR/branch real quick. But not here.

Comment (fredcarle) [reply tests/integration/query/one_to_one/simple_test.go:1]: Well it's the "middle obj" in this case but what matters to me is the dual join on the one object. I think it's quite relevant here so I would like to see it added.

Comment (AndrewSisley) [reply tests/integration/query/one_to_one/simple_test.go:1]: This PR doesn't change any of the join mechanics.  It uses a join, but it doesn't change how they work.

If a bug is found in the test gap you spotted it should not block or impact the merging of this work.

https://github.com/sourcenetwork/defradb/issues/1792

Comment (fredcarle) [reply tests/integration/query/one_to_one/simple_test.go:1]: fair enough :)

File: planner/mapper/mapper.go [hunk 1]
```diff
@@ -928,6 +906,131 @@ sourceLoop:
 	return newFields, nil
 }
 
+// constructDummyJoin constructs a valid empty join with no requested fields.
+func constructDummyJoin(
```
Comment (fredcarle) [inline planner/mapper/mapper.go:910]: suggestion: I think we should avoid using the work `Dummy` as it feels more like something you'd use just for testing purposes. In this case this is a function that is used in a critical path. Maybe `constructEmptyJoin` would be more appropriate.

Comment (AndrewSisley) [reply planner/mapper/mapper.go:910]: Yeah good shout - I'll change it

- [ ] Rename Dummy func

**Review by fredcarle — APPROVED** [review]
Approving with one nitpick.

Tests have been added with two different test name format. I don't want to force you to change that but keep in mind for the future that we agreed to try to have `TestName_Details_Error` as the test name format.
