### PR TITLE
fix: Introspection test bug

### LINKED ISSUE #1502: GraphQL error `Unknown kind of type: ` with one-to-many schema
On develop as of this issue, i.e. https://github.com/sourcenetwork/defradb/commit/a49dbed63feab151487c1a165d647c3311bbe8a4

GraphQL error `Unknown kind of type: ` is obtained

With schema

```gql
type Book {
	name: String
	author: Author
}
type Author {
	name: String
	published: [Book]
}
```

And introspection query (default from clients GraphiQL, Altair, ...):
```
query IntrospectionQuery {
  __schema {
    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type { ...TypeRef }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #1502

## Description

This PR fixes an issue with the introspection test utils that caused us to mark a test as failing.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Existing tests

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: tests/integration/utils.go [hunk 1]
```diff
@@ -1695,7 +1695,7 @@ func AssertErrors(
 ) bool {
 	if expectedError == "" {
 		require.Empty(t, errs)
-	} else {
+	} else if len(errs) > 0 {
```
Comment (AndrewSisley) [inline tests/integration/utils.go]: question: I feel like I'm being slow today - this change doesn't look like it does anything.

What do you think it does?

**Review by AndrewSisley — APPROVED** [review]
I'm approving because I trust you more than me atm, but am confused :)

File: tests/integration/utils.go (hunk 1 above)
Comment (nasdf) [reply tests/integration/utils.go]: I may have fixed this in the wrong way. The problem is that an expected error is passed but no errors are returned and this function ignores that.

Comment (nasdf) [reply tests/integration/utils.go]: Okay it should look a bit more coherent now. Sorry about that.

**Review by AndrewSisley — APPROVED** [review]
LGTM! Thanks Keenan :)
