### PR TITLE
fix: Resolve incorrect merge conflict

### LINKED ISSUE #2673: Consolidate behaviour of transaction conflicts
Our in-memory store and badger behave a little differently in certain conflict situations. We should consolidate that behaviour.

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2673 

## Description

This PR fixes the incorrect merge conflict in our memory store.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: datastore/memory/txn.go [hunk 1]
```diff
@@ -270,8 +275,14 @@ func (t *basicTxn) checkForConflicts(ctx context.Context) error {
 	iter := t.ops.Iter()
 	defer iter.Release()
 	for iter.Next() {
-		expectedItem := t.ds.get(ctx, ds.NewKey(iter.Item().key), t.getDSVersion())
-		latestItem := t.ds.get(ctx, ds.NewKey(iter.Item().key), t.ds.getVersion())
+		item := iter.Item()
+		if !item.isGet {
+			// Conflict should only ocure if an item has been updated
```
Comment (shahzadlone) [inline datastore/memory/txn.go:280]:
```suggestion
			// Conflict should only occur if an item has been updated
```

**Review by islamaliev — APPROVED** [review]
LGTM!
