### PR TITLE
fix: Secondary index handle neq and nin filters

### LINKED ISSUE #4400: _neq filter with index returns wrong results
Queries using `_neq` (not equal) filter with indexed fields return incorrect results

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4400

## Description

Fix handling of `_neq` and `_nin` filters by secondary indexes.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Integration tests.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/db/fetcher/indexer_iterators.go [hunk 1]
```diff
@@ -955,6 +936,63 @@ func isComplexJSONFilterValue(filterVal any) bool {
...
+	}
+	return isComplex
+}
+
+// shouldFallbackToFullScan returns true if the index cannot efficiently handle the filter
+// and a full document scan should be used instead.
+//
+// Cases where fallback is needed:
+//   - _geq: null - every value is >= null, so the index provides no benefit
+//   - _leq: null on nested JSON paths - documents with missing JSON fields should match,
```
Comment (fredcarle) [inline internal/db/fetcher/indexer_iterators.go:956]: thought: Can't we index `null` values?

Comment (fredcarle) [reply internal/db/fetcher/indexer_iterators.go:956]: Never mind I misread.

**Review by fredcarle — APPROVED** [review]
LGTM

File: internal/db/fetcher/indexer_iterators.go (hunk 1 above)
Comment (islamaliev) [reply internal/db/fetcher/indexer_iterators.go:956]: we can and we do, but this filter for example `custom: {age: {_geq: null}}` is expected to find not only this document:
```json
{
	"name": "David",
	"custom": {"age": null}
}
```
but also this
```json
{
	"name": "Bruno"
}
```
Actually, I just added a related ticket [#4437](https://github.com/sourcenetwork/defradb/issues/4437)
