### PR TITLE
fix: Reduce telemetry logs

### LINKED ISSUE #4638: Reduce telemetry logs
The OTEL logs are spammy when running with the `-tags telemetry` build.

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #4638

## Description

This PR fixes an issue with the OTEL logs that caused the connection error message to spam.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Manually ran with `go run -tags telemetry`.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/telemetry/otel.go [hunk 1]
```diff
@@ -102,5 +108,13 @@ func ConfigureTelemetry(ctx context.Context, version string) error {
 	otel.SetMeterProvider(meterProvider)
 	// set the global trace provider for all otel instances
 	otel.SetTracerProvider(tracerProvider)
+	// reduce spammy connection messages
+	otel.SetErrorHandler(otel.ErrorHandlerFunc(func(err error) {
```
Comment (fredcarle) [inline internal/telemetry/otel.go:112]: thought: I think the comment from CodeRabbit is accurate. This will silence all other errors.

Comment (nasdf) [reply internal/telemetry/otel.go:112]: fixed

**Review by fredcarle — APPROVED** [review]
LGTM
