### PR TITLE
fix: Default json value

### LINKED ISSUE #3146: JSON object default value causes panic
Setting a JSON default value to an object type causes a panic.

```
type User {
  metadata: JSON @default(json: {one: 1})
}
```

Results in the following panic.

```
panic: runtime error: hash of unhashable type map[string]interface {}
```

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #3146

## Description

Fix default json value by properly converting it's value into a corresponding type.

### CODE REVIEW

**Review by ChrisBQu — APPROVED** [review]
LGTM.

File: internal/request/graphql/schema/collection.go [hunk 1]
```diff
@@ -434,14 +435,28 @@ func defaultFromAST(
...
+			value = string(jsonBytes)
+		}
 	case types.DefaultDirectivePropBlob:
 		value = types.Blob.ParseLiteral(arg.Value, nil)
 	}
 	// If the value is nil, then parsing has failed, or a nil value was provided.
 	// Since setting a default value to nil is the same as not providing one,
 	// it is safer to return an error to let the user know something is wrong.
-	if value == nil {
+	// Exception: JSON fields can have nil as a valid default value
```
Comment (fredcarle) [inline internal/request/graphql/schema/collection.go:458]: question: Why do we treat the JSON type differently?
