### PR TITLE
fix: Index-based order for nested queries

### LINKED ISSUE #4321: Ordering on an indexed field of a one-to-many object yields the wrong result
The order in the following query is not applied as expected. Using `ASC or DESC` yields the same result.
```gql
type Author {
  name: String
  published: [Book]
}

type Book {
  rating: Float @index
}

query {
	Author {
		published(order: {rating: DESC}) { 
			rating
		}
	}
}
```

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4321

## Description

Now secondary indexes are used for sub queries with `order` command.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Integration tests

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: tests/integration/index/query_with_relation_sub_order_test.go [hunk 1]
```diff
@@ -0,0 +1,331 @@
...
+								{"title": "Book B1", "rating": 4.0},
+								{"title": "Book B2", "rating": 2.5},
+							},
+						},
+					},
+				},
+			},
+			testUtils.Request{
+				Request:  makeExplainQuery(req),
+				Asserter: testUtils.NewExplainAsserter().WithOrder().WithIndexFetches(8),
```
Comment (AndrewSisley) [inline tests/integration/index/query_with_relation_sub_order_test.go:326]: todo: Please document why the index is being fetched 8 times when returning 4 indexed documents.

File: internal/planner/type_join.go [hunk 2]
```diff
@@ -604,8 +612,22 @@ func (r *primaryObjectsRetriever) retrievePrimaryDocs() ([]core.Doc, error) {
 
 	oldFetcher := r.primaryScan.fetcher
 	oldIndex := r.primaryScan.index
+	oldOrdering := r.primaryScan.ordering
 
 	r.primaryScan.index = findIndexByFieldName(r.primaryScan.col, r.relIDFieldDef.Name)
+	r.primaryScan.ordering = nil
```
Comment (AndrewSisley) [inline internal/planner/type_join.go]: todo: Please document why this is being explicitly set to nil

File: internal/planner/type_join.go [hunk 3]
```diff
@@ -604,8 +612,22 @@ func (r *primaryObjectsRetriever) retrievePrimaryDocs() ([]core.Doc, error) {
...
+
+	canOrderByIndex := false
+
+	if !r.primaryScan.index.HasValue() {
```
Comment (AndrewSisley) [inline internal/planner/type_join.go:621]: todo: Please document why we are only (re)setting `ordering` if the original index is None.

File: internal/planner/type_join.go [hunk 4]
```diff
@@ -604,8 +612,22 @@ func (r *primaryObjectsRetriever) retrievePrimaryDocs() ([]core.Doc, error) {
...
+		var orderIndex immutable.Option[client.IndexDescription]
+		orderIndex, canOrderByIndex = r.findOrderingIndex()
+		if canOrderByIndex {
+			r.primaryScan.index = orderIndex
+			r.primaryScan.ordering = r.ordering
```
Comment (AndrewSisley) [inline internal/planner/type_join.go:626]: todo: Please document (somewhere) why we wish to use the result of `r.findOrderingIndex` *only if* the `r.primaryScan.index` is None.

File: internal/planner/type_join.go [hunk 5]
```diff
@@ -620,6 +642,7 @@ func (r *primaryObjectsRetriever) retrievePrimaryDocs() ([]core.Doc, error) {
 
 	r.primaryScan.fetcher = oldFetcher
 	r.primaryScan.index = oldIndex
+	r.primaryScan.ordering = oldOrdering
```
Comment (AndrewSisley) [inline internal/planner/type_join.go]: todo: Please document why we are overwriting all the effort that has been done in the new `if !r.primaryScan.index.HasValue() {` block here before returning from the function.

If the result of that block is to only be consumed by `primaryScan.initFetcher`, please also explain why!

**Review by AndrewSisley — APPROVED** [review]
LGTM, thanks for the fix Islam!

File: internal/planner/type_join.go (hunk 5 above)
Comment (islamaliev) [reply internal/planner/type_join.go]: reassigninng of `oldOrdering` was just a precaution. It's not necessary. I removed it.

File: internal/planner/type_join.go (hunk 2 above)
Comment (islamaliev) [reply internal/planner/type_join.go]: This wan just a precaution, but it's not necessary. I removed it.

File: internal/planner/type_join.go (hunk 3 above)
Comment (islamaliev) [reply internal/planner/type_join.go:621]: already commented

File: internal/planner/type_join.go (hunk 4 above)
Comment (islamaliev) [reply internal/planner/type_join.go:626]: done

File: tests/integration/index/query_with_relation_sub_order_test.go (hunk 1 above)
Comment (islamaliev) [reply tests/integration/index/query_with_relation_sub_order_test.go:326]: done
