### PR TITLE
fix: Consistent version query semantics

### LINKED ISSUE #3476: Inconsistent `_version` behavior between time-travel and regular queries
**Describe the problem**
Regular queries `_version` fields return all commits up until the current commit, but time-travel queries only return one commit for the specific requested CID to time-travel to.

**To Reproduce**
Any time-travel query

**Expected behavior**
Time-travel `_version` queries return the full set of commits for the composite up to the target `cid` specified.

### PR DESCRIPTION
**Pull request by jsimnz**
## Relevant issue(s)

Resolves #3476 

## Description

Fixes the consistency between regular queries and time-travel queries with respect to the `_version` subquery. Before, the regular queries would return all commits from the start to the current, but time-travel queries only used a "latestCommit" query at the target version, which meant only returning a single commit entry.

This PR implements some semantics changes to the overall commits API, but maintains all necessary backwards compatibility (however, it does introduce new errors when using invalid cid/docid combinations).

New semantics:
- Only doc ID, default max depth, start from "latest" cid
- doc ID + CID, default 0 depth, start from "target" cid
- doc ID + CID + depth, use depth, start from "target" cid

Unchanged semantics:
- doc ID + depth, use depth, start from "latest" cid

Technically, there is also an optimization where we no longer use the `HeadFetcher` in the commit queries if a `CID` is specified.

## Tasks
- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

(*replace*) Describe the tests performed to verify the changes. Provide instructions to reproduce them.

Specify the platform(s) on which this was tested:
- *(modify the list accordingly*)
- Ubuntu (WSL2)

### CODE REVIEW

File: tests/integration/query/commits/with_doc_id_cid_test.go [hunk 1]
```diff
@@ -70,14 +71,15 @@ func TestQueryCommitsWithDocIDAndCidForDifferentDocWithUpdate(t *testing.T) {
 				Request: ` {
 						commits(
 							docID: "bae-not-this-doc",
-							cid: "bafybeica4js2abwqjjrz7dcialbortbz32uxp7ufxu7yljbwvmhjqqxzny"
+							cid: "bafyreiale6qsjc7qewod3c6h2odwamfwcf7vt4zlqtw7ldcm57xdkgxja4"
```
Comment (jsimnz) [inline tests/integration/query/commits/with_doc_id_cid_test.go:74]: just highlighting this for reviewers. This isnt required by the new changes to the commit query semantics. Its actually fixing a unconsequential bug in using the incorrect `CID` for the goal of the test. The test wanted to test field IDs, but the original `CID` was a composite `CID`.

File: internal/planner/commit.go [hunk 2]
```diff
@@ -240,11 +275,13 @@ func (n *dagScanNode) Next() (bool, error) {
...
-		// match, keep searching.
-		return n.Next()
-	}
+	// // If a specific cid has been requested
+	// // 1) Depth is undefined: then we assume lastestCommit semantics (ie: depth 1)
+	// // 2) Depth is defined,
+	// if n.commitSelect.Cid.HasValue() &&
+	// (currentCid.String() != n.commitSelect.Cid.Value() ||  {
+	// 	return n.Next()
+	// }
```
Comment (fredcarle) [inline internal/planner/commit.go:284]: todo: Please remove this code if no longer necessary.

File: tests/integration/query/latest_commits/simple_test.go [hunk 3]
```diff
@@ -20,7 +20,7 @@ import (
 // desired behaviour (should return all latest commits).
 func TestQueryLatestCommits(t *testing.T) {
 	test := testUtils.TestCase{
-		Description: "Simple latest commits query",
+		Description: "Simple latest commits querys",
```
Comment (fredcarle) [inline tests/integration/query/latest_commits/simple_test.go:23]: typo: queries

**Review by fredcarle — APPROVED** [review]
LGTM. Just one minor todo and a typo.

File: tests/integration/query/latest_commits/simple_test.go [hunk 4]
```diff
@@ -20,7 +20,7 @@ import (
 // desired behaviour (should return all latest commits).
 func TestQueryLatestCommits(t *testing.T) {
 	test := testUtils.TestCase{
-		Description: "Simple latest commits query",
+		Description: "Simple latest commits queries",
```
Comment (shahzadlone) [inline tests/integration/query/latest_commits/simple_test.go:23]: question: why is this plural now? I see only one query request in the test. Also then test name itself has only `Query` in it.

**Review by shahzadlone — APPROVED** [review]
LGTM! one question

File: tests/integration/query/latest_commits/simple_test.go (hunk 4 above)
Comment (jsimnz) [reply tests/integration/query/latest_commits/simple_test.go]: honestly, fantastic question 🙃. I just saw fred suggestion and went with it. Im thinking now that the `s` was there accidentally from me trying to press `ctrl+s` to save at some point and not registering the `ctrl`

Comment (fredcarle) [reply tests/integration/query/latest_commits/simple_test.go]: I assumed John was meaning to make it plural because there were multiple queries in the test (Git change was not showing the full test and just took it for granted)

The assumption cascade is strong with this one... lol

Comment (shahzadlone) [reply tests/integration/query/latest_commits/simple_test.go]: Lol 😆 I looked at it three times, thinking am I missing something or tripping.

File: docs/data_format_changes/i3477-version-query-consistency.md [hunk 5]
```diff
@@ -0,0 +1,2 @@
+# Consistent version query semantics
+Updated semantics for commit/version/time-travel queries when using both DocID and CID.
```
Comment (AndrewSisley) [inline docs/data_format_changes/i3477-version-query-consistency.md:2]: todo: There is no data breaking change in this PR, if the change detector failed it is because the integration test definitions were changed, not the data on disk.  Please change the wording to reflect this.
