### PR TITLE
fix: Ensure no ACP doc check when action is node specific

### LINKED ISSUE #3386: `checkAccessOfDocWithACP` should not have to do an ACP lookup it the access is done by the node itself

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #3386 

## Description

This PR resolve the issue where re-adding docs to the p2p tropics on startup resulted in checking doc access. If we know the operation is node specific, meaning it is not to be returned to a client, then we don't need to check access through the ACP engine.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Manual startup test.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/db/p2p_replicator.go [hunk 1]
```diff
@@ -156,6 +157,8 @@ func (db *db) getDocsHeads(
 		}
 		defer txn.Discard(ctx)
 		ctx = SetContextTxn(ctx, txn)
+		// This is a node specific action which means the actor is the node itself.
+		ctx = identity.WithContext(ctx, db.nodeIdentity)
```
Comment (AndrewSisley) [inline internal/db/p2p_replicator.go:161]: nitpick: I don't think this function can actually guarantee that this comment is actually true, it would be better to do this in `SetReplicator` immediately after creating the ctx.  Or remove teh ctx param and create the `context.Background()` here.

**Review by AndrewSisley — APPROVED** [review]
LGTM, good job tracking this down.

**Review by shahzadlone — APPROVED** [review]
LGTM

File: internal/db/p2p_replicator.go (hunk 1 above)
Comment (fredcarle) [reply internal/db/p2p_replicator.go:161]: It currently is guaranteed as only `SetReplicator` calls it and the action of getting the doc heads here is used only for the purpose of a node specific action.

Comment (fredcarle) [reply internal/db/p2p_replicator.go]: moved it to `SetReplicator`.
