### PR TITLE
fix: Add missing directive definitions

### LINKED ISSUE #2312: Missing directive definitions in GQL schema
**Describe the problem**
There are various directives that aren't defined within the GQL schema. They do still get parsed, but the directive definition should exist on the GQL schema.

Specific directives:
- @primary
- @relation

We can see all the directives correctly defined in `request/graphql/schema/types.go` with their various `gql.NewDirective` call but they don't get registered into the `defaultDirectivesType()` function https://github.com/sourcenetwork/defradb/blob/c117d84c11cb9f80fababad75cc8286bd0113e74/request/graphql/schema/manager.go#L112

Additionally, the `@crdt` directive isn't defined at all, it only exists within the AST parsing code of fieldsFromAST function https://github.com/sourcenetwork/defradb/blob/c117d84c11cb9f80fababad75cc8286bd0113e74/request/graphql/schema/collection.go#L370

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2312 

## Description

This PR adds the missing directive definitions (`@crdt`, `@primary`, `@relation`) to GraphQL

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

tested in GraphQL client

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: request/graphql/schema/types/types.go [hunk 1]
```diff
@@ -127,6 +130,20 @@ var (
 		},
 	})
 
+	// CRDTFieldDirective @crdt is used to define the CRDT type of a field
+	CRDTFieldDirective *gql.Directive = gql.NewDirective(gql.DirectiveConfig{
+		Name:        CRDTDirectiveLabel,
+		Description: crdtDirectiveDescription,
+		Args: gql.FieldConfigArgument{
+			CRDTDirectivePropType: &gql.ArgumentConfig{
+				Type: gql.String,
```
Comment (nasdf) [inline request/graphql/schema/types/types.go:139]: question: Would it be possible to make this an enum type that consists of all of our supported CRDT types?

Comment (fredcarle) [reply request/graphql/schema/types/types.go]: Made the change to enum. Let me know what you think.

**Review by shahzadlone — APPROVED** [review]
LGTM, just a non-blocking thought.

thought: I know `Index*` directives were there before, but do we want to somehow separate the Schema Directives from the Operation Directives (on Request/Query).

 For example `@explain` is not a Schema Directive.

**Comment by fredcarle** [comment]
> thought: I know `Index*` directives were there before, but do we want to somehow separate the Schema Directives from the Operation Directives (on Request/Query).
> 
> For example `@explain` is not a Schema Directive.

I think it's worth looking into it. But in a different PR :)
