### PR TITLE
fix: Use node representation for Block

### LINKED ISSUE #2745: `Block` node representation should use representation form.

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2745

## Description

This PR ensures that the node being passed to the link system is in it's representation form. This will allow the use of optional fields.

Node that the 2 added `block` unit tests are there to cover when the optional `isEncrypted` field will be added to `Block` ipld schema.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/core/block/block.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ import (
 // Schema is the IPLD schema type that represents a `Block`.
 var (
 	Schema          schema.Type
-	SchemaPrototype schema.TypedPrototype
+	SchemaPrototype ipld.NodePrototype
```
Comment (islamaliev) [inline internal/core/block/block.go:33]: question: I wonder where this `ipld` coming from. I don't see any import that ends with "ipld"

**Review by islamaliev — APPROVED** [review]
Looks great. Thanks for a quick fix

File: internal/core/block/block.go (hunk 1 above)
Comment (fredcarle) [reply internal/core/block/block.go:33]: `go-ipld-prime` is the package 🙂

**Review by nasdf — APPROVED** [review]
LGTM.
