### PR TITLE
fix: Improve P2P event handling

### LINKED ISSUE #1334: Flaky Test - TestP2PWithSingleDocumentSingleUpdateDoesNotSyncToNonPeerNode
**Describe the problem**
Another Flaky Test
```
...
✓  tests/integration/query/one_to_one_to_one (6.227s)
✖  tests/integration/net/state/simple/peer (27.161s) (-test.shuffle 1681310440125240211)
✓  tests/integration/query/latest_commits (13.868s)
...

=== Failed
=== FAIL: tests/integration/net/state/simple/peer TestP2PWithSingleDocumentSingleUpdateDoesNotSyncToNonPeerNode (unknown)
2023-04-12T10:40:54.985-0400, INFO, defra.tests.integration, , {"Database": "badger-in-memory"}
2023-04-12T10:40:55.165-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T10:40:55.402-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWBfE8GkNA8NeCX2uhfv6HSPnTutDcxTvFhPf25Vu9pVVQ", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T10:40:55.474-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T10:40:55.698-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T10:40:56.011-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWRz1tb7dnfWB8xT4xsJHtucjvkQDdPSyuRfYtnZ4tG4WR", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T10:40:56.032-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T10:40:56.087-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T10:40:56.195-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWNW8p48WZC2vckqnvxBzpzypvSRedSgYcjq2yH8R87ZiJ", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T10:40:56.220-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T10:40:58.466-0400, INFO, defra.tests.integration, Parsing bootstrap peers, {"Peers": "/ip4/172.27.231.49/tcp/43349/p2p/12D3KooWRz1tb7dnfWB8xT4xsJHtucjvkQDdPSyuRfYtnZ4tG4WR"}
2023-04-12T10:40:58.489-0400, INFO, defra.tests.integration, Bootstrapping with peers, {"Addresses": [{"ID":"12D3KooWRz1tb7dnfWB8xT4xsJHtucjvkQDdPSyuRfYtnZ4tG4WR","Addrs":["/ip4/172.27.231.49/tcp/43349"]}]}
2023-04-12T10:40:58.967-0400, INFO, defra.node, Connected, {"Peer ID": "12D3KooWRz1tb7dnfWB8xT4xsJHtucjvkQDdPSyuRfYtnZ4tG4WR"}
2023-04-12T10:40:58.994-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWBfE8GkNA8NeCX2uhfv6HSPnTutDcxTvFhPf25Vu9pVVQ", "Topic": "bae-52b9170d-b77a-5887-b877-cbdbb99b009f", "Message": "JOINED"}
2023-04-12T10:40:59.011-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWRz1tb7dnfWB8xT4xsJHtucjvkQDdPSyuRfYtnZ4tG4WR", "Topic": "bae-52b9170d-b77a-5887-b877-cbdbb99b009f", "Message": "JOINED"}

DONE 1309 tests, 1 failure in 89.464s
make: *** [Makefile:146: test] Error 1

```

**To Reproduce**
```
make test
```

**Expected behavior**
to not fail

### LINKED ISSUE #1335: Flaky Test - TestP2PSubscribeAddSingleAndRemoveNone
**Describe the problem**
Flakey subscribe test.

**To Reproduce**
`make test`

**Expected behavior**
Not be flaky

**Platform**

latest commit on develop:
`bbe8408a (HEAD -> develop, origin/develop) 2 hours ago fix: API address parameter validation (#1311)
`

**Additional context**
```
...
✖  tests/integration/net/state/simple/peer/subscribe (45.248s) (-test.shuffle 1681310110272527126)
...

=== Failed
=== FAIL: tests/integration/net/state/simple/peer/subscribe TestP2PSubscribeAddSingleAndRemoveNone (unknown)
2023-04-12T10:35:46.157-0400, INFO, defra.tests.integration, , {"Database": "badger-in-memory"}

DONE 1312 tests, 1 failure in 125.214s
make: *** [Makefile:146: test] Error 1
```

### LINKED ISSUE #1336: Flaky Test - TestP2PWithMultipleDocumentUpdatesPerNode
**Describe the problem**
Flakey test.

**To Reproduce**
`make test`

**Expected behavior**
Not be flaky

**Platform**

latest commit on develop:
`bbe8408a (HEAD -> develop, origin/develop) 2 hours ago fix: API address parameter validation (#1311)
`

**Additional context**
```
...

=== Failed
=== FAIL: datastore/badger/v3 TestGetSizeOperationWithStoreClosed (unknown)

=== FAIL: tests/integration/net/state/simple/peer TestP2PWithMultipleDocumentUpdatesPerNode (unknown)
2023-04-12T10:58:57.907-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/subscriber_notifee.go:108     could not check peerstore for protocol support: err: datastore closed
2023-04-12T10:58:57.908-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/subscriber_notifee.go:108     could not check peerstore for protocol support: err: datastore closed
2023-04-12T10:58:57.908-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/subscriber_notifee.go:108     could not check peerstore for protocol support: err: datastore closed
2023-04-12T10:58:57.910-0400    ERROR   peerstore/ds    pstoreds/keybook.go:63  error when fetching pubkey from datastore for peer 12D3KooWEyKsi421kF382prWWJt8Vzz7nCTb982jTwthT3aoChwG: datastore closed

2023-04-12T10:58:57.911-0400    ERROR   peerstore/ds    pstoreds/keybook.go:81  error while updating pubkey in datastore for peer 12D3KooWEyKsi421kF382prWWJt8Vzz7nCTb982jTwthT3aoChwG: datastore closed

2023-04-12T10:58:57.915-0400, INFO, defra.tests.integration, , {"Database": "badger-in-memory"}
2023-04-12T10:58:57.981-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T10:58:58.076-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWFE4XEa4uUAEchG5kRdWtZjZFcjmP6aZ3otNuMHNc3rVT", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T10:58:58.081-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T10:58:58.106-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T10:58:58.326-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWExFEg7GVEawm61f2ajdXMCdQh8aXCqL4ZhnYJaopc2Ab", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T10:58:58.384-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T10:58:58.557-0400, INFO, defra.tests.integration, Parsing bootstrap peers, {"Peers": "/ip4/172.27.231.49/tcp/40643/p2p/12D3KooWExFEg7GVEawm61f2ajdXMCdQh8aXCqL4ZhnYJaopc2Ab"}
2023-04-12T10:58:58.558-0400, INFO, defra.tests.integration, Bootstrapping with peers, {"Addresses": [{"ID":"12D3KooWExFEg7GVEawm61f2ajdXMCdQh8aXCqL4ZhnYJaopc2Ab","Addrs":["/ip4/172.27.231.49/tcp/40643"]}]}
2023-04-12T10:58:58.684-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWFE4XEa4uUAEchG5kRdWtZjZFcjmP6aZ3otNuMHNc3rVT", "Topic": "bae-52b9170d-b77a-5887-b877-cbdbb99b009f", "Message": "JOINED"}
2023-04-12T10:58:58.689-0400, INFO, defra.node, Connected, {"Peer ID": "12D3KooWExFEg7GVEawm61f2ajdXMCdQh8aXCqL4ZhnYJaopc2Ab"}
2023-04-12T10:58:58.794-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeibikyvp4kiwgvbdm7skhsnglvksquih6suj6adxsryiwxfol7rhky", "CID": "bafybeicp7jguntelc4svy2iqty65vkp47iqrkegplwlhtq3lmajnmlqrji", "Height": 2}
2023-04-12T10:58:59.146-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeih45xhodaynmvu3pehetcjkcjvs5fgnm2z454yzztce6jdzn2xw4u", "CID": "bafybeigehyhrm5igewfcohbasz7kp3cyqu65jxfnvigcinpkbe2empfyta", "Height": 2}
2023-04-12T10:58:59.151-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeicp7jguntelc4svy2iqty65vkp47iqrkegplwlhtq3lmajnmlqrji", "CID": "bafybeifhvkbnvjrlq54ccrn2utyni7fsj5b2y67gksludgsyyqu3ojf2ge", "Height": 3}
2023-04-12T10:58:59.153-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeigehyhrm5igewfcohbasz7kp3cyqu65jxfnvigcinpkbe2empfyta", "CID": "bafybeigfuvr64slsxmkppkb5h7czhzfqpvlavsg3fljsste4hplk2m6u7a", "Height": 3}
2023-04-12T10:58:59.155-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeifhvkbnvjrlq54ccrn2utyni7fsj5b2y67gksludgsyyqu3ojf2ge", "CID": "bafybeig3tjzvvku7ejjuzczl4mkli32fzlnelgtotw2qhzwfwgljrtkun4", "Height": 4}
2023-04-12T10:58:59.162-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWExFEg7GVEawm61f2ajdXMCdQh8aXCqL4ZhnYJaopc2Ab", "Topic": "bae-52b9170d-b77a-5887-b877-cbdbb99b009f", "Message": "JOINED"}
2023-04-12T10:58:59.202-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeigfuvr64slsxmkppkb5h7czhzfqpvlavsg3fljsste4hplk2m6u7a", "CID": "bafybeiec3n3mzmqj4j3opvzzfqqbfq6ll3442mycwc2vhnvne7ia75hzse", "Height": 4}
2023-04-12T10:58:59.209-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeibikyvp4kiwgvbdm7skhsnglvksquih6suj6adxsryiwxfol7rhky", "CID": "bafybeiaiwrezgutkyabi3pazplwefat52oq52v5byqb64kqvnxyt7lsqom", "Height": 2}
2023-04-12T10:58:59.211-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeih45xhodaynmvu3pehetcjkcjvs5fgnm2z454yzztce6jdzn2xw4u", "CID": "bafybeid2dcrc7342ownxdudn57luuxud3kj74joezbof4lrdap4ancbq64", "Height": 2}
2023-04-12T10:58:59.348-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeiaiwrezgutkyabi3pazplwefat52oq52v5byqb64kqvnxyt7lsqom", "CID": "bafybeia3hiix2iotxxzlpq7i4uzmwx3oyxwffgv4q43bn246pgy4eackvy", "Height": 3}
2023-04-12T10:58:59.397-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeid2dcrc7342ownxdudn57luuxud3kj74joezbof4lrdap4ancbq64", "CID": "bafybeiaqutvj53ewhqrwufmkftqylos2tg5v4nloyr5ha4syfyrlszs3q4", "Height": 3}
2023-04-12T10:58:59.400-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeia3hiix2iotxxzlpq7i4uzmwx3oyxwffgv4q43bn246pgy4eackvy", "CID": "bafybeibawlibuovkdtxjf6s3e7mg4jaob5w25ffdb7gu3q6svapj5yupay", "Height": 4}
2023-04-12T10:58:59.402-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeiaqutvj53ewhqrwufmkftqylos2tg5v4nloyr5ha4syfyrlszs3q4", "CID": "bafybeicxzwspmu5rsttyhxy3xtroxi34askh7v2obkz6bljezp3emohof4", "Height": 4}
2023-04-12T10:58:59.512-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeibikyvp4kiwgvbdm7skhsnglvksquih6suj6adxsryiwxfol7rhky", "CID": "bafybeicp7jguntelc4svy2iqty65vkp47iqrkegplwlhtq3lmajnmlqrji", "Height": 2}
2023-04-12T10:58:59.585-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeih45xhodaynmvu3pehetcjkcjvs5fgnm2z454yzztce6jdzn2xw4u", "CID": "bafybeigehyhrm5igewfcohbasz7kp3cyqu65jxfnvigcinpkbe2empfyta", "Height": 2}
2023-04-12T10:58:59.918-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeiaiwrezgutkyabi3pazplwefat52oq52v5byqb64kqvnxyt7lsqom", "CID": "bafybeia3hiix2iotxxzlpq7i4uzmwx3oyxwffgv4q43bn246pgy4eackvy", "Height": 3}
2023-04-12T10:59:00.051-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeid2dcrc7342ownxdudn57luuxud3kj74joezbof4lrdap4ancbq64", "CID": "bafybeiaqutvj53ewhqrwufmkftqylos2tg5v4nloyr5ha4syfyrlszs3q4", "Height": 3}
2023-04-12T10:59:00.125-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeiaiwrezgutkyabi3pazplwefat52oq52v5byqb64kqvnxyt7lsqom", "CID": "bafybeia3hiix2iotxxzlpq7i4uzmwx3oyxwffgv4q43bn246pgy4eackvy", "Height": 3}
2023-04-12T10:59:00.127-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeid2dcrc7342ownxdudn57luuxud3kj74joezbof4lrdap4ancbq64", "CID": "bafybeiaqutvj53ewhqrwufmkftqylos2tg5v4nloyr5ha4syfyrlszs3q4", "Height": 3}
2023-04-12T10:59:00.193-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeicp7jguntelc4svy2iqty65vkp47iqrkegplwlhtq3lmajnmlqrji", "CID": "bafybeifhvkbnvjrlq54ccrn2utyni7fsj5b2y67gksludgsyyqu3ojf2ge", "Height": 3}
    p2p.go:476:
                Error Trace:    /home/shahzad/~~/defradb/tests/integration/p2p.go:476
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:396
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:289
                                                        /home/shahzad/~~/defradb/tests/integration/net/state/simple/peer/with_update_test.go:422
                Error:          timeout occured while waiting for data stream
                Test:           TestP2PWithMultipleDocumentUpdatesPerNode

DONE 1295 tests, 2 failures in 147.509s
make: *** [Makefile:146: test] Error 1

```

### LINKED ISSUE #1337: Flaky Test - TestP2PCreateWithP2PCollection
**Describe the problem**
Flakey test.

**To Reproduce**
`make test`

**Expected behavior**
Not be flaky

**Platform**

latest commit on develop:
`bbe8408a (HEAD -> develop, origin/develop) 2 hours ago fix: API address parameter validation (#1311)
`

**Additional context**
```
=== Failed
=== FAIL: tests/integration/net/state/simple/peer TestP2PCreateWithP2PCollection (unknown)
2023-04-12T11:14:24.553-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/dht.go:655    failed to validate if peer is a DHT peer        {"peer": "12D3KooWHu4FQvnGaQmjQL7nXjcmUL6KxuXkkYRjSgcMjeg9ddEp", "error": "datastore closed", "errorVerbose": "datastore closed. Stack: /home/shahzad/~~/defradb/datastore/memory/errors.go:20 (0x1c62407)\n\tinit: ErrClosed      = errors.New(\"datastore closed\")\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6329 (0x482566)\n\tdoInit: f()\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:233 (0x474db3)\n\tmain: doInit(&main_inittask)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594 (0x4a90a1)\n\tgoexit: BYTE\t$0x90\t// NOP\n"}
2023-04-12T11:14:24.555-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/dht.go:655    failed to validate if peer is a DHT peer        {"peer": "12D3KooWDFfYcgkGi3zkk5NjBCthbxN9Bs2GzmzdqLnRQ4TJfZjm", "error": "datastore closed", "errorVerbose": "datastore closed. Stack: /home/shahzad/~~/defradb/datastore/memory/errors.go:20 (0x1c62407)\n\tinit: ErrClosed      = errors.New(\"datastore closed\")\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6329 (0x482566)\n\tdoInit: f()\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:233 (0x474db3)\n\tmain: doInit(&main_inittask)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594 (0x4a90a1)\n\tgoexit: BYTE\t$0x90\t// NOP\n"}
2023-04-12T11:14:24.557-0400, INFO, defra.tests.integration, , {"Database": "badger-in-memory"}
2023-04-12T11:14:24.556-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/dht.go:655    failed to validate if peer is a DHT peer        {"peer": "12D3KooWHu4FQvnGaQmjQL7nXjcmUL6KxuXkkYRjSgcMjeg9ddEp", "error": "datastore closed", "errorVerbose": "datastore closed. Stack: /home/shahzad/~~/defradb/datastore/memory/errors.go:20 (0x1c62407)\n\tinit: ErrClosed      = errors.New(\"datastore closed\")\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6329 (0x482566)\n\tdoInit: f()\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:233 (0x474db3)\n\tmain: doInit(&main_inittask)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594 (0x4a90a1)\n\tgoexit: BYTE\t$0x90\t// NOP\n"}
2023-04-12T11:14:24.638-0400    ERROR   peerstore/ds    pstoreds/keybook.go:63  error when fetching pubkey from datastore for peer 12D3KooWDFfYcgkGi3zkk5NjBCthbxN9Bs2GzmzdqLnRQ4TJfZjm: datastore closed

2023-04-12T11:14:24.648-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/subscriber_notifee.go:108     could not check peerstore for protocol support: err: datastore closed
2023-04-12T11:14:24.649-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/subscriber_notifee.go:108     could not check peerstore for protocol support: err: datastore closed
2023-04-12T11:14:27.337-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T11:14:27.755-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWSQvB6FLfxYoW3tGCEuzL3NhgkyL7hVFMqW2KbZgyocKe", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T11:14:27.781-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T11:14:28.876-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T11:14:29.578-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWKk5WKYSb6ZkDCKjzynZDYV7EZ9CLVHmeDNFimF745okU", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T11:14:32.198-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T11:14:32.919-0400, INFO, defra.tests.integration, Parsing bootstrap peers, {"Peers": "/ip4/172.27.231.49/tcp/33297/p2p/12D3KooWSQvB6FLfxYoW3tGCEuzL3NhgkyL7hVFMqW2KbZgyocKe"}
2023-04-12T11:14:32.923-0400, INFO, defra.tests.integration, Bootstrapping with peers, {"Addresses": [{"ID":"12D3KooWSQvB6FLfxYoW3tGCEuzL3NhgkyL7hVFMqW2KbZgyocKe","Addrs":["/ip4/172.27.231.49/tcp/33297"]}]}

DONE 1306 tests, 1 failure in 131.185s
make: *** [Makefile:146: test] Error 1
```

### LINKED ISSUE #1338: Flaky - TestP2PWithMultipleDocumentsWithUpdateAndDeleteBeforeConnectSingleDeleteWithShowDeleted
**Describe the problem**
Flakey test.

**To Reproduce**
`make test`

**Expected behavior**
Not be flaky

**Platform**

latest commit on develop:
`bbe8408a (HEAD -> develop, origin/develop) 2 hours ago fix: API address parameter validation (#1311)
`

**Additional context**
```
=== Failed
=== FAIL: tests/integration/net/state/simple/peer TestP2PWithMultipleDocumentsWithUpdateAndDeleteBeforeConnectSingleDeleteWithShowDeleted (11.35s)
2023-04-12T11:22:09.996-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/dht.go:655    failed to validate if peer is a DHT peer        {"peer": "12D3KooWQ8jR6HdUsPYZ3wPKs9SpaYT2giX6Hx2dsDfjm4DsVHAq", "error": "datastore closed", "errorVerbose": "datastore closed. Stack: /home/shahzad/~~/defradb/datastore/memory/errors.go:20 (0x1c62407)\n\tinit: ErrClosed      = errors.New(\"datastore closed\")\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6329 (0x482566)\n\tdoInit: f()\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:233 (0x474db3)\n\tmain: doInit(&main_inittask)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594 (0x4a90a1)\n\tgoexit: BYTE\t$0x90\t// NOP\n"}
2023-04-12T11:22:09.996-0400, INFO, defra.tests.integration, , {"Database": "badger-in-memory"}
2023-04-12T11:22:10.003-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/dht.go:655    failed to validate if peer is a DHT peer        {"peer": "12D3KooWEStTWTjAoonnsKR2mPRNRhFyv6JJL5UPhM4Z1WTuBdrg", "error": "datastore closed", "errorVerbose": "datastore closed. Stack: /home/shahzad/~~/defradb/datastore/memory/errors.go:20 (0x1c62407)\n\tinit: ErrClosed      = errors.New(\"datastore closed\")\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6329 (0x482566)\n\tdoInit: f()\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:233 (0x474db3)\n\tmain: doInit(&main_inittask)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594 (0x4a90a1)\n\tgoexit: BYTE\t$0x90\t// NOP\n"}
2023-04-12T11:22:10.029-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T11:22:10.125-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWHFDJ4fiDs5yoDvQgmLhN5NZDRJXLupiPPsHPTKQTLp2Z", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T11:22:10.137-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T11:22:10.188-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T11:22:10.252-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T11:22:10.264-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T11:22:10.330-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeiaggvx7n2alz7aaronjwebcbrnh4ajnm7vkd2c7plotg5czill54m", "CID": "bafybeif5apzvwrk5jnvtbjmruq6uqw2ujvsdo424wtauxanekzgushp4y4", "Height": 2}
2023-04-12T11:22:10.331-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeieibjbtlp633yis27ycaquu3bx7ywxmij5apcylm4bsa5xbignwaa", "CID": "bafybeigjsmbmbs5oo6623sedrczuxxz4k57cliupa4noxxt47zi2mx46my", "Height": 2}
2023-04-12T11:22:10.334-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeif5apzvwrk5jnvtbjmruq6uqw2ujvsdo424wtauxanekzgushp4y4", "CID": "bafybeiaf4dgpsrwwwuew4avlqxgadhttcgbirg6m44ebkwofrbb366yvnu", "Height": 3}
2023-04-12T11:22:10.335-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeigjsmbmbs5oo6623sedrczuxxz4k57cliupa4noxxt47zi2mx46my", "CID": "bafybeidxn3ctwtti4e542icqonlua6llh74qqblgbllyvmyxvnkm77skcu", "Height": 3}
2023-04-12T11:22:10.339-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeidxn3ctwtti4e542icqonlua6llh74qqblgbllyvmyxvnkm77skcu", "CID": "bafybeiemznzwy4rehry372qdckm3ko5sjib4q22rhg5ij6k43qhlckoycm", "Height": 4}
2023-04-12T11:22:10.340-0400, INFO, defra.tests.integration, Parsing bootstrap peers, {"Peers": "/ip4/172.27.231.49/tcp/44627/p2p/12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw"}
2023-04-12T11:22:10.340-0400, INFO, defra.tests.integration, Bootstrapping with peers, {"Addresses": [{"ID":"12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw","Addrs":["/ip4/172.27.231.49/tcp/44627"]}]}
2023-04-12T11:22:10.376-0400, INFO, defra.node, Connected, {"Peer ID": "12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw"}
2023-04-12T11:22:10.381-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWHFDJ4fiDs5yoDvQgmLhN5NZDRJXLupiPPsHPTKQTLp2Z", "Topic": "bae-b4a08ad3-8970-5511-8048-ba1b873008dc", "Message": "JOINED"}
2023-04-12T11:22:10.381-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWHFDJ4fiDs5yoDvQgmLhN5NZDRJXLupiPPsHPTKQTLp2Z", "Topic": "bae-e45fa288-797b-5b12-b08a-f673f70b7ee5", "Message": "JOINED"}
2023-04-12T11:22:10.390-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw", "Topic": "bae-b4a08ad3-8970-5511-8048-ba1b873008dc", "Message": "JOINED"}
2023-04-12T11:22:10.391-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw", "Topic": "bae-e45fa288-797b-5b12-b08a-f673f70b7ee5", "Message": "JOINED"}
2023-04-12T11:22:10.478-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeiaggvx7n2alz7aaronjwebcbrnh4ajnm7vkd2c7plotg5czill54m", "CID": "bafybeiau3szayl6r2ad62ylte7jkcsxndvx3z7gth4p55wgi5eihlkehzu", "Height": 2}
2023-04-12T11:22:10.479-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeieibjbtlp633yis27ycaquu3bx7ywxmij5apcylm4bsa5xbignwaa", "CID": "bafybeigr5ehntqvbopvumjaaxbl7j2zcocijsjydzkn32i7b55vsrdblne", "Height": 2}
2023-04-12T11:22:10.503-0400, INFO, defra.tests.integration, , {"RequestResults": [{"Age":74,"Name":"Andy","_deleted":false},{"Age":62,"Name":"John","_deleted":true}]}
2023-04-12T11:22:10.506-0400, INFO, defra.tests.integration, , {"RequestResults": [{"Age":74,"Name":"Andy","_deleted":false},{"Age":66,"Name":"John","_deleted":false}]}
2023-04-12T11:22:10.508-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWHFDJ4fiDs5yoDvQgmLhN5NZDRJXLupiPPsHPTKQTLp2Z", "Topic": "bae-b4a08ad3-8970-5511-8048-ba1b873008dc", "Message": "LEFT"}
2023-04-12T11:22:10.509-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWHFDJ4fiDs5yoDvQgmLhN5NZDRJXLupiPPsHPTKQTLp2Z", "Topic": "bae-e45fa288-797b-5b12-b08a-f673f70b7ee5", "Message": "LEFT"}
2023-04-12T11:22:10.511-0400, INFO, defra.db, Closing DefraDB process...
2023-04-12T11:22:10.642-0400, INFO, defra.db, Successfully closed running process
2023-04-12T11:22:10.642-0400    ERROR   peerstore/ds    pstoreds/keybook.go:63  error when fetching pubkey from datastore for peer 12D3KooWHFDJ4fiDs5yoDvQgmLhN5NZDRJXLupiPPsHPTKQTLp2Z: datastore closed

2023-04-12T11:22:10.653-0400, INFO, defra.db, Closing DefraDB process...
2023-04-12T11:22:10.663-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/dht.go:655    failed to validate if peer is a DHT peer        {"peer": "12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw", "error": "datastore closed", "errorVerbose": "datastore closed. Stack: /home/shahzad/~~/defradb/datastore/badger/v3/datastore.go:28 (0x1074487)\n\tinit: ErrClosed      = errors.New(\"datastore closed\")\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6329 (0x482566)\n\tdoInit: f()\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:233 (0x474db3)\n\tmain: doInit(&main_inittask)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594 (0x4a90a1)\n\tgoexit: BYTE\t$0x90\t// NOP\n"}
2023-04-12T11:22:10.664-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/subscriber_notifee.go:108     could not check peerstore for protocol support: err: datastore closed
2023-04-12T11:22:10.665-0400    ERROR   peerstore/ds    pstoreds/keybook.go:63  error when fetching pubkey from datastore for peer 12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw: datastore closed

2023-04-12T11:22:10.666-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/subscriber_notifee.go:108     could not check peerstore for protocol support: err: datastore closed
2023-04-12T11:22:10.669-0400    ERROR   peerstore/ds    pstoreds/keybook.go:81  error while updating pubkey in datastore for peer 12D3KooWJWvf29EEKbm49XuvQ4x2LbbWG4BpKweUabgJMALsszcw: datastore closed

2023-04-12T11:22:10.832-0400    ERROR   dht     go-libp2p-kad-dht@v0.21.1/dht.go:655    failed to validate if peer is a DHT peer        {"peer": "12D3KooWHFDJ4fiDs5yoDvQgmLhN5NZDRJXLupiPPsHPTKQTLp2Z", "error": "datastore closed", "errorVerbose": "datastore closed. Stack: /home/shahzad/~~/defradb/datastore/badger/v3/datastore.go:28 (0x1074487)\n\tinit: ErrClosed      = errors.New(\"datastore closed\")\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6329 (0x482566)\n\tdoInit: f()\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:6306 (0x4824b1)\n\tdoInit: doInit(t2)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/proc.go:233 (0x474db3)\n\tmain: doInit(&main_inittask)\n/home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594 (0x4a90a1)\n\tgoexit: BYTE\t$0x90\t// NOP\n"}
2023-04-12T11:22:10.832-0400, INFO, defra.db, Successfully closed running process
2023-04-12T11:22:10.834-0400, INFO, defra.tests.integration, , {"Database": "defra-memory-datastore"}
2023-04-12T11:22:10.836-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T11:22:10.866-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWAYLeSA1z51NqQd1ci639iQZHz3uiBhVFHsr8mfK6i4bM", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T11:22:10.869-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T11:22:10.872-0400, INFO, defra.tests.integration, Starting P2P node, {"P2P address": "/ip4/0.0.0.0/tcp/0"}
2023-04-12T11:22:10.902-0400, INFO, defra.node, Created LibP2P host, {"PeerId": "12D3KooWGyAE6mf3dyDXnqMBVk32WEUvhSNaj3ku58Tdvn38HdE4", "Address": ["/ip4/0.0.0.0/tcp/0"]}
2023-04-12T11:22:10.911-0400, INFO, defra.net, Starting internal broadcaster for pubsub network
2023-04-12T11:22:10.940-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeiaggvx7n2alz7aaronjwebcbrnh4ajnm7vkd2c7plotg5czill54m", "CID": "bafybeif5apzvwrk5jnvtbjmruq6uqw2ujvsdo424wtauxanekzgushp4y4", "Height": 2}
2023-04-12T11:22:10.941-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeieibjbtlp633yis27ycaquu3bx7ywxmij5apcylm4bsa5xbignwaa", "CID": "bafybeigjsmbmbs5oo6623sedrczuxxz4k57cliupa4noxxt47zi2mx46my", "Height": 2}
2023-04-12T11:22:10.942-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeif5apzvwrk5jnvtbjmruq6uqw2ujvsdo424wtauxanekzgushp4y4", "CID": "bafybeiaf4dgpsrwwwuew4avlqxgadhttcgbirg6m44ebkwofrbb366yvnu", "Height": 3}
2023-04-12T11:22:10.943-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeigjsmbmbs5oo6623sedrczuxxz4k57cliupa4noxxt47zi2mx46my", "CID": "bafybeidxn3ctwtti4e542icqonlua6llh74qqblgbllyvmyxvnkm77skcu", "Height": 3}
2023-04-12T11:22:10.945-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeidxn3ctwtti4e542icqonlua6llh74qqblgbllyvmyxvnkm77skcu", "CID": "bafybeiemznzwy4rehry372qdckm3ko5sjib4q22rhg5ij6k43qhlckoycm", "Height": 4}
2023-04-12T11:22:10.945-0400, INFO, defra.tests.integration, Parsing bootstrap peers, {"Peers": "/ip4/172.27.231.49/tcp/37733/p2p/12D3KooWGyAE6mf3dyDXnqMBVk32WEUvhSNaj3ku58Tdvn38HdE4"}
2023-04-12T11:22:10.945-0400, INFO, defra.tests.integration, Bootstrapping with peers, {"Addresses": [{"ID":"12D3KooWGyAE6mf3dyDXnqMBVk32WEUvhSNaj3ku58Tdvn38HdE4","Addrs":["/ip4/172.27.231.49/tcp/37733"]}]}
2023-04-12T11:22:10.997-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWGyAE6mf3dyDXnqMBVk32WEUvhSNaj3ku58Tdvn38HdE4", "Topic": "bae-e45fa288-797b-5b12-b08a-f673f70b7ee5", "Message": "JOINED"}
2023-04-12T11:22:10.997-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWGyAE6mf3dyDXnqMBVk32WEUvhSNaj3ku58Tdvn38HdE4", "Topic": "bae-b4a08ad3-8970-5511-8048-ba1b873008dc", "Message": "JOINED"}
2023-04-12T11:22:10.997-0400, INFO, defra.node, Connected, {"Peer ID": "12D3KooWGyAE6mf3dyDXnqMBVk32WEUvhSNaj3ku58Tdvn38HdE4"}
2023-04-12T11:22:10.998-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWAYLeSA1z51NqQd1ci639iQZHz3uiBhVFHsr8mfK6i4bM", "Topic": "bae-e45fa288-797b-5b12-b08a-f673f70b7ee5", "Message": "JOINED"}
2023-04-12T11:22:10.998-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWAYLeSA1z51NqQd1ci639iQZHz3uiBhVFHsr8mfK6i4bM", "Topic": "bae-b4a08ad3-8970-5511-8048-ba1b873008dc", "Message": "JOINED"}
2023-04-12T11:22:11.034-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeiaggvx7n2alz7aaronjwebcbrnh4ajnm7vkd2c7plotg5czill54m", "CID": "bafybeif5apzvwrk5jnvtbjmruq6uqw2ujvsdo424wtauxanekzgushp4y4", "Height": 2}
2023-04-12T11:22:11.035-0400, INFO, defra.merkleclock, Replacing DAG head, {"Old": "bafybeieibjbtlp633yis27ycaquu3bx7ywxmij5apcylm4bsa5xbignwaa", "CID": "bafybeigjsmbmbs5oo6623sedrczuxxz4k57cliupa4noxxt47zi2mx46my", "Height": 2}
    p2p.go:476:
                Error Trace:    /home/shahzad/~~/defradb/tests/integration/p2p.go:476
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:396
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:289
                                                        /home/shahzad/~~/defradb/tests/integration/net/state/simple/peer/with_delete_test.go:409
                Error:          timeout occured while waiting for data stream
                Test:           TestP2PWithMultipleDocumentsWithUpdateAndDeleteBeforeConnectSingleDeleteWithShowDeleted
    p2p.go:246:
                Error Trace:    /home/shahzad/~~/defradb/tests/integration/p2p.go:246
                                                        /home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594
                Error:          Received unexpected error:
                                waiting for pushlog timed out. Stack: /home/shahzad/~~/defradb/node/node.go:330 (0x1c28bf9)
                                        (*Node).WaitForPushLogByPeerEvent: return errors.New("waiting for pushlog timed out")
                                /home/shahzad/~~/defradb/tests/integration/p2p.go:245 (0x1e13f8e)
                                        connectPeers.func1: err := sourceNode.WaitForPushLogByPeerEvent(targetNode.PeerID())
                                /home/shahzad/.local/bin/go1.19.5/src/runtime/asm_amd64.s:1594 (0x4a90a1)
                                        goexit: BYTE    $0x90   // NOP
                Test:           TestP2PWithMultipleDocumentsWithUpdateAndDeleteBeforeConnectSingleDeleteWithShowDeleted
2023-04-12T11:22:21.184-0400, INFO, defra.tests.integration, , {"RequestResults": [{"Age":74,"Name":"Andy","_deleted":false},{"Age":62,"Name":"John","_deleted":true}]}
2023-04-12T11:22:21.210-0400, INFO, defra.tests.integration, , {"RequestResults": [{"Age":74,"Name":"Andy","_deleted":false},{"Age":62,"Name":"John","_deleted":true}]}
    utils2.go:1121:
                Error Trace:    /home/shahzad/~~/defradb/tests/integration/utils2.go:1121
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:933
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:390
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:289
                                                        /home/shahzad/~~/defradb/tests/integration/net/state/simple/peer/with_delete_test.go:409
                Error:          Not equal:
                                expected: false
                                actual  : true
                Test:           TestP2PWithMultipleDocumentsWithUpdateAndDeleteBeforeConnectSingleDeleteWithShowDeleted
                Messages:       node: 0, doc: 1
    utils2.go:1121:
                Error Trace:    /home/shahzad/~~/defradb/tests/integration/utils2.go:1121
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:933
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:390
                                                        /home/shahzad/~~/defradb/tests/integration/utils2.go:289
                                                        /home/shahzad/~~/defradb/tests/integration/net/state/simple/peer/with_delete_test.go:409
                Error:          Not equal:
                                expected: 0x42
                                actual  : 0x3e
                Test:           TestP2PWithMultipleDocumentsWithUpdateAndDeleteBeforeConnectSingleDeleteWithShowDeleted
                Messages:       node: 0, doc: 1
2023-04-12T11:22:21.260-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWAYLeSA1z51NqQd1ci639iQZHz3uiBhVFHsr8mfK6i4bM", "Topic": "bae-e45fa288-797b-5b12-b08a-f673f70b7ee5", "Message": "LEFT"}
2023-04-12T11:22:21.283-0400, INFO, defra.net, Received new pubsub event, {"SenderId": "12D3KooWAYLeSA1z51NqQd1ci639iQZHz3uiBhVFHsr8mfK6i4bM", "Topic": "bae-b4a08ad3-8970-5511-8048-ba1b873008dc", "Message": "LEFT"}
2023-04-12T11:22:21.323-0400, INFO, defra.db, Closing DefraDB process...
2023-04-12T11:22:21.323-0400, INFO, defra.db, Successfully closed running process
2023-04-12T11:22:21.338-0400, INFO, defra.db, Closing DefraDB process...
2023-04-12T11:22:21.339-0400, INFO, defra.db, Successfully closed running process

```

### LINKED ISSUE #1339: Increase p2p test framework sleep slightly
Will increase them slightly to see if it feels like it helps the CI.

### LINKED ISSUE #1375: Order of pushing to replicator and subscribing to topic can cause sync issues in P2P tests.

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #1334
Resolves #1335 
Resolves #1336
Resolves #1337
Resolves #1338
Resolves #1375

## Description

This PR seems to have fixed all known flakyness from the P2P integration tests. It does so at different levels:
1. We prevent pre peer connection and pre replicator configuration actions from having their events received by the wait function by adding a 100ms sleep call pre setup.
2. We ensure that the wait go routines are ready before continuing with the actions.
3. We add a docQueue to the PushLog function so that we don't handle multiple updates to the same document at once. This helps avoid unnecessary transaction conflicts. This would also sometimes cause the PushLog function to hang and the RPC call hitting a timeout.
4. We handle pubsub topic subscriptions a little better by subscribing only to the collection **OR** the documents. Subscribing to documents and the collection would cause double the event handling.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Integration test (a 6 hour run without errors)

Specify the platform(s) on which this was tested:
- Github CI
- MacOS

### CODE REVIEW

File: tests/integration/p2p.go [hunk 1]
```diff
@@ -140,6 +140,9 @@ func connectPeers(
 	nodes []*node.Node,
 	addresses []string,
 ) chan struct{} {
+	// If we have some database actions prior to connecting the peers, we want to ensure that they had time to
+	// complete before we connect. Otherwise we might wrongly catch them in our wait function.
+	time.Sleep(100 * time.Millisecond)
```
Comment (AndrewSisley) [inline tests/integration/p2p.go:145]: praise: Nice spot - I didn't notice this looking through your wip branch earlier :)

File: net/peer.go [hunk 2]
```diff
@@ -629,10 +627,16 @@ func (p *Peer) handleDocCreateLog(evt events.Update) error {
 		return errors.Wrap("failed to get DocKey from broadcast message", err)
 	}
 
+	// We need to register the document before pushing to the replicators if we want to
+	// ensure that we have subscribed to the topic.
+	err = p.RegisterNewDocument(p.ctx, dockey, evt.Cid, evt.Block, evt.SchemaID)
```
Comment (AndrewSisley) [inline net/peer.go:632]: question: This change is not noted in the description, is it still needed, or is this left here accidentally?

File: net/peer.go [hunk 3]
```diff
@@ -804,6 +808,30 @@ func (p *Peer) AddP2PCollections(collections []string) error {
 		addedTopics = append(addedTopics, col)
 	}
 
+	// If adding the collection topics succeeds, we remove the collections' documents
+	// from the pubsub topics to avoid receiving duplicate events.
+	for _, col := range collections {
```
Comment (AndrewSisley) [inline net/peer.go:813]: thought: This is potentially very expensive - how long do you expect this code to live?  It might be worth noting this in the public documentation.

File: net/peer.go [hunk 4]
```diff
@@ -804,6 +808,30 @@ func (p *Peer) AddP2PCollections(collections []string) error {
...
+		c, err := store.GetCollectionBySchemaID(p.ctx, col)
+		if err != nil {
+			return err
+		}
+		keyChan, err := c.GetAllDocKeys(p.ctx)
+		if err != nil {
+			return err
+		}
+		for key := range keyChan {
+			err := p.server.removePubSubTopic(key.Key.String())
```
Comment (AndrewSisley) [inline net/peer.go:823]: suggestion: This will not be rolled back if the txn commit fails, but it should be.  I do not see this as a new issue however (just expanded), as the `addedTopics` block also suffers from this.  Strongly suggest creating a ticket to roll this back properly on commit error (might already be one, I'm not sure though).

Same issue exists in RemoveP2PCollections

File: net/server.go [hunk 5]
```diff
@@ -151,6 +201,26 @@ func (s *server) PushLog(ctx context.Context, req *pb.PushLogRequest) (*pb.PushL
...
 
+	s.docQueue.add(req.Body.DocKey.String())
+	defer func() {
+		s.docQueue.done(req.Body.DocKey.String())
+		if s.pushLogEmitter != nil {
+			byPeer, err := libpeer.Decode(req.Body.Creator)
+			if err != nil {
+				log.Info(ctx, "could not decode the peer id of the log creator", logging.NewKV("Error", err.Error()))
+			}
+			err = s.pushLogEmitter.Emit(EvtReceivedPushLog{
```
Comment (AndrewSisley) [inline net/server.go:212]: praise: I like that this is in a defer now

File: tests/integration/p2p.go [hunk 6]
```diff
@@ -307,7 +317,7 @@ func configureReplicator(
 				docIDsSyncedToSource[currentdocID] = struct{}{}
 			}
 
-			if action.NodeID.HasValue() && action.NodeID.Value() == cfg.SourceNodeID {
+			if !action.NodeID.HasValue() || action.NodeID.Value() == cfg.SourceNodeID {
```
Comment (AndrewSisley) [inline tests/integration/p2p.go:320]: question: Are you sure this is correct?

If `!action.NodeID.HasValue()` then the document will be created synchronously and locally by the test framework in all nodes. Does the P2P system still transmit sync events if they already exist on the node?

todo: If this is correct, can you please add a comment documenting this :)

**Review by AndrewSisley — APPROVED** [review]
Really great work Fred - thanks a whole bunch for sorting these out :)

Left a couple of small comments which would be good to resolve before merge.

File: net/peer.go (hunk 2 above)
Comment (fredcarle) [reply net/peer.go:632]: I think it's still needed for the situation where the target would receive the push to replicator and then the target getting an update before the source registers to the topic. This probably would never happen in real life but it did happen in the tests.

File: net/peer.go (hunk 3 above)
Comment (fredcarle) [reply net/peer.go:813]: At the moment I can't think of a better way to handle this. It would only be expensive if a dev decides to subscribe to a given collection after it has millions of documents. It's also a one-off event if someone was to do it so I don't think we need to worry about speed too much. Not at this time anyways.

I can add a warning to the doc though.

File: net/peer.go (hunk 4 above)
Comment (fredcarle) [reply net/peer.go:823]: Ticket opened 👍

Comment (AndrewSisley) [reply net/peer.go:823]: cheers :)

File: tests/integration/p2p.go (hunk 6 above)
Comment (fredcarle) [reply tests/integration/p2p.go:320]: > Does the P2P system still transmit sync events if they already exist on the node?

Yes. The Replicator doesn't know that the target has the document already so it still sends the created document which will cause the target to send a `received push log` event.
