### PR TITLE
fix: Grouping by indexed field

### LINKED ISSUE #4397: Fix grouping by indexed field

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4397

## Description

Fix out-of-range panic when using `_group` filter on relation with indexed field.
Fix `GroupBy` field value returned as `nil` when using `_group` filter on indexed relation.

### CODE REVIEW

File: tests/integration/index/query_with_group_test.go [hunk 1]
```diff
@@ -0,0 +1,173 @@
+// Copyright 2025 Democratized Data Foundation
```
Comment (fredcarle) [inline tests/integration/index/query_with_group_test.go]: todo: 2026 :)

File: internal/planner/planner.go [hunk 2]
```diff
@@ -411,8 +411,15 @@ func (p *Planner) tryOptimizeJoinDirectionByFilter(node *invertibleTypeJoin, par
 }
 
 // extractRelatedSubFilter extracts the sub filter from the parent filter.
+// Returns nil if the relation field doesn't exist in the document map.
 func extractRelatedSubFilter(f *mapper.Filter, docMap *core.DocumentMapping, relField mapper.Field) *mapper.Filter {
-	subInd := docMap.FirstIndexOfName(relField.Name)
+	// In groupBy queries with _group filters, the docMap may not contain the relation field,
+	// so we check existence before accessing to avoid a panic.
+	indexes, ok := docMap.IndexesByName[relField.Name]
+	if !ok || len(indexes) == 0 {
```
Comment (fredcarle) [inline internal/planner/planner.go]: question: If `ok == true`, is it even possible to have `len(indexes) == 0`?

**Review by fredcarle — COMMENTED** [review]
LGTM

**Review by fredcarle — APPROVED** [review]

**Review by shahzadlone — APPROVED** [review]
LGTM

File: tests/integration/index/query_with_group_test.go (hunk 1 above)
Comment (islamaliev) [reply tests/integration/index/query_with_group_test.go]: done

File: internal/planner/planner.go (hunk 2 above)
Comment (islamaliev) [reply internal/planner/planner.go]: looks like it's not necessary. Removed
