### PR TITLE
fix: Update GetCollections behaviour

### LINKED ISSUE #2371: Fetching a col description with specific version shouldn't require `--get-inactive` flag
If a collection of a specific version is requested `--get-inactive` flat should not be required:
```shell
$ defradb client collection describe --version bafkreichzc4yohatnt7f7uthqjzyusiy7q5mmdutczltou2dzvq6tjxzei 
[]
```
```shell
$ defradb client collection describe --version bafkreichzc4yohatnt7f7uthqjzyusiy7q5mmdutczltou2dzvq6tjxzei --get-inactive
[
  {
    "description": {
      "Name": null,
      "ID": 5,
      "RootID": 5,
      "SchemaVersionID": "bafkreichzc4yohatnt7f7uthqjzyusiy7q5mmdutczltou2dzvq6tjxzei",
      "Sources": [],
      "Fields": [
        {
          "Name": "_docID",
          "ID": 0
        },
...
```

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2371 

## Description

This PR updates the behaviour of `getCollections` to return inactive collections if a specific version is requested even if the `--get-inactive` flag hasn't been set.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: tests/integration/schema/updates/with_schema_branch_test.go [hunk 1]
```diff
@@ -543,3 +543,63 @@ func TestSchemaUpdates_WithBranchingSchemaAndSetActiveSchemaToOtherBranchThenPat
...
+			testUtils.SchemaPatch{
+				// The second schema version will not be set as the active version, leaving the initial version active
+				SetAsDefaultVersion: immutable.Some(false),
+				Patch: `
+					[
+						{ "op": "add", "path": "/Users/Fields/-", "value": {"Name": "email", "Kind": 11} }
+					]
+				`,
+			},
+			testUtils.SchemaPatch{
```
Comment (AndrewSisley) [inline tests/integration/schema/updates/with_schema_branch_test.go:571]: suggestion: 3 schema versions are not required to test this - you could remove the first patch and the `SetActiveSchemaVersion` action and then query for `schemaVersion1ID`

**Review by AndrewSisley — APPROVED** [review]
LGTM, thanks for sorting this out.

suggestion: I think it would be good to update the cli/http/go documentation to note this.

File: tests/integration/schema/updates/with_schema_branch_test.go (hunk 1 above)
Comment (fredcarle) [reply tests/integration/schema/updates/with_schema_branch_test.go]: Thanks for pointing that out. I got lazy on that copy pasting 😅

Comment (fredcarle) [reply tests/integration/schema/updates/with_schema_branch_test.go]: ✅

**Comment by fredcarle** [comment]
> suggestion: I think it would be good to update the cli/http/go documentation to note this.

Documentation updated ✅

File: cli/collection_describe.go [hunk 2]
```diff
@@ -33,10 +33,10 @@ Example: view all collections
 Example: view collection by name
   defradb client collection describe --name User
 		
-Example: view collection by schema id
+Example: view collection by schema root id
```
Comment (AndrewSisley) [inline cli/collection_describe.go:36]: praise: Nice spot :)
