### PR TITLE
fix(i): SetReplicator and DeleteReplicator params

### LINKED ISSUE #3159: `client.Replicator` `Status` and `LastStatusChange` appear to be setable but are not
`client.SetReplicator` takes a `client.Replicator` as a param, yet all implementations ignore any provided `Status` and `LastStatusChange` values given by the users.

It seems likely that the fix for this is to rework the input type used for `client.SetReplicator` so that these values do not appear setable.

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #3159

## Description

This PR fixes an issue where replicator params that are not modifiable were exposed to the client API.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Existing integration tests.

Specify the platform(s) on which this was tested:
- *(modify the list accordingly*)
- MacOS

### CODE REVIEW

File: client/replicator.go [hunk 1]
```diff
@@ -16,6 +16,14 @@ import (
...
+type ReplicatorParams struct {
+	// Info is the address of the peer to replicate to.
+	Info peer.AddrInfo
+	// Collections is the list of collection names to replicate.
+	Collections []string
+}
+
 // Replicator is a peer that a set of local collections are replicated to.
 type Replicator struct {
 	Info             peer.AddrInfo
```
Comment (fredcarle) [inline client/replicator.go:29]: thought: Might as well change the `Schema` to `Collection` to match `ReplicatorParams`

**Review by fredcarle — APPROVED** [review]
LGTM. Just one thougth.

**Review by shahzadlone — APPROVED** [review]
LGTM

File: client/replicator.go (hunk 1 above)
Comment (nasdf) [reply client/replicator.go:29]: The `Schema` field contains schema roots though not collections.

Comment (fredcarle) [reply client/replicator.go:29]: True. Disregard my thought then. 👍
