### PR TITLE
fix: Queries with filter on 2 rel fields of composite index

### LINKED ISSUE #3032: Secondary indexes on relations cause different documents to be returned depending on joins included
Schema:
```gql
type ActionRequirement @index(unique: true, includes: [{ name: "action_id" }, { name: "reward_id" }], name: "actionId_rewardId") {
  count: Int
  isPreReq: Boolean 
  action: Action @relation(name: "actionActionRequirements")
  reward: Reward @relation(name: "rewardActionRequirements")
  createdAt: DateTime 
  oldId: String
}

type Reward {
  name: String 
  description: String
  value: Int
  limit: Int
  tiers: [RewardTier] @relation(name: "rewardRewardTiers")
  priority: Int
  enabled: Boolean 
  actionRequirements: [ActionRequirement] @relation(name: "rewardActionRequirements")
  playerRewards: [PlayerReward] @relation(name: "rewardPlayerRewards")
  rewardGroup: [String] 
  createdAt: DateTime
  oldId: String
}

type RewardTier @index(unique: true, includes: [{ name: "level" }, { name: "reward_id" }], name: "level_rewardId") {
  level: Int
  name: String
  description: String
  value: Int
  reward: Reward @index @primary @relation(name: "rewardRewardTiers") 
  playerReward: [PlayerReward] @relation(name: "playerRewardRewardTiers")
  oldId: String
}

type Action {
  key: String 
  name: String 
  description: String 
  enabled: Boolean 
  levelRequired: Int 
  actionRequirements: [ActionRequirement] @relation(name: "actionActionRequirements")
  playerActions: [PlayerAction] @relation(name: "actionPlayerActions")
  createdAt: DateTime 
  oldId: String
}
```
Queries:
```gql
query queryRewardForLogPlayerAction {
  withTier: Reward(
    filter: {actionRequirements: {action_id: {_in: ["bae-4a72e698-51f8-5f83-ac96-7dee17e7f1a6"]}}}
  ) {
    id: _docID
    actionRequirements {
      id: _docID
    }
    tiers {
      _docID
    }
  }
  withoutTier: Reward(
    filter: {actionRequirements: {action_id: {_in: ["bae-4a72e698-51f8-5f83-ac96-7dee17e7f1a6"]}}}
  ) {
    actionRequirements {
      id: _docID
    }
  }
  withTierNoActionReq: Reward(
    filter: {actionRequirements: {action_id: {_in: ["bae-4a72e698-51f8-5f83-ac96-7dee17e7f1a6"]}}}
  ) {
    id: _docID
    tiers {
      _docID
    }
  }
}
```
All the queries return different sets of data!  Removing the all the indexes from the schema results in all queries returning the correct (and same) results.

Preliminary testing suggests that the problem is with `type ActionRequirement @index(unique: true, includes: [{ name: "action_id" }, { name: "reward_id" }], name: "actionId_rewardId") {` and that removing all but that index results in the same (incorrect) 3 sets of differing results.

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #3032 #2928

## Description

Make parallel node perform a real merge instead of copying fields of a fetched doc, which resulted every next doc overwrite previous fields.

### CODE REVIEW

File: internal/planner/multi.go [hunk 1]
```diff
@@ -136,12 +136,22 @@ func (p *parallelNode) nextMerge(_ int, plan planNode) (bool, error) {
...
 
 	return true, nil
 }
 
+func (p *parallelNode) mergeDoc(doc core.Doc, newFields core.DocFields) core.Doc {
+	for i := range newFields {
+		if doc.Fields[i] == nil {
+			doc.Fields[i] = newFields[i]
+		} else if newSubDoc, ok := newFields[i].(core.Doc); ok {
+			doc.Fields[i] = p.mergeDoc(doc.Fields[i].(core.Doc), newSubDoc.Fields)
```
Comment (AndrewSisley) [inline internal/planner/multi.go:149]: todo: Please document why this is needed, it is not terribly clear why the node should be mutating child relations.

File: tests/integration/index/query_with_unique_index_on_relation_filter_test.go [hunk 2]
```diff
@@ -70,3 +70,106 @@ func TestQueryWithUniqueCompositeIndex_WithFilterOnIndexedRelation_ShouldFilter(
 
 	testUtils.ExecuteTestCase(t, test)
 }
+
+func TestQueryWithUniqueCompositeIndex_WithIndexComprising2RelationsAndFilterOnIt_ShouldFilter(t *testing.T) {
```
Comment (AndrewSisley) [inline tests/integration/index/query_with_unique_index_on_relation_filter_test.go:74]: suggestion: It might be highlighting with a comment why this test is important to have, for example compared to just for composite scalar tests.

Please also document the significance of including two id fields, and one object field in the index.  Perhaps highlighting why a test with two object fields in the index (e.g. `includes: [{name: "owner"}, {name: "manufacturer"}` is not required.

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
I trust it works, but please explain why the the new code does what it does before merge.

File: internal/planner/multi.go (hunk 1 above)
Comment (islamaliev) [reply internal/planner/multi.go:149]: well, it now justifies the name of method `nextMerge`.

I'll add a comment.

File: tests/integration/index/query_with_unique_index_on_relation_filter_test.go (hunk 2 above)
Comment (islamaliev) [reply tests/integration/index/query_with_unique_index_on_relation_filter_test.go:74]: The test case is actually a bit simpler. I wanted to update it, but forgot. Thanks for reminding.

I will add some comments.

File: internal/planner/multi.go (hunk 1 above)
Comment (AndrewSisley) [reply internal/planner/multi.go:153]: I'm not sure the new comment answers what I'm most uncertain about - why does this function recursively mutate child documents, instead of just the top doc?  Why and under which circumstances is the mutation of the children required?  Do please message/call me on discord if you unsure as to what I'm asking.

File: tests/integration/index/query_with_unique_index_on_relation_filter_test.go (hunk 2 above)
Comment (AndrewSisley) [reply tests/integration/index/query_with_unique_index_on_relation_filter_test.go]: Thanks Islam, looks good!

**Review by AndrewSisley — APPROVED** [review]
LGTM, thanks Islam - please try and tweak the documentation for `mergeDoc` a little bit before merge though.

File: internal/planner/multi.go (hunk 1 above)
Comment (islamaliev) [reply internal/planner/multi.go:153]: there is no real reason for recursion here. I just though it would cover some future perverted edge-cases.
I made it merge just top fields to keep it simple.

Comment (AndrewSisley) [reply internal/planner/multi.go]: Ah got it, thanks Islam!
