### PR TITLE
fix(i): Make badger dependency optional

### LINKED ISSUE #2827: Make badger dependency optional
Move badger dependencies to files with build flags to allow JS build

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #2827

## Description

This PR moves some things around to make the badger dependency optional to allow for JS builds.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

`make test`

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: datastore/errors/errors_badger.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+// licenses/APL.txt.
+
+//go:build !js
+
+package errors
+
+import "github.com/sourcenetwork/badger/v4"
+
+func init() {
+	ErrTxnConflict = badger.ErrConflict
```
Comment (AndrewSisley) [inline datastore/errors/errors_badger.go:18]: suggestion: I can picture this causing problems - not building for JS does not mean that the errors should be badger ones!  Other stores may be used (also or as well).  It would be far better IMO to make sure that we return consistent errors instead of doing this.

In my opinion errors are part of the interface (contract), not the implementation - yes, a bunch of annoying libs break this, and occasionally it is necessary if the interface does not declare enough useful errors (not a problem here, as we have control - even if it means a thin wrapper), but this is the point of view I have when making the above suggestion.

File: node/store.go [hunk 2]
```diff
@@ -14,65 +14,75 @@ import (
...
 	}
 }
 
-// WithDefraStore sets the defra store flag.
-//
-// Setting this to true will result in the defra node being created with
-// the a custom defra implementation of the rootstore instead of badger.
-func WithDefraStore(defraStore bool) StoreOpt {
+// WithBadgerInMemory sets the badger in memory option.
+func WithBadgerInMemory(enable bool) StoreOpt {
```
Comment (AndrewSisley) [inline node/store.go:62]: todo: I think if the badger store is protected by build flags, then all of the production badger stuff should also be, including these functions.  Please move them into a build-tag specific file, or explain why that is not practical :)

File: node/store.go [hunk 3]
```diff
@@ -14,65 +14,75 @@ import (
...
 	}
 }
 
-// WithPath sets the datastore path.
-func WithPath(path string) StoreOpt {
+// WithBadgerPath sets the badger datastore path.
+func WithBadgerPath(path string) StoreOpt {
 	return func(o *StoreOptions) {
-		o.path = path
+		o.badgerPath = path
```
Comment (AndrewSisley) [inline node/store.go:71]: question: Why have you made these (props and public funcs) store specific?

File: datastore/errors/errors.go [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+
+var (
+	ErrClosed = errors.New("datastore closed")
+	// ErrConflict is returned when a transaction conflicts with another transaction. This can
+	// happen if the read rows had been updated concurrently by another transaction.
+	//
+	// This error is copied from badger because it is used in a few places outside of the datastore
+	// package. This copy ensures that we can build in environments that do not support badger.
+	//
+	//nolint:revive
```
Comment (AndrewSisley) [inline datastore/errors/errors.go:23]: question: What is the `nolint` for?  What error do you get without it?

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
LGTM, looking forward to getting the full JS build :)  Got a handful of small stuff for you first :)

File: datastore/errors/errors.go (hunk 4 above)
Comment (nasdf) [reply datastore/errors/errors.go:23]: Capital letter at the beginning of the message.

Comment (AndrewSisley) [reply datastore/errors/errors.go:23]: This reason nudges me even more towards changing the errors (either in the badger fork, or with a wrapper)

File: datastore/errors/errors_badger.go (hunk 1 above)
Comment (nasdf) [reply datastore/errors/errors_badger.go]: I've added a function to convert the errors within the badger datastore. It was much simpler than I first thought.

File: node/store.go (hunk 2 above)
Comment (nasdf) [reply node/store.go:62]: The trade-off to make here is: if we move the options to the build specific file, then we will need to add platform specific files to the test harness as well. I was hoping the node package could serve as the entry point for all platforms so that we can avoid adding platform specific files elsewhere. I'm fine with either option.

Comment (nasdf) [reply node/store.go]: I moved the options to the badger specific file like we discussed.

File: node/store.go (hunk 3 above)
Comment (nasdf) [reply node/store.go]: I renamed `badgerPath` to `path`.

File: datastore/errors/errors.go (hunk 4 above)
Comment (AndrewSisley) [reply datastore/errors/errors.go:23]: Are these code-comments now out of date? These can now be our own errors due to the wrapping?  Can we remove the lint and start them with lower case?

Comment (nasdf) [reply datastore/errors/errors.go]: Done

**Review by shahzadlone — APPROVED** [review]
LGTM
