### PR TITLE
fix: Add entropy to counter CRDT type updates

### LINKED ISSUE #2179: Concurrent PNCounter is unpredictable over P2P
In a peer network of two nodes, where two concurrent updates are made to each node with the same value, sometimes the end result will be the summation/doubling of the update, and sometimes the result will be a single update.

For example in the below, the result will sometimes be `45`, and sometimes it will be `90`. `90` Appears to occur less frequently than `45`.
```
                        testUtils.RandomNetworkingConfig(),
			testUtils.RandomNetworkingConfig(),
			testUtils.SchemaUpdate{
				Schema: `
					type Users {
						Name: String
						Age: Int @crdt(type: "pncounter")
					}
				`,
			},
			testUtils.CreateDoc{
				// Create John on all nodes
				Doc: `{
					"Name": "John",
					"Age": 0
				}`,
			},
			testUtils.ConnectPeers{
				SourceNodeID: 0,
				TargetNodeID: 1,
			},
			testUtils.UpdateDoc{
				NodeID: immutable.Some(0),
				Doc: `{
					"Age": 45
				}`,
			},
			testUtils.UpdateDoc{
				NodeID: immutable.Some(1),
				Doc: `{
					"Age": 45
				}`,
			},
			testUtils.WaitForSync{},
			testUtils.Request{
				Request: `query {
					Users {
						Age
					}
				}`,
			},
```

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2179 

## Description

Counters need to be incrementable independently from different nodes. Initially, if two nodes incremented by the same amount from the same synced state, then the update CID would be the same and thus taken as a the same operation when syncing. So starting from 10 if both node A and B increment by 5 simultaneously, because they would generate the same CID for the update, the end result would be 15. We want it to be 20.

This PR adds entropy to the PN Counter delta so that a situation like described above would result in 20.

Note that the entropy is only added on update so that a document can be instantiated on multiple nodes with exactly the same CID.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: core/crdt/pncounter.go [hunk 1]
```diff
@@ -45,6 +48,9 @@ type PNCounterDelta[T Incrementable] struct {
 	DocID     []byte
 	FieldName string
 	Priority  uint64
+	// Entropy is an added randomly generated number that ensures
+	// that each increment operation is unique.
+	Entropy int64
```
Comment (jsimnz) [inline core/crdt/pncounter.go:53]: todo: Lets rename this to `Nonce` as its more cryptographically accurate, and slightly more common

File: core/crdt/pncounter.go [hunk 2]
```diff
@@ -108,13 +114,30 @@ func (reg PNCounter[T]) Value(ctx context.Context) ([]byte, error) {
 }
 
 // Set generates a new delta with the supplied value
-func (reg PNCounter[T]) Increment(value T) *PNCounterDelta[T] {
+func (reg PNCounter[T]) Increment(ctx context.Context, value T) (*PNCounterDelta[T], error) {
+	// To ensure that the dag block is unique, we add a random number to the delta.
+	// This is done only on update (if the doc doesn't already exist) to ensure that the
+	// initial dag block of a document can be reproducible.
```
Comment (AndrewSisley) [inline core/crdt/pncounter.go:120]: praise: Good catch :)

question: Do we have any tests that target this and ensure that the docID is consistent (e.g. by hard coding it in the test)? If not, please consider this a todo :)

Comment (AndrewSisley) [reply core/crdt/pncounter.go:120]: Should have read first, there are tests that cover this, but they are complicated by cids and updates.  Can you please add a simple one that makes it clear why such a test is needed?

**Review by AndrewSisley — APPROVED** [review]
LGTM, one test todo first before merge though please :)

File: core/crdt/pncounter.go [hunk 3]
```diff
@@ -108,13 +114,30 @@ func (reg PNCounter[T]) Value(ctx context.Context) ([]byte, error) {
...
+	exists, err := reg.store.Has(ctx, reg.key.ToPrimaryDataStoreKey().ToDS())
+	if err != nil {
+		return nil, err
+	}
+	var entropy int64
+	if exists {
```
Comment (jsimnz) [inline core/crdt/pncounter.go:126]: question: When creating a new PNCounter field, this is going to produce an entropy value of `0`. Is this intended? Or do we want to omit the entropy field entirely when creating? (IE: not include in the cbor marshal)

**Review by jsimnz — CHANGES_REQUESTED** [review]

File: core/crdt/pncounter.go (hunk 2 above)
Comment (fredcarle) [reply core/crdt/pncounter.go:120]: If the docID wasn't consistent, the updates wouldn't sync over P2P.

File: core/crdt/pncounter.go (hunk 3 above)
Comment (fredcarle) [reply core/crdt/pncounter.go:126]: This is indeed intended. Instead of having a different struct for create vs update, using 0 gives us the same result with less complexity.

File: core/crdt/pncounter.go (hunk 1 above)
Comment (AndrewSisley) [reply core/crdt/pncounter.go:53]: Lol... Whoever introduced that to crypto was probably not British... It is not very polite.  If it is only slightly more common I'd suggest sticking with `Entropy`.

File: core/crdt/pncounter.go (hunk 2 above)
Comment (AndrewSisley) [reply core/crdt/pncounter.go:120]: True :)  Thanks for pointing out

Comment (fredcarle) [reply core/crdt/pncounter.go:120]: I'm adding a docID assertion on the mutation create test just to make it more obvious.

File: core/crdt/pncounter.go (hunk 3 above)
Comment (fredcarle) [reply core/crdt/pncounter.go:126]: A clarification. The entropy will be `0` only when creating the **document**.

File: core/crdt/pncounter.go (hunk 1 above)
Comment (shahzadlone) [reply core/crdt/pncounter.go]: FWIW `nonce` is fairly common in the cryptography world, so I have a slight pref for it.

**Review by shahzadlone — APPROVED** [review]
Neat fix, LGTM

**Review by jsimnz — APPROVED** [review]
