### PR TITLE
fix: Validate GraphQL schemas

### LINKED ISSUE #3151: Validate GraphQL schemas
GraphQL schemas are currently not validated. This allows for invalid types in schema fields, directives, etc.

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #3151

## Description

This PR fixes an issue where GraphQL schemas were never validated.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Updated integration tests.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by jsimnz — COMMENTED** [review]
LGTM (super speedy :) )

**Review by jsimnz — APPROVED** [review]
LGTM (super speedy)

**Review by shahzadlone — APPROVED** [review]
Nice and clean! Thanks Keenan =)

File: internal/request/graphql/schema/manager.go [hunk 1]
```diff
@@ -99,162 +77,22 @@ func (s *SchemaManager) ResolveTypes() error {
...
-
-		commitsOrderArg,
-		commitLinkObject,
-		commitObject,
-
-		crdtEnum,
-		explainEnum,
-
-		indexFieldInput,
+	validation := gql.ValidateDocument(&s.schema, doc, gql.SpecifiedRules)
```
Comment (AndrewSisley) [inline internal/request/graphql/schema/manager.go:90]: thought: I love the near total lack of documentation in the gql-go lib...

todo: This is quite an odd flow, as we appear to be validating the `doc` against a schema that does not yet contain the contents of `doc`.  Can you please document this call quite heavily.

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
It looks good, but the location of the `ValidateDocument` looks odd and needs documentation.

thought: You blended a lot of seemingly random refactors into to main change, without documenting them in the PR description or committing them separately - whilst they are nice changes, presenting them to reviewers  like this made the review quite a lot harder than it needed to be.

File: internal/request/graphql/schema/manager.go (hunk 1 above)
Comment (jsimnz) [reply internal/request/graphql/schema/manager.go:90]: I think you have the validation flow backwards Andy.

The ValidateDocument call *is* to validate that the given SDL document is valid relative to the schema defined up till now (eg, first run only the "default" schema is defined). 

This is the correct flow as I understand it. A comment can help but it doesn't seem unusual or out of place to me.

Comment (AndrewSisley) [reply internal/request/graphql/schema/manager.go:90]: > The ValidateDocument call is to validate that the given SDL document is valid relative to the schema defined up till now (eg, first run only the "default" schema is defined).

That's fine, but need to be documented, particularly given that the SDL is partial atm and does not fully represent the changes that will be made to the GQL-schema once encorporated.  There is a lot of GQL stuff that we do/add that will not be validated by this call.

Comment (jsimnz) [reply internal/request/graphql/schema/manager.go:90]: Agreed, all the generated stuff after this won't get validated, but I don't think there's any implication at this call site that it's doing anything more than validating the user provided SDL, which needs to be valid on its own before continuing on with any future schema generation stuff.

Comment (AndrewSisley) [reply internal/request/graphql/schema/manager.go:90]: Yes, I'm totally on board with all of that.

The reason I'm asking for documentation is so that the next person who comes across this line (including our future selves) doesn't need to think terribly hard about why it is done here, and why the premature validation is okay here (and potentially come to the wrong conclusion, wasting even more time and thought).

Comment (nasdf) [reply internal/request/graphql/schema/manager.go:92]: I've added documentation that hopefully makes it a bit more clear as to what's happening

**Comment by nasdf** [comment]
> It looks good, but the location of the `ValidateDocument` looks odd and needs documentation.
> 
> thought: You blended a lot of seemingly random refactors into to main change, without documenting them in the PR description or committing them separately - whilst they are nice changes, presenting them to reviewers like this made the review quite a lot harder than it needed to be.

Sorry it was a bit messy. I put this PR together very quickly last night and should have probably just waited to finish it properly.

File: internal/request/graphql/schema/manager.go (hunk 1 above)
Comment (AndrewSisley) [reply internal/request/graphql/schema/manager.go:92]: Looks good, thanks Keenan - should help a fair bit :)

**Review by AndrewSisley — APPROVED** [review]
> Sorry it was a bit messy. I put this PR together very quickly last night and should have probably just waited to finish it properly.

No worries at all, it was a small PR after all, and I'm plenty guilty of rushing stuff out in the evenings :)

Looks great, and is great to get this in, especially before the release :)
