### PR TITLE
fix: Prevent doc writes after collection deleted

### LINKED ISSUE #4268: Concurrent writes during a collection version delete succeed and break commits api
I was 'fairly confident' that the transaction system would prevent this, however it does not (at least with badger stores).

Instead of the create-doc calls erroring out, they are allowed to complete after the last collection version has been deleted.

This orphans blocks, and cause any subsequent calls to the commits API (without collection filters at least) to fail with a `key not found` error as the planner tries to populate the orphaned doc commits to a collection that no longer exists.

This issue probably also affects document writes received over P2P and other means (import?), but that has not been tested.

This issue is documented by `TestColVersionUpdateRemoveCollections_ConcurrentWrite` and there is a code-comment referencing this issue in the WIP branch.

### LINKED ISSUE #4663: Cannot recreate collection after deleting it
The following test errors on the last action.  The error differs if using a transaction or not.  It should not error at all:
```
	test := testUtils.TestCase{
		Actions: []any{
			&action.AddCollection{
				SDL: `
					type Users {
						name: String
					}
				`,
			},
			&action.AddCollection{
				// We don't yet have a create transaction action, so we need to create
				// one by performing an operation on anything but the `Users` collection
				// as doing anything on `Users` will acquire a read lock on the collection.
				TransactionID: immutable.Some(0),
				SDL: `
					type Books {
						name: String
					}
				`,
			},
			&action.PatchCollection{
				Patch: `
						[
							{
								"op": "remove",
								"path": "/Users"
							}
						]
					`,
			},
			&action.AddCollection{
				TransactionID: immutable.Some(0),
				SDL: `
					type Users {
						name: String
					}
				`,
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
```
`error checking for known block` without a txn, `collection already exists` with a transaction.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #4268
Partially resolves #4663

## Description

Prevents doc writes after last collection version deleted.

### CODE REVIEW

File: internal/db/description/collection_store.go [hunk 1]
```diff
@@ -0,0 +1,512 @@
...
+		err = txn.Systemstore().Set(ctx, collectionVersionKey.Bytes(), []byte{})
+		if err != nil {
+			return err
+		}
+	}
+
+	i.forbiddenLock.Lock()
+	// If this transaction writes a collection version that was previously forbidden, we must unforbid it
+	// within the context of this transaction.
+	// todo - make sure the unforbidding is tested!
```
Comment (AndrewSisley) [inline internal/db/description/collection_store.go]: todo: I missed this todo - I'm fairly sure this is tested now, but double check and then delete the todo.

- [x] Remove todo

Comment (AndrewSisley) [reply internal/db/description/collection_store.go]: This is covered by TestColVersionUpdateRemoveCollection_CollectionMayBeRedeclaredAndUsedByTxn, removing todo.

**Review by shahzadlone — APPROVED** [review]
LGTM
