### PR TITLE
fix(i): Add self reference import handling

### LINKED ISSUE #1697: Backup-Import cannot handle self referencing documents
As documented by `TestBackupSelfRefImport_SelfReferencing_NoError` and `TestBackupSelfRefImport_SplitPrimaryRelationWithSecondCollection_NoError`.

Whilst it is very difficult to achieve by import alone due to difficulties in generating the relation-id, this issue does mean that an export of such a document cannot be imported correctly.

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #1697 

## Description

This PR add the capability to handle self referencing docs on import.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

added integration tests

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: db/backup.go [hunk 1]
```diff
@@ -69,6 +69,19 @@ func (db *db) basicImport(ctx context.Context, txn datastore.Txn, filepath strin
 				return NewErrJSONDecode(err)
 			}
 
+			// check if self referencing and remove from docMap for key creation
+			resetMap := map[string]any{}
```
Comment (AndrewSisley) [inline db/backup.go:73]: todo: This does not look like it will work with `TestBackupSelfRefImport_SplitPrimaryRelationWithSecondCollection_NoError` - your `TestBackupImport_DoubleReletionshipWithUpdate_NoError` test has defined the primary relations all on one object meaning it is not really self-referencing, although it is a gap I have missed in my PR and should be kept.

Either way I think you should wait for that PR to be merged in order to make use of the tests that flagged this error to be sure it  is fixed.

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
I'm not sure this fully solves the issue, and I think it should wait for the more comprehensive tests added in the PR that found the bug.

File: db/backup.go (hunk 1 above)
Comment (fredcarle) [reply db/backup.go:73]: It won't but it's a different problem. The error in `TestBackupSelfRefImport_SplitPrimaryRelationWithSecondCollection_NoError` is on export as explained in the note I left on your PR.

Comment (AndrewSisley) [reply db/backup.go:73]: (noted over there, but repeating here for ease of reference)

Was a really good spot by you there, but I still don't think the import code will work once the export is fixed.

File: tests/integration/backup/one_to_one/import_test.go [hunk 2]
```diff
@@ -237,3 +237,58 @@ func TestBackupImport_WithMultipleNoKeyAndMultipleCollectionsAndMultipleUpdatedD
 
 	executeTestCase(t, test)
 }
+
+func TestBackupImport_DoubleReletionshipWithUpdate_NoError(t *testing.T) {
```
Comment (shahzadlone) [inline tests/integration/backup/one_to_one/import_test.go:241]: nitpick:
```suggestion
func TestBackupImport_DoubleRelationshipWithUpdate_NoError(t *testing.T) {
```

**Review by jsimnz — APPROVED** [review]
Lgtm. Didn't dive too much into the root problem so my review is mostly on the superficial code quality aspect.
