### PR TITLE
fix: Handle _version alongside type joins

### LINKED ISSUE #1709: queries on type with requested relational object and _version don't work

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1709

## Description

Handles `_version` properties that exist alongside type joins.

### CODE REVIEW

File: internal/planner/multi.go [hunk 1]
```diff
@@ -81,6 +81,29 @@ func (p *parallelNode) Kind() string {
...
+			endIndex--
+		default:
+			newChildren[startIndex] = child
+			newChildIndexes[startIndex] = p.childIndexes[i]
+			startIndex++
+		}
+	}
+
+	p.children = newChildren
+	p.childIndexes = newChildIndexes
```
Comment (islamaliev) [inline internal/planner/multi.go:109]: suggestion: the significance of this change is not clear here. Maybe a comment explaining an examples case it solves. Even better would to extract this block into a function with a descriptive name like `orderChildrenExecution`

**Review by islamaliev — APPROVED** [review]
LGTM!

File: internal/planner/multi.go (hunk 1 above)
Comment (AndrewSisley) [reply internal/planner/multi.go:109]: You don't think the existing comment covers it?  Do you have a rough example as to what you are looking for?
> // Any node types that result in `nextAppend` calls must be executed last, as they are
  // dependent on the docID set by the `nextMerge` calls.

**Review by fredcarle — APPROVED** [review]
Thank for fixing this. It would be nice to document this a little more before merge. The comment in the switch case is not giving much information unless the reader is very familiar with that part of the code.

File: internal/planner/multi.go (hunk 1 above)
Comment (AndrewSisley) [reply internal/planner/multi.go:109]: Fred's comment gave me an idea, as this code is in a different block to the one with the `nextAppend`/`nextMerge` calls - I've linked to it more explicitly.
