### PR TITLE
fix: Standardise `schema migration` CLI errors

### LINKED ISSUE #1652: Add tests for `schema migration` CLI commands
`get` and `set`

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1652

## Description

Standardises `schema migration set` errors. And errors if given unknown lens cfg properties.

Adds integration tests for the command.

### CODE REVIEW

File: tests/integration/cli/client_schema_migration_get_test.go [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+
+	stdout, _ := runDefraCommand(t, conf, []string{
+		"client", "schema", "migration", "get",
+	})
+	_ = stopDefra()
+
+	assertContainsSubstring(t, stdout, `{"data":{"configuration":[]}}`)
+}
+
+func TestSchemaMigrationGet_GivenEmptyMigrationObj_ShouldSucceed(t *testing.T) {
```
Comment (islamaliev) [inline tests/integration/cli/client_schema_migration_get_test.go:45]: todo: `TestSchemaMigrationSet_`

Comment (AndrewSisley) [reply tests/integration/cli/client_schema_migration_get_test.go:45]: I disagree - this test tests `get`, it 'accidentally' tests part of `set` in order to test `get`

**Review by islamaliev — APPROVED** [review]
Looks good Andy. I'm not sure if this should be part of this PR but would it be possible to add integration tests with invalid arguments to a lens module? 
```json
{"lenses": [{"path": "/path/to/remove.wasm", "arguments": {"invalid":"verified"}}]}
```

File: tests/integration/cli/client_schema_migration_get_test.go (hunk 1 above)
Comment (islamaliev) [reply tests/integration/cli/client_schema_migration_get_test.go:45]: okay, I though it was a mistake

**Comment by AndrewSisley** [comment]
> Looks good Andy. I'm not sure if this should be part of this PR but would it be possible to add integration tests with invalid arguments to a lens module?
> 
> ```json
> {"lenses": [{"path": "/path/to/remove.wasm", "arguments": {"invalid":"verified"}}]}
> ```

There is one such test - `TestSchemaMigrationSet_GivenCfgWithLenseError_ShouldError` - I see further testing of that as outside the scope of the CLI tests - they should (and are) instead tested within lens and (a little bit) in the core defra tests.

Within the CLI tests for Lens I just care that it does report wasm generated errors to the user, I see the specifics regarding which errors and how/when they are generated as out of scope here.

File: Makefile [hunk 2]
```diff
@@ -29,7 +29,7 @@ ifdef BUILD_TAGS
 BUILD_FLAGS+=-tags $(BUILD_TAGS)
 endif
 
-TEST_FLAGS=-race -shuffle=on -timeout 70s
+TEST_FLAGS=-race -shuffle=on -timeout 120s
```
Comment (shahzadlone) [inline Makefile:32]: Question: what caused this bump?

**Review by shahzadlone — APPROVED** [review]
LGTM

File: Makefile (hunk 2 above)
Comment (AndrewSisley) [reply Makefile:32]: More tests == even slower :(

Comment (islamaliev) [reply Makefile:32]: I guess a bunch of CLI tests
