### PR TITLE
fix(i): Lock collection when deleting collection versions

### LINKED ISSUE #4511: Deleting the last remaining collection version should lock collection
Deleting the last remaining collection version should lock the collection, and cause competing actions to fail with a transaction conflict error.

Related to https://github.com/sourcenetwork/defradb/issues/4268 and https://github.com/sourcenetwork/defradb/issues/4510

Deleting fields also needs to lock, as their sids are being deleted.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #4511

## Description

Locks the collection when deleting collection and field short ids.

Also fixes a bug where collection short ids weren't actually getting deleted when the last collection version was deleted.

This is currently a pain to test due to the caching issue described in https://github.com/sourcenetwork/defradb/issues/4268 - the CI will make sure that no regressions are introduced, but they do not (yet) validate that the bug has been fixed.  Tests will be added during #4268.

### CODE REVIEW

File: internal/db/description/collection.go [hunk 1]
```diff
@@ -499,12 +505,16 @@ func DeleteCollection(
...
+	err = id.DeleteShortFieldIDs(ctx, lockSet, version, versions)
 	if err != nil {
 		return err
 	}
 
-	if len(versions) == 0 {
+	if len(versions) == 1 {
+		// It is impossible to recreate the collection short ID once it is deleted, so we must lock the collection
+		// whilst we finalize this operation, otherwise other threads/operations may try and make use of it.
+		lockSet.CollectionLock(txn, shortID)
```
Comment (nasdf) [inline internal/db/description/collection.go:516]: question: Could this lock be acquired before `DeleteShortFieldIDs` so that we don't need two different locks?

File: internal/db/description/collection.go [hunk 2]
```diff
@@ -499,12 +505,16 @@ func DeleteCollection(
 
 	// WARNING - DeleteShortFieldIDs is dependent on the collection short id still existing, it should be called
 	// before deleting the collection short id.
-	err = id.DeleteShortFieldIDs(ctx, version, versions)
+	err = id.DeleteShortFieldIDs(ctx, lockSet, version, versions)
 	if err != nil {
 		return err
 	}
 
-	if len(versions) == 0 {
```
Comment (nasdf) [inline internal/db/description/collection.go:507]: question: Was this an existing bug?

**Review by nasdf — APPROVED** [review]
LGTM

File: internal/db/description/collection.go (hunk 1 above)
Comment (AndrewSisley) [reply internal/db/description/collection.go:516]: > two different locks

I'm not completely sure if you mean two different locks, or two different calls to acquire (a) lock(s).

Field short ids get deleted if the last collection that contains them gets deleted, so they can be deleted, and the lock required, even if there remain collection versions after this collection version is deleted.  So two calls to acquire (a) lock(s) are required.

Two (or more) locks will never actually be acquired.  The lock system ensures that each transaction can only ever hold a single lock, so if both calls to `CollectionLock` are made, only one lock will be held.  This is important to prevent deadlocks, such as the one that would occur here if two locks for the same collection were requested by the same thread.

File: internal/db/description/collection.go (hunk 2 above)
Comment (AndrewSisley) [reply internal/db/description/collection.go:507]: Yes, sorry, I should have noted that in the PR description.  It was documented in the commit message, but *that* documentation was not noted in the PR description.

I'll edit the PR description before merge for tracking - thanks for flagging :)
