### PR TITLE
fix: Handle queries with _version prop and order param

### LINKED ISSUE #4144: Panic when query contains `order` and `_version`
E.g. The below works:
```
Log (filter: { _and: [ { blockNumber: { _ge: 1 } }, { blockNumber: { _le: 1000 } } ] }){
  _docID
 _version { cid signature { type identity value } } 
 address
 topics 
 data
 transactionHash
 blockNumber
}
```
But the following panics:
```
Log (filter: { _and: [ { blockNumber: { _ge: 1 } }, { blockNumber: { _le: 1000 } } ] }, order: { blockNumber: DESC }){
  _docID
  _version { cid signature { type identity value } } 
  address
  topics
  data
  transactionHash
  blockNumber
}
```
With:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10930b9ac]

goroutine 1269 [running]:
github.com/sourcenetwork/defradb/internal/planner.(*multiScanNode).Source(0x0)
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/scan.go:407 +0x1c
github.com/sourcenetwork/defradb/internal/planner.getNode[...]({0x10cbbba60, 0x1400160e000})
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/type_join.go:853 +0xd0
github.com/sourcenetwork/defradb/internal/planner.isOrderedByIndex({0x10cbbba60, 0x1400160e000})
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/planner.go:322 +0x44
github.com/sourcenetwork/defradb/internal/planner.(*Planner).expandSelectTopNodePlan(0x14012111c70, 0x1401215d810, 0x0)
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/planner.go:240 +0x1bc
github.com/sourcenetwork/defradb/internal/planner.(*Planner).expandPlan(0x14012111c70, {0x10cbbb0a0, 0x1401215d810}, 0x0)
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/planner.go:154 +0x4b8
github.com/sourcenetwork/defradb/internal/planner.(*Planner).expandMultiNode(0x14012111c70, {0x119ebbe20, 0x14012147040}, 0x0)
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/planner.go:276 +0xa8
github.com/sourcenetwork/defradb/internal/planner.(*Planner).expandPlan(0x14012111c70, {0x10cbbb700, 0x14012147040}, 0x0)
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/planner.go:191 +0x6f8
github.com/sourcenetwork/defradb/internal/planner.(*Planner).optimizePlan(0x14012111c70, {0x10cbbb700, 0x14012147040})
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/planner.go:146 +0x40
github.com/sourcenetwork/defradb/internal/planner.(*Planner).MakePlan(0x14012111c70, 0x14012146fa0)
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/planner.go:726 +0x21c
github.com/sourcenetwork/defradb/internal/planner.(*Planner).RunRequest(0x14012111c70, {0x10cb90370, 0x1400ca66c60}, 0x14012146fa0)
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/planner/planner.go:639 +0x58
github.com/sourcenetwork/defradb/internal/db.(*DB).execRequest(0x14000271600, {0x10cb90370, 0x1400ca66c60}, {0x1400031be00, 0xea}, 0x1400ca31170)
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/db/request.go:59 +0x654
github.com/sourcenetwork/defradb/internal/db.(*DB).ExecRequest(0x14000271600, {0x10cb90370, 0x1400ca66c60}, {0x1400031be00, 0xea}, {0x0, 0x0, 0x0})
	/Users/quinnpurdy/go/pkg/mod/github.com/sourcenetwork/defradb@v0.20.0/internal/db/store.go:42 +0x434
github.com/shinzonetwork/app-sdk/pkg/defra.(*queryClient).query(0x14001971b88, {0x10cb903a8, 0x140016645a0}, {0x1400031be00, 0xea})
	/Users/quinnpurdy/go/pkg/mod/github.com/shinzonetwork/app-sdk@v0.0.0-20251107185640-33925fbdeafc/pkg/defra/query.go:35 +0xdc
github.com/shinzonetwork/app-sdk/pkg/defra.(*queryClient).queryDataInto(0x14001971b88, {0x10cb903a8, 0x140016645a0}, {0x1400031be00, 0xea}, {0x10bed33c0, 0x1400ca310e0})
	/Users/quinnpurdy/go/pkg/mod/github.com/shinzonetwork/app-sdk@v0.0.0-20251107185640-33925fbdeafc/pkg/defra/query.go:96 +0x6c
github.com/shinzonetwork/app-sdk/pkg/defra.QueryArray[...]({0x10cb903a8, 0x140016645a0}, 0x14000657b90, {0x1400ca76000, 0xe0})
	/Users/quinnpurdy/go/pkg/mod/github.com/shinzonetwork/app-sdk@v0.0.0-20251107185640-33925fbdeafc/pkg/defra/query.go:234 +0x170
github.com/shinzonetwork/shinzo-host-client/pkg/host.(*Host).ApplyView(0x1400781db00, {0x10cb903a8, 0x140016645a0}, {{0x1400214a085, 0x61}, 0x1400208a1e0, 0x1400208a1f0, {{0x14002089a10, 0x1, 0x1}}, ...}, ...)
	/Users/quinnpurdy/Documents/repos/host2/pkg/host/viewHosting.go:111 +0x30c
github.com/shinzonetwork/shinzo-host-client/pkg/host.(*Host).processView(0x1400781db00, {0x10cb903a8, 0x140016645a0}, 0x14007849d60)
	/Users/quinnpurdy/Documents/repos/host2/pkg/host/blockProcessing.go:75 +0x328
github.com/shinzonetwork/shinzo-host-client/pkg/host.(*Host).processAllViews(0x1400781db00, {0x10cb903a8, 0x140016645a0})
	/Users/quinnpurdy/Documents/repos/host2/pkg/host/blockProcessing.go:98 +0x1fc
created by github.com/shinzonetwork/shinzo-host-client/pkg/host.StartHostingWithEventSubscription in goroutine 6
	/Users/quinnpurdy/Documents/repos/host2/pkg/host/host.go:98 +0xa40
```

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #4144

## Description

Handle queries with `_version` property and order parameter instead of panicing.

I also had a look at #1709 - it is still failing, but for very similar reasons, however the fix is proving to be a bit more involved, so I'm sorting that out in another PR.

#4021 was also looked at, it has a very easy fix, but is a separate issue, so I'm going to sort that separately too.

### CODE REVIEW

File: tests/integration/query/simple/with_version_order_test.go [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+package simple
+
+import (
+	"testing"
+
+	"github.com/sourcenetwork/defradb/tests/action"
+	testUtils "github.com/sourcenetwork/defradb/tests/integration"
+)
+
+func TestQuerySimpleWithVersionAndOrder(t *testing.T) {
```
Comment (islamaliev) [inline tests/integration/query/simple/with_version_order_test.go:20]: nitpick: the name doesn't follow our convention.

File: tests/integration/query/simple/with_version_order_test.go [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+	test := testUtils.TestCase{
+		Actions: []any{
+			&action.AddSchema{
+				Schema: `
+					type Users {
+						Name: String
```
Comment (islamaliev) [inline tests/integration/query/simple/with_version_order_test.go]: nitpick: field names are usually lower-cased

**Review by islamaliev — APPROVED** [review]
LGTM! Left 2 nitpicks

File: internal/planner/multi.go
Comment (jsimnz) [inline internal/planner/multi.go:1]: question: I'm a little confused by this fix. Obviously it works, but it feels like for the wrong reason (or works because were shoehorning in a fix in an awkward spot).

Specifically, adding a dedicated `source` plan to the `parellelNode` then returning that `source` on the `Source()` method might be incorrect semantics here. You are instanciating the `parallelNode` with a specific/singular `planNode` (the `dagScanNode` in this case), but we are never updating it. But isnt the whole point of the parallelNode that is pulls from the `multiScanNode` and thats why the `multiScanNode` is the "source" here.

When we add additional plans to the `parallelNode` after its been instanciated (like we do on line 246) that "source" is no longer the one `dagScanNode`, but we never update the `source` field on the `parallelNode`.

--

I know thats a little convoluted. Basically, I recognize this fix works, but it seems like its in the wrong place. Obviously `Source()` is called elsewhere, and wherever that call site is in relation to the `dagScanNode` and the order code is causing the problem this PR is trying to fix. Seems like the fix should update the callsite and be smarter to dig through the `multiscan` "source" that was previously in place and pull out the correct one.

This works, but I fear its creating some new unknown issue down the line by abusing the `Source()` semantics.

File: tests/integration/query/simple/with_version_order_test.go (hunk 1 above)
Comment (AndrewSisley) [reply tests/integration/query/simple/with_version_order_test.go:20]: Which convention :)?  It follows the convention used by many tests.

File: internal/planner/multi.go
Comment (AndrewSisley) [reply internal/planner/multi.go:1]: `Source()` is broken by design, and that is one of the reasons for the other bug I'm working on.  Nodes can have many sources, and the function signature does not take that into account.

It might be removed completely.

> This works, but I fear its creating some new unknown issue down the line by abusing the Source() semantics.

Tldr, it is already broken, probably has been since it was introduced, and will be fixed/removed in an upcoming PR.

File: tests/integration/query/simple/with_version_order_test.go (hunk 2 above)
Comment (AndrewSisley) [reply tests/integration/query/simple/with_version_order_test.go]: This depends on the age of the test, or the test it was copied from.  I think we agreed to change to lowercase moving forward (a few years ago) though, so I'll change the new ones.

- [ ] Lowercase the field names

File: tests/integration/query/simple/with_version_order_test.go (hunk 1 above)
Comment (fredcarle) [reply tests/integration/query/simple/with_version_order_test.go:20]: We agree a long time ago to have this pattern `TestArea_WhatTheTestIs_ExpectResult` :)
