### PR TITLE
fix: Filter on top-level indexed JSON field

### LINKED ISSUE #4396: Fix filtering on json field with top-level condition

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4396

## Description

Fix filtering on top-level indexed JSON field

### CODE REVIEW

File: internal/db/fetcher/indexer_iterators.go [hunk 1]
```diff
@@ -815,7 +817,7 @@ func makeFieldFilterCondition(
 	}
 
 	var err error
-	if len(jsonPath) > 0 {
+	if indexedField.Kind == client.FieldKind_NILLABLE_JSON && (len(jsonPath) > 0 || filterVal != nil) {
```
Comment (AndrewSisley) [inline internal/db/fetcher/indexer_iterators.go]: suggestion: Documentation here would be really handy.  I am struggling to figure out why this if is so nuanced.

**Review by AndrewSisley — APPROVED** [review]
LGTM :)

File: internal/db/fetcher/indexer_iterators.go (hunk 1 above)
Comment (islamaliev) [reply internal/db/fetcher/indexer_iterators.go]: done
