### PR TITLE
fix: Mutation of branchable collection

### LINKED ISSUE #4185: Not possible to mutate branchable collection
```go
func TestBranchableCollection_AddingFieldViaPatching_ShouldSucceed(t *testing.T) {
	test := testUtils.TestCase{
		Actions: []any{
			testUtils.RandomNetworkingConfig(),
			testUtils.RandomNetworkingConfig(),
			&action.AddSchema{
				Schema: `
					type User @branchable {
						name: String
					}
				`,
			},
			testUtils.CreateDoc{
				NodeID: immutable.Some(0),
				DocMap: map[string]any{
					"name": "John",
				},
			},
			testUtils.CreateDoc{
				NodeID: immutable.Some(0),
				DocMap: map[string]any{
					"name": "Islam",
				},
			},
			testUtils.PatchCollection{
				NodeID: immutable.Some(0),
				Patch: `
					[
						{ "op": "add", "path": "/User/Fields/-", "value": {"Name": "email", "Kind": 11} }
					]
				`,
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
}
```
Get this result:
```
Error:     Received unexpected error:
           mutating IsBranchable is not supported. Collection: User
```

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4185 

## Description

This fix makes it possible to mutate branchable collections

### CODE REVIEW

File: tests/integration/collection_version/updates/add/branchable_test.go [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+import (
+	"testing"
+
+	"github.com/sourcenetwork/immutable"
+
+	"github.com/sourcenetwork/defradb/tests/action"
+	testUtils "github.com/sourcenetwork/defradb/tests/integration"
+)
+
+func TestBranchableCollection_AddNewField_ShouldAddField(t *testing.T) {
```
Comment (AndrewSisley) [inline tests/integration/collection_version/updates/add/branchable_test.go]: suggestion: You could simplify this test by removing the create document actions and query and instead call `GetCollections`.  At the moment there is quite a lot going on and I would argue that a lot of it is irrelevant (multiple docs, one on the far side of the patch) - even if we felt like we want to test that situation, my preference would be to have the simple test followed by a more complicated document test with documentation detailing exactly why we felt the need to create documents in that order.

By creating docs in the current manner the code is suggesting that it *is* important, without explaining why.

**Review by AndrewSisley — APPROVED** [review]
LGTM, but I suggest simplifying the test before merge

File: tests/integration/collection_version/updates/add/branchable_test.go (hunk 1 above)
Comment (islamaliev) [reply tests/integration/collection_version/updates/add/branchable_test.go]: added simpler test
