### PR TITLE
fix: Patching of new fields on cols with sec. relations

### LINKED ISSUE #4707: PatchCollection fails to set CRDT if secondary relationship exists on collection
Produced on defra version dev-develop (150204c3 2026-03-09)

The following error is returned:
```
Error: failed to add collection: no type found for given name. Field: after, Kind: Self-1
```
When adding the collections:
```gql
type Dev_RC_Domain2 {
    createdAt: DateTime
    updatedAt: DateTime
    verifiedAt: DateTime
    lastCheckAt: DateTime

    user: Dev_RC_User
    fqdn: String @index(unique: true)
    verificationToken: String @index(unique: true)

    routes: [Dev_RC_RedirectRoute2]
    firstRoute: Dev_RC_RedirectRoute2 @primary @relation(name: "domain_first_route")
    lastRoute: Dev_RC_RedirectRoute2 @primary @relation(name: "domain_last_route")
}

type Dev_RC_RedirectRoute2 {
    createdAt: DateTime
    updatedAt: DateTime

    firstForDomain: Dev_RC_Domain2 @relation(name: "domain_first_route")
    lastForDomain: Dev_RC_Domain2 @relation(name: "domain_last_route")

    publicID: String
    user: Dev_RC_User
    domain: Dev_RC_Domain2
    after: Dev_RC_RedirectRoute2
    if: JSON
    then: JSON
    with: JSON
    logging: JSON
    campaign: JSON
}
```
Omitting, then patching in the `after` field works, but will then fail when trying to add a document to the collection with `[ { message: 'unknown crdt. Type: none' } ]`.  This looks like it might be a separate bug, but I'm not sure.

Patch:
```
'[
  { "op":"add", "path":"/Dev_RC_RedirectRoute/Fields/-", "value": { "Name":"_afterID", "Kind":1, "Typ":1, "RelationName":"dev_rc_redirectroute_dev_rc_redirectroute", "IsPrimary":true } },
  { "op":"add", "path":"/Dev_RC_RedirectRoute/Fields/-", "value": { "Name":"after", "Kind":{ "RelativeID":"", "Array":false }, "Typ":0, "RelationName":"dev_rc_redirectroute_dev_rc_redirectroute", "IsPrimary":true } }
]'
```

Describe result post-patch:
```json
[
  {
    "Name": "Dev_RC_RedirectRoute",
    "VersionID": "bafyreibrbgug3s7bklwae3oaz4ztu44lbas54wvgelkd5ggqsznr5lemam",
    "CollectionID": "bafyreid7m7uap6vsnkfxdfocgfzstbka5rktla6dytid4gchwzrzodxmve",
    "CollectionSet": null,
    "Query": null,
    "PreviousVersion": {
      "SourceCollectionID": "bafyreidgejdf4jhi2nxhbwcx2fac462bs73wybsz7l37l7ge5tnyxxfhju",
      "Transform": null
    },
    "Fields": [
      {
        "FieldID": "bafyreihqzhiz3iwro4jozp6kphq4sosg6ccoqcbiaf7rg5dmvea7aux55a",
        "Name": "_docID",
        "Kind": 1,
        "Typ": 0,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreifcjs4e4cojrhm5uv2lgvqf6aaveykezhtg7z7mgktgbrqbbificq",
        "Name": "_domainID",
        "Kind": 1,
        "Typ": 1,
        "RelationName": "dev_rc_domain_dev_rc_redirectroute",
        "IsPrimary": true,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreibkuuiwnvxrunt5bblguyyw63r7wbznbf4njivchzq4ldz3zutpz4",
        "Name": "_userID",
        "Kind": 1,
        "Typ": 1,
        "RelationName": "dev_rc_redirectroute_dev_rc_user",
        "IsPrimary": true,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreihqeurepuzop4lxppy6pmjiqywb7msejdhrmvat7meje27g6yyphq",
        "Name": "createdAt",
        "Kind": 10,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreicihbjg774d6bwusdkyiep2gvsu3jg4wdtcaq7hbrq2wn6ima5ssy",
        "Name": "domain",
        "Kind": {
          "Array": false,
          "CollectionID": "bafyreieqd474wxepso5mhv6sozx76cxb4fdfxmpogxde4ijagbq2tl5mdm"
        },
        "Typ": 0,
        "RelationName": "dev_rc_domain_dev_rc_redirectroute",
        "IsPrimary": true,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreiezx6lwbi23im2wphwtrzxggqbpc6bvglddlx3kdce6khwrxfsvqe",
        "Name": "sub",
        "Kind": 11,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreigqtp5wz6mqus5ajo25xkzkly4cm3ny26riy7krnjxzfbvcm5rgyy",
        "Name": "target",
        "Kind": 11,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreiepubluqkvv5y6vc5w64ezzokpo7qcm2wbj7vpdkvfrlux7htqnh4",
        "Name": "updatedAt",
        "Kind": 10,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreia4a43mppjn53ddtg7pbnz6oqmnl2dxkwqd6jd52vhe3ew2olzgoy",
        "Name": "user",
        "Kind": {
          "Array": false,
          "CollectionID": "bafyreidhiml46yqtblrouxkjqvwqrvbqbgebz7qae63llj54yvk7az4tii"
        },
        "Typ": 0,
        "RelationName": "dev_rc_redirectroute_dev_rc_user",
        "IsPrimary": true,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreidqxngni7kbds2766tfvc7dtdawaukkq2qow7i65qj2tka3c5ne7i",
        "Name": "if",
        "Kind": 14,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreidn5xcflgzitlfq665comvgx4ka27fzmtosoiompklqbcbe2tzloe",
        "Name": "then",
        "Kind": 14,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreide2r4ibxribomnjsrr7lyzppoq3ogqbqeehyq3vbmvzcquuy3oju",
        "Name": "with",
        "Kind": 14,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreic2bmelstguo5pjc4tgbuuxelbsihlczvbiyjpw4lwppiyjp4y7ui",
        "Name": "logging",
        "Kind": 14,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreihhuk4lzdhg2eplwhj6aivpm5svoiq7tl3iflqv2gj7zrcccvfd7m",
        "Name": "campaign",
        "Kind": 14,
        "Typ": 1,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreigllcbpjah53fwctmiwpeor6ipfg753marvydil5s572pt44slw3m",
        "Name": "_afterID",
        "Kind": 1,
        "Typ": 1,
        "RelationName": "dev_rc_redirectroute_dev_rc_redirectroute",
        "IsPrimary": true,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "",
        "Name": "after",
        "Kind": {
          "RelativeID": "",
          "Array": false
        },
        "Typ": 0,
        "RelationName": "dev_rc_redirectroute_dev_rc_redirectroute",
        "IsPrimary": true,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "bafyreie4j3rw3hw5x7eavcdvcarm4vytg2sor4m4sc3reyrl4ken2etxt4",
        "Name": "publicID",
        "Kind": 11,
        "Typ": 0,
        "RelationName": null,
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "",
        "Name": "firstForDomain",
        "Kind": {
          "Array": false,
          "CollectionID": "bafyreieqd474wxepso5mhv6sozx76cxb4fdfxmpogxde4ijagbq2tl5mdm"
        },
        "Typ": 0,
        "RelationName": "domain_first_route",
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      },
      {
        "FieldID": "",
        "Name": "lastForDomain",
        "Kind": {
          "Array": false,
          "CollectionID": "bafyreieqd474wxepso5mhv6sozx76cxb4fdfxmpogxde4ijagbq2tl5mdm"
        },
        "Typ": 0,
        "RelationName": "domain_last_route",
        "IsPrimary": false,
        "DefaultValue": null,
        "Size": 0
      }
    ],
    "Indexes": [
      {
        "Name": "Dev_RC_RedirectRoute__domainID_ASC",
        "ID": 1,
        "Fields": [
          {
            "Name": "_domainID",
            "Descending": false
          },
          {
            "Name": "sub",
            "Descending": false
          }
        ],
        "Unique": true
      }
    ],
    "EncryptedIndexes": [],
    "Policy": null,
    "IsActive": true,
    "IsMaterialized": true,
    "IsBranchable": false,
    "IsEmbeddedOnly": false,
    "IsPlaceholder": false,
    "VectorEmbeddings": []
  }
]
```
`add document` command:
```gql
mutation AddRedirectRoute($createdAt:DateTime,$updatedAt:DateTime,$domainDocID:ID,$userDocID:ID,$publicID:String,$if:JSON,$then:JSON,$with:JSON,$logging:JSON,$campaign:JSON) {
        add_RedirectRoute: add_Dev_RC_RedirectRoute(input:{createdAt:$createdAt,updatedAt:$updatedAt,domain:$domainDocID,user:$userDocID,publicID:$publicID,if:$if,then:$then,with:$with,logging:$logging,campaign:$campaign,after:null}) {
                routeDocID: _docID routeID: publicID if then with logging campaign
        }
}
```
`add document` variables:
```
{
  createdAt: '2026-04-11T18:48:43.161Z',
  updatedAt: '2026-04-11T18:48:43.161Z',
  domainDocID: 'bae-6fd70af7-beeb-5b9c-b51a-5af97e0957fb',
  userDocID: 'bae-b28099ad-8020-5c81-afec-61e8c9b91fda',
  publicID: 'T8EBUgmKjconR43iysdUIYme',
  if: {
    or: [
      {
        and: [
          { type: 'path', match: 'prefix', value: 'foo/bar' },
          { type: 'lang', value: [ 'en', 'jp' ] }
        ]
      },
      { and: [ { type: 'path', match: 'exact', value: 'foobar' } ] }
    ]
  },
  then: {
    protocol: 'https://',
    url: 'to.tld',
    query: 'oq={{query}}',
    hash: '',
    status: 302
  },
  with: { cache: 600, headers: [ { name: 'x-foo', value: 'bar' } ] },
  logging: { retention: 30, counts: 'daily', ip: false, headers: true },
  campaign: {}
}
```

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #4707

## Description

Fixes the patching of new fields on collections with existing secondary relations.

Previously they were being created without a CRDT unless one was explicitly provided, causing subsequent document creation to fail.

Bug found by Kyle.

### CODE REVIEW

**Review by shahzadlone — APPROVED** [review]
LGTM

File: tests/integration/collection_version/updates/add/field/add_test.go [hunk 1]
```diff
@@ -122,3 +122,47 @@ func TestCollectionVersionUpdatesAddFieldWithAddAfterCollectionUpdate(t *testing
 	}
 	testUtils.ExecuteTestCase(t, test)
 }
+
+// This test documents a bug that was found as part of https://github.com/sourcenetwork/defradb/issues/4707
+// it only occured when adding a field to a collection that already has a secondary relationship.
```
Comment (fredcarle) [inline tests/integration/collection_version/updates/add/field/add_test.go]: thought: This comments makes it seem like the bug still exists but then the results seem to show that it's working fine. Might be worth reworking the language a little.

File: docs/data_format_changes/i4707-sec-rel-field-patches.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+# PatchCollection fails to set CRDT if secondary relationship exists on collection
+
+New fields added to collections that already had a secondary relation would fail to set a default CRDT if one was not explicitly provided.  Those newly added fields will not work properly and should be deprecated.
```
Comment (fredcarle) [inline docs/data_format_changes/i4707-sec-rel-field-patches.md]: thought: "Those newly added fields will not work properly and should be deprecated". This breaking change documentation seems to say that the change is causing a regression. Please reword this for clarity.

**Review by fredcarle — APPROVED** [review]
Approving with 2 comments that I'd like to resolve before merge.

File: docs/data_format_changes/i4707-sec-rel-field-patches.md (hunk 2 above)
Comment (AndrewSisley) [reply docs/data_format_changes/i4707-sec-rel-field-patches.md]: Rewritten.

File: tests/integration/collection_version/updates/add/field/add_test.go (hunk 1 above)
Comment (AndrewSisley) [reply tests/integration/collection_version/updates/add/field/add_test.go]: Wording altered
