### PR TITLE
fix: Index on JSON _geq and _leq null filter ops

### LINKED ISSUE #4398: JSON nested null filter returns wrong results
Comparison operators with `null` value on nested JSON paths return fewer results than expected

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4398

## Description

Use index only for top-level `_leq: null` filter. Other cases like json nested `_leq` or any `_geq` are ignore by index as there is no benefit of using index there.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Integration tests

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/db/fetcher/indexer_iterators.go [hunk 1]
```diff
@@ -762,6 +762,15 @@ func (f *indexFetcher) determineFieldFilterConditions() ([]fieldFilterCond, erro
 						return true
 					}
 
+					// For _geq: null, every value is >= null, so the index provides no benefit -
```
Comment (fredcarle) [inline internal/db/fetcher/indexer_iterators.go:765]: praise: Thanks for the documentation.

**Review by fredcarle — APPROVED** [review]
LGTM
