### PR TITLE
fix: Document change detector breaking change

### LINKED ISSUE #1530: Change detector panics in develop after fix
```shell
=== FAIL: tests/integration/query/one_to_one TestQueryOneToOneWithIdFieldOnPrimary (0.03s)
2023-05-24T22:54:10.519-0400, INFO, tests.integration, One-to-one relation primary direction, id field with name clash on primary side, {"Database": "badger-file-system"}
2023-05-24T22:54:10.539-0400, INFO, db, Closing DefraDB process...
2023-05-24T22:54:10.548-0400, INFO, db, Successfully closed running process
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x100f2ec68]

goroutine 4490 [running]:
testing.tRunner.func1.2({0x1015602c0, 0x10222fbd0})
	/usr/local/go/src/testing/testing.go:1396 +0x1c8
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1399 +0x378
panic({0x1015602c0, 0x10222fbd0})
	/usr/local/go/src/runtime/panic.go:884 +0x204
github.com/sourcenetwork/defradb/tests/integration.getDocuments({0x1017a4e70, 0x14000046090}, 0x140008feb70?, {{0x101100f5a, 0x4f}, {0x140008feb70, 0x3, 0x3}}, {0x1400020a1e0, 0x1, ...}, ...)
	/private/var/folders/5j/5mpqq_mj103gyyb21sd1smr00000gn/T/defradb/tests/changeDetector/code/20e9286eee169fb2186b6ad00d648818b7373564/tests/integration/utils2.go:806 +0x288
github.com/sourcenetwork/defradb/tests/integration.executeTestCase({0x1017a4e70, 0x14000046090}, 0x140004c2820, {0x14000869e70, 0x2, 0x2}, {{0x101100f5a, 0x4f}, {0x140008feb70, 0x3, ...}}, ...)
	/private/var/folders/5j/5mpqq_mj103gyyb21sd1smr00000gn/T/defradb/tests/changeDetector/code/20e9286eee169fb2186b6ad00d648818b7373564/tests/integration/utils2.go:316 +0x254
github.com/sourcenetwork/defradb/tests/integration.ExecuteTestCase(0x10167d3e0?, {0x14000869e70, 0x2, 0x2}, {{0x101100f5a, 0x4f}, {0x140008feb70, 0x3, 0x3}})
	/private/var/folders/5j/5mpqq_mj103gyyb21sd1smr00000gn/T/defradb/tests/changeDetector/code/20e9286eee169fb2186b6ad00d648818b7373564/tests/integration/utils2.go:283 +0x354
github.com/sourcenetwork/defradb/tests/integration/query/one_to_one.TestQueryOneToOneWithIdFieldOnPrimary(0x1400024d200?)
	/private/var/folders/5j/5mpqq_mj103gyyb21sd1smr00000gn/T/defradb/tests/changeDetector/code/20e9286eee169fb2186b6ad00d648818b7373564/tests/integration/query/one_to_one/with_id_field_test.go:116 +0x220
testing.tRunner(0x140004c2820, 0x101789358)
	/usr/local/go/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x300
```

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #1530 

## Description

This PR fixes the previous fix and adds a breaking change document to prevent the broken cycle in the change detector after the fix. Should have been part of the #1528 although the change detector was passing before merge.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test:changes

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Comment by shahzadlone** [comment]
Why did the change detector not catch that in the last PR? is it broken?

File: tests/integration/utils2.go [hunk 1]
```diff
@@ -560,6 +558,7 @@ ActionLoop:
 			// We must not set this to -1 :)
 			startIndex = firstNonSetupIndex
 		} else {
+			// if we down't have any non-mutation actions, just use the last action
```
Comment (shahzadlone) [inline tests/integration/utils2.go:561]: todo:
```suggestion
			// if we don't have any non-mutation actions, just use the last action
```

Comment (fredcarle) [reply tests/integration/utils2.go:561]: thanks for catching this.

**Comment by shahzadlone** [comment]
question: Did you test that it fails even in this branch without the documentation? and then once the documentation is added it works?

**Comment by fredcarle** [comment]
> question: Did you test that it fails even in this branch without the documentation? and then once the documentation is added it works?

I did. I basically recreated the changes on my fork without the regression and it works fine. Here we need the change documentation to prevent the regression from failing the change detector check.

**Review by shahzadlone — APPROVED** [review]
Thanks for taking care of this. Fingers crossed :P hopefully no more fails on develop.
