### PR TITLE
fix: Treat multiple filters as AND when join is inverted

### LINKED ISSUE #4314: Multiple filters do not appear to be treated as `_and` clauses
Posted in `dev-dv`.`confused by query results (filtering behavior)` https://discord.com/channels/1374835078781468722/1452940620325978142

```
query GetPasskeyCredential($credentialID:String,$userIsEnabled:Boolean,$userID:String) {
        PasskeyCredential: Dev_RC_PasskeyCredential(filter:{credentialID:{_eq:$credentialID},user:{isEnabled:{_eq:$userIsEnabled},publicID:{_eq:$userID}}}) {
                publicKeySPKI publicKeyAlgoCOSE credentialID user { publicID }
        }
}
```

And here's the vars I pass into it:
```
{
  credentialID: 'AOWrPXX4jS504tsAT6/zEA==',
  userIsEnabled: true,
  userID: 'nUV6e3sbciL+KeWsdVEEsbuP'
}
```

Now, there are 3 entries in my `PasskeyCredential` collection right now, all for the same user, but only one of them has the specified credentialID... so I'm expecting that query to return just one result (given that my 3 filters should combine as "AND" according to the docs, AFAICT).

```
[
  {
    credentialID: 'r2fdP6Ydwds3s2VwTEfQeGgN+2oLFCa/DMWuo5ka+gc=',
    publicKeyAlgoCOSE: -7,
    publicKeySPKI: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+NAT861Mk+hKJodOV/kfDY+pdO2yDZJncJgZlTT2ZYK9AcVWDhsWL9oF/2EY/za8NL/deVEZ1Ylz4BpRi5Khcg==',
    user: { publicID: 'nUV6e3sbciL+KeWsdVEEsbuP' }
  },
  {
    credentialID: 'AOWrPXX4jS504tsAT6/zEA==',
    publicKeyAlgoCOSE: -7,
    publicKeySPKI: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdY/y1sdUcDDiTvhEeigSIUbBtYTHpwUPVVDl9/Vs71bIyOdDfWoeduMM3EkCYDLoy1WAiA+oKwLe6hW53f3nNQ==',
    user: { publicID: 'nUV6e3sbciL+KeWsdVEEsbuP' }
  },
  {
    credentialID: 'ATSd8SK6bIAggBdG1KEA1OButQrxjEidN1ijnfUjlxkPKLZPzUtZsuA3XlzrD32w70RaOKlRWwDZ/chy9/PmmbY=',
    publicKeyAlgoCOSE: -7,
    publicKeySPKI: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/kcvO18qMlDcfBxzgLzc6V7c7g7Q1rOGVxxFciedgSU7cXdKI8hY986cKDfetQI3wFgOz3wLSWKbOvuM3S4cdA==',
    user: { publicID: 'nUV6e3sbciL+KeWsdVEEsbuP' }
  }
]
```
```
type Dev_RC_User {
    createdAt: DateTime
    updatedAt: DateTime

    publicID: String @index(unique: true)
    firstName: String
    lastName: String
    isEnabled: Boolean
    accountLevel: Int

    emails: [Dev_RC_Email]
    passkeys: [Dev_RC_PasskeyCredential]
    domains: [Dev_RC_Domain]
    recoveryCodes: [String]
}

type Dev_RC_PasskeyCredential {
    createdAt: DateTime
    updatedAt: DateTime
    lastUsedAt: DateTime
    revokedAt: DateTime

    user: Dev_RC_User
    label: String
    credentialID: String @index(unique: true)
    publicKeyRaw: String @index(unique: true)
    publicKeySPKI: String @index(unique: true)
    publicKeyAlgoCOSE: Int
    publicKeyAlgoOID: String
    discoverable: Boolean
    credentialBackup: Boolean
    AAGUID: String
    attachment: String
    transports: [String]
}
```
Issue is probably index related:
> There's [probably] a bug in the way we're running filters. The user part of the filter is running as an AND, and the "root type" (the credential) is running as a separate AND, of which the two are OR'd together.

### PR DESCRIPTION
**Pull request by islamaliev**
## Relevant issue(s)

Resolves #4314

## Description

When a query filter combines scalar conditions with a relation condition at the top level without explicit `_and`, the scalar conditions were silently dropped if the join got inverted for index optimization. For example, `Book(filter: {rating: {_gt: 4.5}, author: {name: {_eq: "John Grisham"}}})` would ignore the rating condition and return all books by John Grisham. Using explicit `_and` worked around this because it triggered a different code path that kept all conditions together.

The problem was in `retrievePrimaryDocs`. When the join is inverted, the parent scan becomes the second side and its filter gets overwritten with just the relation ID lookup. Any scalar conditions that were sitting on the parent scan were lost. The fix merges the parent scan's original filter into the retrieval filter before overwriting, and properly saves/restores it afterward.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Added integration tests covering mixed scalar + relation filters with and without explicit `_and`, verifying they produce the same results.

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: internal/planner/type_join.go [hunk 1]
```diff
@@ -644,13 +644,25 @@ func (r *primaryObjectsRetriever) collectDocs() ([]core.Doc, error) {
...
-	r.primaryScan.filter = addFilterOnField(r.filter, r.primarySide.relIDFieldMapIndex.Value(),
+	scanFilter := addFilterOnField(r.filter, r.primarySide.relIDFieldMapIndex.Value(),
 		r.targetSecondaryDoc.GetID())
 
+	// When the join is inverted, the parent becomes the primary (second) side.
+	// Its scan may still hold scalar filter conditions (e.g., rating > 4.5) that
+	// prepareScanNodeFilterForTypeJoin left there. Since the original scan is not
+	// iterated in the inverted path, merge those conditions so they are applied
+	// during retrieval.
+	if r.primarySide.isParent && r.primaryScan.filter != nil {
```
Comment (fredcarle) [inline internal/planner/type_join.go:655]: todo: This solves one direction but it seems to fail in the other. Here is a test that demonstrates what I mean.
```
// TestQueryWithIndex_FromSecondarySideWithScalarAndRelationFilter_ShouldApplyBothAsAnd
// queries from the secondary (non-FK) side with a scalar filter on the queried collection
// and a relation filter containing a scalar condition on the primary (FK-holding) side.
// This exercises the path where the primary side is NOT the parent, verifying that the
// isParent guard in retrievePrimaryDocs is sufficient — the child's scalar conditions are
// already captured in subFilter and don't need a separate merge.
func TestQueryWithIndex_FromSecondarySideWithScalarAndRelationFilter_ShouldApplyBothAsAnd(t *testing.T) {
	test := testUtils.TestCase{
		Actions: []any{
			&action.AddCollection{
				SDL: `
					type Author {
						name: String @index
						age: Int
						published: [Book]
					}

					type Book {
						title: String
						rating: Float
						author: Author
					}
				`,
			},
			&action.AddDoc{
				CollectionID: 0,
				Doc: `{
					"name": "John Grisham",
					"age": 69
				}`,
			},
			&action.AddDoc{
				CollectionID: 0,
				Doc: `{
					"name": "Cornelia Funke",
					"age": 57
				}`,
			},
			&action.AddDoc{
				CollectionID: 1,
				DocMap: map[string]any{
					"title":  "Painted House",
					"rating": 4.9,
					"author": testUtils.NewDocIndex(0, 0),
				},
			},
			&action.AddDoc{
				CollectionID: 1,
				DocMap: map[string]any{
					"title":  "A Time to Kill",
					"rating": 4.0,
					"author": testUtils.NewDocIndex(0, 0),
				},
			},
			&action.AddDoc{
				CollectionID: 1,
				DocMap: map[string]any{
					"title":  "Thief Lord",
					"rating": 4.8,
					"author": testUtils.NewDocIndex(0, 1),
				},
			},
			&action.AddDoc{
				CollectionID: 1,
				DocMap: map[string]any{
					"title":  "Inkheart",
					"rating": 4.4,
					"author": testUtils.NewDocIndex(0, 1),
				},
			},
			// Query from Author (secondary side) with a scalar filter on Author
			// and a relation filter with a scalar condition on Book (primary side).
			// Book is primary but NOT the parent — the isParent merge should NOT fire,
			// yet the Book scalar filter (rating > 4.5) must still be applied.
			&action.Request{
				Request: `query {
					Author(filter: {age: {_gt: 60}, published: {rating: {_gt: 4.5}}}) {
						name
						age
						published {
							title
							rating
						}
					}
				}`,
				Results: map[string]any{
					"Author": []map[string]any{
						{
							"name": "John Grisham",
							"age":  int64(69),
							"published": []map[string]any{
								{
									"title":  "Painted House",
									"rating": 4.9,
								},
							},
						},
					},
				},
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
}
```

Comment (fredcarle) [reply internal/planner/type_join.go:655]: Never mind. I initially thought the filter should apply to the relationship but it shouldn't.  It should only use the relationship to filter the parent.

**Review by fredcarle — APPROVED** [review]
LGTM
