### PR TITLE
fix: Allow update when updating non-indexed field

### LINKED ISSUE #2510: Updating non indexed field of doc with unique index fails
Updating unique indexed field on a given doc succeeds but updating a non indexed field of a doc with a unique index fails. The following should succeed but it fails with the error:
```
can not index a doc's field(s) that violates unique index. DocID: bae-b0a35b3c-486b-54fc-8736-eeff036414ef, name: Fred.
```
```go
func TestUniqueIndexUpdate_UponUpdatingDocNonIndexedField_ShouldSucceed(t *testing.T) {
	test := testUtils.TestCase{
		Actions: []any{
			testUtils.SchemaUpdate{
				Schema: `
					type User {
						name: String @index(unique: true)
						age: Int
					}
				`,
			},
			testUtils.CreateDoc{
				CollectionID: 0,
				Doc: `
					{
						"name":	"Fred",
						"age":	36
					}`,
			},
			testUtils.UpdateDoc{
				CollectionID: 0,
				DocID:        0,
				Doc: `
					{
						"age":	37
					}`,
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
}
```

There is also a similar behaviour for composite indexes where the following should succeed but fails with the error:
```
can not index a doc's field(s) that violates unique index. DocID: bae-cae3deac-d371-5a1f-93b4-ede69042f79b, name: John, age: 21
```
```go
func TestUniqueCompositeIndexUpdate_UponUpdatingDocWithExistingFieldValue_ShouldSucceed(t *testing.T) {
	test := testUtils.TestCase{
		Actions: []any{
			testUtils.SchemaUpdate{
				Schema: `
					type User @index(unique: true, fields: ["name", "age"]) {
						name: String 
						age: Int 
						email: String
					}
				`,
			},
			testUtils.CreateDoc{
				CollectionID: 0,
				Doc: `
					{
						"name":	"John",
						"age":	21,
						"email": "email@gmail.com"
					}`,
			},
			testUtils.UpdateDoc{
				CollectionID: 0,
				DocID:        0,
				Doc: `
					{
						"email": "another@gmail.com"
					}`,
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
}
```

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #2510 

## Description

This PR adds a check to the index validation step where if the resulting KV pair is the same on update as the previous KV pair, the outcome will be an no-op instead of an index existing error.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

File: db/collection_index.go [hunk 1]
```diff
@@ -588,3 +592,18 @@ func generateIndexName(col client.Collection, fields []client.IndexedFieldDescri
 	}
 	return sb.String()
 }
+
+func isUpdatingIndexedFields(index CollectionIndex, doc *client.Document) bool {
```
Comment (islamaliev) [inline db/collection_index.go:596]: suggestion: I think it's better to compare 2 docs here. What if an update is requested, but to the same value? Will `val.IsDirty` return true?

You can instead pass here 2 docs and do something like:
```go
for _, indexedFields := range index.Description().Fields {
	newVal := newDoc.GetValue(indexedFields.Name)
	oldVal := oldDoc.GetValue(indexedFields.Name)
	if newVal.Value() != oldVal.Value() {
		return true
	}
}
```
This way you don't need to iterate through all `doc.Fields()` but only indexed ones.

File: tests/integration/index/update_unique_composite_test.go [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+package index
+
+import (
+	"testing"
+
+	testUtils "github.com/sourcenetwork/defradb/tests/integration"
+)
+
+func TestUniqueCompositeIndexUpdate_UponUpdatingDocWithExistingFieldValue_ShouldSucceed(t *testing.T) {
```
Comment (islamaliev) [inline tests/integration/index/update_unique_composite_test.go:19]: praise: thanks for adding a test for the composite one.

**Review by islamaliev — APPROVED** [review]
Good catch and good job fixing it! I just have some clarifying comments.

File: db/collection_index.go (hunk 1 above)
Comment (fredcarle) [reply db/collection_index.go]: > What if an update is requested, but to the same value? Will val.IsDirty return true?
Yes.

I like that suggestion. It will ensure we don't try to update the index if the indexed field values are set to the same value 👍

Comment (fredcarle) [reply db/collection_index.go]: ✅

Comment (fredcarle) [reply db/collection_index.go]: I'll wait for you to check the change before merging.

File: db/collection_index.go [hunk 3]
```diff
@@ -197,9 +197,13 @@ func (c *collection) updateIndexedDoc(
 		return err
 	}
 	for _, index := range c.indexes {
-		err = index.Update(ctx, txn, oldDoc, doc)
-		if err != nil {
-			return err
+		// We only need to update the index if one of the indexed fields
+		// on the document has been changed.
+		if isUpdatingIndexedFields(index, oldDoc, doc) {
```
Comment (jsimnz) [inline db/collection_index.go:202]: question(cc: @islamaliev): Should this be done inside the `index.Update` func, instead of here? This will A) allow different index types to handle this differently B) Gurantees this behavior is consistent regardless of where `index.Update` is called from (vs doing it here which is only fixed for this particular call path).

File: db/collection_index.go (hunk 1 above)
Comment (fredcarle) [reply db/collection_index.go]: @islamaliev still waiting for you to check the change :)

File: db/collection_index.go (hunk 3 above)
Comment (islamaliev) [reply db/collection_index.go:202]: I also thought about this, but though it would be unlikely to have any other update behaviour.
Although, thinking about it again we don't know what will be in the future especially when we decide to index array or json fields or some other fancy stuff.

Comment (fredcarle) [reply db/collection_index.go]: Moved ✅

File: db/index.go [hunk 4]
```diff
@@ -381,6 +381,11 @@ func (index *collectionUniqueIndex) Update(
 	oldDoc *client.Document,
 	newDoc *client.Document,
 ) error {
+	// We only need to update the index if one of the indexed fields
+	// on the document has been changed.
+	if !isUpdatingIndexedFields(index, oldDoc, newDoc) {
```
Comment (islamaliev) [inline db/index.go:386]: suggestion: I think it also makes sense to do this check for regular indexes otherwise they will do unnecessary work with storage.

**Review by islamaliev — COMMENTED** [review]
LGTM! Just have a final suggestion.

File: db/index.go (hunk 4 above)
Comment (fredcarle) [reply db/index.go:386]: I'll open a new PR to cover that case 👍
