### PR TITLE
fix: Add missing return after successful merge execution

### LINKED ISSUE #4355: Merge retry loop missing return on success causes unnecessary repeated execution
The `Merge` function in `internal/db/merge.go`  is missing a `return nil` statement after successful execution. This causes the loop to continue iterating even when `executeMerge` succeeds, resulting in every merge operation running up to `MaxTxnRetries` times instead of once.

### PR DESCRIPTION
**Pull request by SharanRP**
## Relevant issue(s)

Resolves #4355

## Description

This PR fixes a bug in the merge retry loop where the function was missing a `return nil` statement after successful execution.

**The problem:** In `internal/db/merge.go` the `Merge()` function's retry loop  didn't return on success, causing the loop to continue iterating. This resulted in every merge operation running up to `MaxTxnRetries` times instead of exiting immediately after the first successful execution.

**Why it went unnoticed:**
- Merging is idempotent, so repeated execution produces the same result
- Existing tests call `executeMerge()` directly, bypassing the retry loop

**The fix:** Added `return nil` after the successful execution case to exit the loop immediately.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Ran existing merge unit tests to verify the fix doesn't break current functionality

## Release Notes

* **Bug Fixes**
  * Merge operation now stops retrying once a merge completes successfully, reducing unnecessary retry cycles and improving merge completion time.
  * Behavior for conflict and error handling remains unchanged to preserve expected failure semantics.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: internal/db/merge.go [hunk 1]
```diff
@@ -72,6 +72,7 @@ func (db *DB) Merge(ctx context.Context, evt event.Merge) error {
 		if err != nil {
 			return err
 		}
+		return nil
```
Comment (fredcarle) [inline internal/db/merge.go:75]: praise: Nice catch! I wonder I'd be curious to know quantitatively the wasted overhead that this caused.

**Review by fredcarle — APPROVED** [review]
Thanks for this Sharan.
